### ISSUE TITLE
All Styling via JavaScript

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#109]
This one needs some discussion.

We like:
- The theme changing using the extended colors
- The removal of a css dependency while keeping the styles
- The option of change themes for ticks, labels, tooltips, etc
- The option of setting the font as an options

We don't like:
- The use of JS to style (but we need to do it anyways)

**Comment by abacaj** [comment]
What's wrong with using CSS to style svg elements, seems they already have class names associated to them?

**Comment by miglesiasEB** [comment]
Hi @abacaj, thanks for the question!

Well, there's nothing wrong about styling with CSS, and it's my preferred way. However, we are already doing some styling via JavaScript, as it usually happens on D3 based charts. That and the rest of the points on the 'we like' list makes us think that it could be a potential improvement.

That said, we want to see what the community thinks about it. I would count your comment as a -1, right?

**Comment by miglesiasEB** [comment]
Closing by lack of support
