### ISSUE TITLE
Create React Wrapper

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#115]
Explore wrapping Britecharts into react components.

**Comment by ktcith** [comment]
Where can I find the react components for Britecharts?

**Comment by Golodhros** [comment]
Hi @ktcith, this feature will be necessary for us in the short term. I expect to work on this pretty soon!

**Comment by adack123** [comment]
Hi @Golodhros, I'm curious as to where anyone is on this, or if its being explored at all. I'm currently wrapping Britecharts into react components in a separate project. This seems like something that would live in the docs, just as an implementation detail considering britecharts isn't specifically tailored toward react, but you all might have something else in mind.

I'd be open to PRing this. Thoughts?

**Comment by Golodhros** [comment]
Hi @adack123, thanks for your question!

Yes, is something we will be working soon, in the next month. Up to now, we have a specification of it. It will be in a different repo though.

I just asked for that repo to be created, I will then move the specification there and ping you so that you can take a look and help us build it if it works for you, what do you think?

**Comment by adack123** [comment]
@Golodhros Sounds good to me :+1:

**Comment by Golodhros** [comment]
Hi @adack123, sorry for the delay!

Here is the repo we will use for the project: https://github.com/eventbrite/britecharts-react

We will be starting to work on this in the next two weeks by our last estimations...

**Comment by Golodhros** [comment]
Closing, we are really close to version 1 in Britecharts React!
