### ISSUE TITLE
Extract transitions into library

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#116]
Extract transitions into functions, follow:
```
var t = d3.transition()
.duration(750)
.ease(d3.easeLinear);
d3.selectAll(".apple").transition(t)
.style("fill", "red");
d3.selectAll(".orange").transition(t)
.style("fill", "orange");
```

We need to explore which transitions we will want to support.

**Comment by miglesiasEB** [comment]
I have just read this is a bad idea.
Using the same 'stored' transition would make the elements to move on sync, not just with the same animation characteristics.
