### ISSUE TITLE
Stacked Bar Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#118]
We want to create an stacked bar chart.

The current design for it would looke like:
![stacked-bar-chart-green](https://cloud.githubusercontent.com/assets/190833/26166996/5df88ce6-3aea-11e7-80f8-9fdaca933916.png)

**Comment by behrtam** [comment]
Would love to see stacked bar charts (https://bl.ocks.org/mbostock/3886208)!

**Comment by filipblaauw** [comment]
+1

**Comment by bung87** [comment]
![fireshot capture 108 - tutorial_ stacked-bar - http___localhost_8001_tutorial-stacked-bar html](https://cloud.githubusercontent.com/assets/2238294/26328187/9316a546-3f74-11e7-9bb1-a1da39312258.png)  

I'm working on this,and almost done the main chart render parts,need some time to work with other chart part,test and code clean.

**Comment by filipblaauw** [comment]
@bung87 Looks very nice!

**Comment by Golodhros** [comment]
Ready, created by @bung87
