### ISSUE TITLE
Add x and y labels to bar, line and stacked area charts

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#120]
We need to think how this could be extracted so that we don't duplicate code.

**Comment by cnwalker** [comment]
I'd be interested in taking this on

**Comment by Golodhros** [comment]
Great!! Go for it!

You could use the same code you added to the step chart. I would only set a fixed offset on the X and Y axis for now. Later we could open those options if people need them!

Thanks a lot!!

**Comment by Golodhros** [comment]
Let's close this for now. Not many people seem interested.
