### ISSUE TITLE
Create Scatter Plot

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#126]
Create a Scatter Plot chart

**Comment by henboffman** [comment]
Curious if this has gained any traction.

**Comment by rickgoud** [comment]
me too; would be great. Also if it would include bubble sizes and colors!

**Comment by DalerAsrorov** [comment]
Will have some time to work on it in upcoming days!

**Comment by skybondsor** [comment]
+1 for this, especially if it includes generating trendlines!

**Comment by dalerasrorov-eb** [comment]
Hey guys, I implemented initial work for Scatter Plot. More features will be added soon. Feel free to leave comments/feedback: https://github.com/eventbrite/britecharts/pull/560

**Comment by dalerasrorov-eb** [comment]
Scatter plot was created. All the new functionalities and fixes will be added with new issues.
