### ISSUE TITLE
Stacked area chart overshoots beyond axis line

### ISSUE THREAD

**Issue by evb-sun** [eventbrite/britecharts#129]

**Comment by evb-sun** [comment]
<img width="1140" alt="screen shot 2017-02-08 at 4 30 47 pm" src="https://cloud.githubusercontent.com/assets/13459095/22765184/c2e9b5f8-ee23-11e6-92d0-5e876ac076e0.png">
<img width="437" alt="screen shot 2017-02-08 at 5 20 30 pm" src="https://cloud.githubusercontent.com/assets/13459095/22765186/c5399206-ee23-11e6-95ee-357659550204.png">

Curved area chart 
1. overshoots beyond axis lines;
2. making data less accurate to read

**Comment by Golodhros** [comment]
Fixed on https://github.com/eventbrite/britecharts/pull/172
