### ISSUE TITLE
Categories Axis Labeling

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts#160]
Using category names can be tricky on bar charts and step chart.
Ryan came up with a good solution using the text wrapper function for the horizontal, but it could not be enough.

Let's explore the issue. Some reading:
* https://blog.graphiq.com/wrapping-axis-labels-in-d3-js-c29202c3e3e4#.dpr3x8uzf

## Expected Behavior
Category labels well positioned and wrapped

## Current Behavior
Working on Horizonal Line Chart

## Possible Solution
Use the same wrapping

**Comment by Golodhros** [comment]
Check https://bl.ocks.org/d3noob/0e276dc70bb9184727ee47d6dd06e915
