### ISSUE TITLE
Brush chart styling has solid slection area

### ISSUE THREAD

**Issue by rwholey-eb** [eventbrite/britecharts#174]
When selecting dates for the brush, the selection area is a solid opaque rectangle instead of the chart highlight

## Expected Behavior
we should see the chart highlight, not an opaque selection rectangle

## Possible Solution
brush styling

## Steps to Reproduce (for bugs)
1. Go to the kitchen sink
2. play with the brush

## Your Environment

* Version used: 1.4.4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): mac osx

![image](https://cloud.githubusercontent.com/assets/18017479/24162716/ab4bf196-0e25-11e7-80a0-161df96d3b73.png)

**Comment by Golodhros** [comment]
<img width="414" alt="britecharts_-_d3_js_based_charting_library_of_reusable_components" src="https://cloud.githubusercontent.com/assets/190833/24180740/eac8d85e-0e73-11e7-9b12-33d8047a249b.png">

Maybe we have a bigger problem?
Have you tried to remove the /docs folder altogether?

**Comment by Golodhros** [comment]
Fixed on  #181
