### ISSUE TITLE
Britecharts complete build doesn't provide the right structure

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#186]
When loading /dist/bundled/britecharts.min.js, either by ES6 imports, commonJS modules or AMD modules we are not getting the expected results.

## Expected Behavior
We should get an object with this structure: 
```
  britecharts: {
    bar: function...
    brush: function...
    ...
  }
```
## Current Behavior
Either getting just the first object or nothing being imported to the global scope (in script mode)

## Possible Solution
Right now, our individual charts are exporting the right object (AMD and CommonJS) or a global object (script load) with this shape: window.britecharts.chartName

We want the whole bundle to do the same, aggregating all the charts in an object named britecharts.
This way we should be able to do:
```
   import britehcarts from 'britecharts';
   import {bar} from 'britecharts';
```
or
```
   <script src="/dist/bundle/britecharts.min.js"></script>
   ...
   var barChart = window.britecharts.bar;
```
I hope the solution would be something we haven't tried yet on our webpack configuration.
prodUMD poduces our individual bundles all right
prod should produce the desired outcome. Right now looks like:
```
  prod: {
        entry:  {
            britecharts: currentChartsArray
        },
        devtool: 'source-map',
        output: {
            path: 'dist/bundled',
            filename: projectName + '.min.js',
            library: ['britecharts'],
            libraryTarget: 'umd'
        },
        externals: {
            d3: 'd3',
            underscore: 'underscore'
        },
        module: {
            loaders: [ defaultJSLoader ],
            // Tell Webpack not to parse certain modules.
            noParse: [
                new RegExp(vendorsPath + '/d3/d3.js')
            ]
        },
        resolve: {
            alias: {
                d3: vendorsPath + '/d3'
            }
        },
        plugins
    }
```

## Steps to Reproduce (for bugs)
1. Load `/dist/bundle/britecharts.min.js`
2. Check what gives back

## Context
This actually makes our bundle unusable.

**Comment by miglesiasEB** [comment]
Related: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by sblack4** [comment]
I think this is related to an issue I was having - with webpack (& typescript using es2015 modules) I was
`import {line} from "britecharts"` 
but running `line()` produced the error `line() is not a function` because nothing was being imported.

I solved this by placing an `index.js` file in the project's root folder 
```javascript
"use strict";

var bar = require("./dist/umd/bar.min.js");
var brush = require("./dist/umd/brush.min.js");
var colors = require("./dist/umd/colors.min.js");
var donut = require("./dist/umd/donut.min.js");
var legend = require("./dist/umd/legend.min.js");
var line = require("./dist/umd/line.min.js");
var miniTooltip = require("./dist/umd/mini-tooltip.min.js");
var sparkline = require("./dist/umd/sparkline.min.js");
var stackedArea = require("./dist/umd/stacked-area.min.js");
var step = require("./dist/umd/step.min.js");
// var tootltip = require("./dist/umd/tooltip.min.js");

module.exports = {
    bar
    , brush
    , colors
    , donut
    , legend
    , line
    , miniTooltip
    , sparkline
    , stackedArea
    , step
    // , tooltip
};
```

and pointing the package.json toward it by changing 

```json
  "license": "Apache-2.0",
  "main": "README.md",
  "maintainers": [
```
 to 

```json
  "license": "Apache-2.0",
  "main": "index.js",
  "maintainers": [
```

now everything seems to work, except the tooltip (I haven't figured that out yet) :smiley:

**Comment by Golodhros** [comment]
Hi @sblack4 thanks for your work there!

Yes, it seems that a solution like yours will work well! We have a couple of PRs that we will merge this weekend with similar solutions. From what I have seen, as we are formatting the output as UMD, the ES2015 modules don't seem to work, but it works as AMD/CommonJS modules or simple JS scripts.

Good call about the 'main'! I will definitely include it on the final solution!

Thanks again for your contribution!!

**Comment by Golodhros** [comment]
Hi @sblack4, this should be solved by now!

Thanks a lot for your insights, we have included the 'main' link too.

**Comment by sblack4** [comment]
@Golodhros  Thanks!
