### ISSUE TITLE
Need a REALLY Basic HTML Page

### ISSUE THREAD

**Issue by mmartimo** [eventbrite/britecharts#196]
I was hoping to be able to create a very simple single HTML page with a single chart or two so that the designers could do their thing and then we can incorporate their designs in Angular.

Is there any way to link a simple script tag with a src to have a single page with a chart?

With d3, the following works fine...  it'd be great to have something similar.

```
<!DOCTYPE html>
<html>
  <head>
 <meta charset='utf-8' />
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <script src="https://d3js.org/d3-selection.v1.min.js"></script>
  </head>
  <body>
    <div id='charts'>
      <h1 id='heading'></h1>
    </div>
    <script>
      d3.select('#heading')
        .text('My Page');
    </script>
  </body>
</html>
```

**Comment by Golodhros** [comment]
Hi Matthew,

Yes, you should be able to do something similar. You will need first to go to our [releases page][https://github.com/eventbrite/britecharts/releases] and download the library as a .zip file. Then, you could search within that folder for this path: `/dist/umd/` and pick one of the charts there, loading them with a script tag like this:

`<script src="pathToBritecharts/dist/umd/bar.min.js"></script>`

This will extend the global scope with an object named 'britecharts' and within it, you will find the bar chart (so it will be on `britecharts.bar`).

We are working on a ['bundled' version][https://github.com/eventbrite/britecharts/issues/186] that will be served via CDN and will contain all charts, making it easy to setup a sandbox to play with Britecharts.

Let me know if I can help you with anything else and thanks for using Britecharts!

**Comment by Golodhros** [comment]
@mmartimo Did this work? Can we help you any other way?

**Comment by perborgen** [comment]
@Golodhros Is it possible to do this with a hosted CDN at the moment?

**Comment by Golodhros** [comment]
@perborgen Almost!
We have an issue with our webpack configuration for creating the bundle: https://github.com/eventbrite/britecharts/issues/186, but once we solve that, our already set up CDN link will work fine!

**Comment by perborgen** [comment]
Awesome! When that's ready I plan to create a tutorial on the library at [Scrimba](https://scrimba.com/).

**Comment by Golodhros** [comment]
That's great! I will ping you soon (I hope!)

**Comment by laurikari** [comment]
I cannot make a simple HTML page work.  This does not work, for example:

`<!DOCTYPE html>
<html>
<head>
    <title>BriteCharts test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <script src="https://d3js.org/d3-selection.v1.min.js"></script>
    <script src="bar.min.js"></script>
</head>
<body>
    <div id="barContainer"></div>
    <script>
var barChart = new britecharts.bar();
var dataset = [
    {
	value: 1,
	name: 'glittering'
    },
    {
	value: 1,
	name: 'luminous'
    }
];
barChart
    .width('100%')
    .height(300);

var barContainer = d3.select('#barContainer');
var d = barContainer.datum(dataset);
d.call(barChart);
</script>
</body>
</html>
`

What could be wrong?  Could it be that he version of d3-selection inside the bundle is not compatible with the version of d3-selection from d3js CDN?

**Comment by laurikari** [comment]
Ah, change `100%` to a number and it will work.  Phew.

**Comment by AlfonsoML** [comment]
It would be really great to provide the code of each example in a way that it's easier to copy&paste everything and we can start playing.

For example I've tried to follow the steps outlined at https://www.eventbrite.com/engineering/introducing-britecharts/ but my chart was monochrome, I digged in the examples and I found a call to .colorSchema(colors.colorSchemas.britechartsColorSchema)
But when I copied that there's a JS error because colors is not defined.

So it's either trying to follow all the links and dig deep in the combined js file for the examples, or skip this project that otherwise looks so great

**Comment by Golodhros** [comment]
Hi @AlfonsoML,
Ouch! sorry to hear that! Yes, you would need to load the colors helper, you can see the whole demo code in https://github.com/eventbrite/britecharts/blob/master/demos/demo-bar.js

Totally, we are working on making the demos more accessible. Maybe using codePens or JSBin containers. We are working on having a whole bundle download (it's almost there) and that would allows us to use the CDN and set up test pages easily.

**Comment by Golodhros** [comment]
@AlfonsoML we just added some links from the demo pages into the code that renders them. It's not the best solution but we hope it helps people to find the original code!

**Comment by Golodhros** [comment]
Hi @mmartimo, @AlfonsoML  and @perborgen,

We have just released a patch that has solved this issue. From now on, you would be able to use a CDN to download Britecharts:

`
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/britecharts/dist/css/britecharts.min.css" type="text/css" />

<script src="https://cdn.jsdelivr.net/npm/britecharts@1/dist/bundled/britecharts.min.js" type="text/javascript" />
`

Also, you could find the split modules and the rest of the contents of the `dist` folder in this link: `https://cdn.jsdelivr.net/npm/britecharts/dist/`

Thanks for your patience!
