### ISSUE TITLE
Error with npm install on project

### ISSUE THREAD

**Issue by ludope** [eventbrite/britecharts#197]
After getting sources from `npm install britecharts d3-selection` command, and trying to install dependencies on `britecharts` I get the following error:

```
$ npm install
npm WARN deprecated babel-istanbul-loader@0.1.0: Package is deprecated, use https://github.com/deepsweet/istanbul-instrumenter-loader
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git://github.com/beevelop/grunt-release.git resetting remote C:\Users\Ludovic\AppData\Roaming\npm-cache\_git-remotes\git-github-com-beevelop-grunt-release-git-f3dd0c51 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  requirejs/text resetting remote C:\Users\Ludovic\AppData\Roaming\npm-cache\_git-remotes\git-github-com-requirejs-text-git-37804fea because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

I expect to have dependencies installed and to build the library into `dist/` folder using `npm run prod`command line.

## Environment

* Britecharts: latest using `npm install britecharts d3-selection`
* Node version: 6.9.1
* NPM version: 3.10.8
* Operating System and version (desktop or mobile): Windows 10

**Comment by Golodhros** [comment]
Hi @ludope, thanks for taking the time to file an issue!

I have tried to reproduce the issue in my machine (a Mac) with npm 6.9.1 and I couldn't see the same message. It worked fine for me. 

I also tried to search something about the error code: `addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url` but couldn't find anything clear about it.

It looks like a `git` configuration problem, but I am afraid I cannot give you more insights. I think that is not a Britecharts issue.

**Comment by ludope** [comment]
Hi @Golodhros, and thank you for your answer. As I was investigating I remember that somtimes I have to change git config using the following command `git config --global url.https://github.com/.insteadOf git://github.com/`, now it seems to work for the first part (`npm install`) as I got no error displayed. But the second part shows me an error while running `npm run prod` command line:

```
$ npm run prod

> britecharts@1.4.6 prod \Libraries\node_modules\britecharts
> npm run _prod && npm run _prodUMD


> britecharts@1.4.6 _prod \Libraries\node_modules\britecharts
> WEBPACK_ENV=prod webpack

(node:8320) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
'WEBPACK_ENV' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
npm ERR! britecharts@1.4.6 _prod: `WEBPACK_ENV=prod webpack`
npm ERR! `cmd "/c" "WEBPACK_ENV=prod webpack"` failed with 1
npm ERR!
npm ERR! Failed at the britecharts@1.4.6 _prod script.
npm ERR! This is most likely a problem with the britecharts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     WEBPACK_ENV=prod webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls britecharts
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "\\nodejs\\node.exe" "\\node_modules\\britecharts\\node_modules\\npm\\bin\\npm-cli.js" "run" "_prod"
npm ERR! cwd \Libraries\node_modules\britecharts
npm ERR! node -v v6.9.1
npm ERR! npm -v 1.1.71
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     \Libraries\node_modules\britecharts\npm-debug.log
npm ERR! not ok code 0

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "\\nodejs\\node.exe" "\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! britecharts@1.4.6 prod: `npm run _prod && npm run _prodUMD`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the britecharts@1.4.6 prod script 'npm run _prod && npm run _prodUMD'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the britecharts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run _prod && npm run _prodUMD
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs britecharts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls britecharts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \Libraries\node_modules\britecharts\npm-debug.log
```
I think I have to configure the WEBPACK_ENV variable. So I'm still investigating.

**Comment by Golodhros** [comment]
Hi @ludope, glad it got solved!

What are you trying to do? Because if you just want to use one of the charts, you should be good to go. You can require the charts from `/dist/umd/` and start rendering them.

However, if what you are trying is to contribute to the project or fork one of the charts, then you should clone the repo, and then inside the new folder run `npm install` and the rest of instructions on `https://github.com/eventbrite/britecharts/blob/master/CONTRIBUTING.md`.

**Comment by ludope** [comment]
Hi @Golodhros, thank you for your answer again.

It appears `/dist/umd/` directory is not up to date as `legend.min.js` still requires `d3` for example. That's why I was trying to get this directory compiled in order to get it up to date and to see if some of the errors I got (that I did not talked about yet as I don't know if it has already been fixed or not) are still there in an updated version of the library and so I can report them or suggest a fix.

So, I just want to build the project into `/dist/umd/` directory for testing the library in a non-ES2015 project.

**Comment by Golodhros** [comment]
Hi @ludope ,

Oh yeah, we have a delay between our bower/git releases and our NPM releases. Right now, NPM is a bit out of date compared to bower/git. This is because in our company we need help from OPS in order to release a new version. We will do it pretty soon, but I can't give you times...

In the meanwhile, if you need the legend working fine, I would either use bower, or directly use a git link in your package.json. That would give you the most updated version, with the Legend working fine.

Also you could clone the repo and run install and prod, so you will also have that legend with the latests changes.

**Comment by ludope** [comment]
Hi @Golodhros, I cloned the repo in a Debian machine and it compiles almost successfully.

I get some UglifyJs warnings on the `npm run prod` but the compilation is done. I can see that `d3` is not required anymore in `legend.min.js` as it should be. The issue should comes from my Windows environment.

Thank you for you time!
