### ISSUE TITLE
Export as a Polymer element/web component

### ISSUE THREAD

**Issue by AdamMurray** [eventbrite/britecharts#204]
Exactly what it says on the tin: create a Polymer wrapper for the library.

**Comment by miglesiasEB** [comment]
Thanks Adam Murray for the proposal!
Right now we are in a moment where we want to hear from the community about what to include in Britecharts and how it should evolve, so this is great feedback!!

**Comment by Golodhros** [comment]
Closing due to lack of support. Let's reopen if more people is interested.
