### ISSUE TITLE
Scrolling triggers viewport resize on iPhone

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#206]
It seems that scrolling is triggering viewport resizes on our demos, thus re-rendering charts.

Reported in https://news.ycombinator.com/item?id=14307608#14308850

**Comment by Golodhros** [comment]
Reproduced in iPhone 6 Plus

**Comment by nobitagit** [comment]
This happens on Android as well (Chrome on Samsung S7, though I guess pretty much anywhere) but it's technically not a bug.

What's happening here is that on certain mobile browsers the address toolbar scrolls out of view when scrolling the page downwards. This in practice resizes the viewport and fires a resize event that is correctly handled by the function in `resizeHelper.js`.

The simplest trick here is to fire the callback only when the width changes, as in general the change in width is all we care about when dealing with responsive charts. I submitted a PR with a fix for it so you can test if that solves the issue.
