### ISSUE TITLE
Minor: demos links go to wrong pages

### ISSUE THREAD

**Issue by sincarne** [eventbrite/britecharts#208]
The demo links beneath "Stacked Area Chart" do not take you to the right pages. Instead, they link you to the first list of demos again.

**Comment by Golodhros** [comment]
Hi @sincarne, thanks for the feedback!

Actually that's expected, as those demos are components that only make sense to show along with the charts. This way, we show the tooltip with the line chart, the mini tooltip with the bar chart and so on.

Thanks anyways!

**Comment by sincarne** [comment]
Ah, makes sense.
