### ISSUE TITLE
Range Selection support

### ISSUE THREAD

**Issue by niemyjski** [eventbrite/britecharts#211]
Is there a good way to do range selection? For example I have a time series line (area) chart and I want to be able to select a date range and call a callback to update the chart (I don't want zoom). I looked through the demos and did a search through the source but didn't see anything.

**Comment by Golodhros** [comment]
Hi Niemyjski, thanks for the question!

We usually do that either by using a double date picker, re-rendering the charts after the second date has been selected, or using a brush like the one on the linechart demo: http://eventbrite.github.io/britecharts/tutorial-line.html

From what I understand, you would like to do the brushing (drag and drop an area) on the chart itself, is that right?

**Comment by niemyjski** [comment]
Yes that is correct, currently we are using rickshaw and would like to replace it as it's dead... We built a range selection which draws an overlay and then fires a callback with the min/max x coords (which is a unix timestamp). It's much like the selection you pointed out, but instead of re rendering it, we fire a callback and get more detailed data server side (what you pointed out is more like a zoom).

https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/rickshaw/rickshaw-custom.js

**Comment by Golodhros** [comment]
I see, I think the Brush (http://eventbrite.github.io/britecharts/tutorial-brush.html) will work for you!

With it, when you drag and drop, it will trigger an event that will give you the start-date and the end-date of the selected range. What you do with it is up to you, you can do another HTTP request to fetch more data and refresh the chart with that new one, or you can just filter the current data and apply it to the chart.

Let me know if you have any problems with it!

**Comment by niemyjski** [comment]
Thanks!
