### ISSUE TITLE
Ticks do not match tooltip for stacked area chart

### ISSUE THREAD

**Issue by rwholey-eb** [eventbrite/britecharts#213]
Take a look at the [kitchen sink]([http://eventbrite.github.io/britecharts/tutorial-kitchen-sink.html). The stacked area chart dates and tooltip do not match

## Expected Behavior
I would expect the tooltip and the stacked area ticks to agree with each other

## Current Behavior
The tool tip and the ticks are not in agreement

## Possible Solution
I believe it has to do with the date processing, this is also an issue in EB core analytics suite so we can see it in both places

## Steps to Reproduce (for bugs)
1. [kitchen sink]([http://eventbrite.github.io/britecharts/tutorial-kitchen-sink.html)
2. play with stacked area
3. See tool tip does not match ticks

![image](https://cloud.githubusercontent.com/assets/18017479/25965416/c5330d12-363c-11e7-9a1d-f2a1ad34846d.png)

**Comment by ryanwholey** [comment]
i'm going to take a look at this one

**Comment by rwholey-eb** [comment]
As of right now, britecharts should receive localized data which it will display. If you have utc data, consider localizing it first.
