### ISSUE TITLE
Add Bullet Charts

### ISSUE THREAD

**Issue by hrstoyanov** [eventbrite/britecharts#215]
We could add Bullet Charts to Britecharts

See an example here:
https://bl.ocks.org/mbostock/4061961

![bullet_charts_-_bl_ocks_org](https://cloud.githubusercontent.com/assets/190833/25969996/f5136ce8-364b-11e7-99e4-3f9f7bc3bd1a.png)

**Comment by dalerasrorov-eb** [comment]
http://www.perceptualedge.com/articles/misc/Bullet_Graph_Design_Spec.pdf

**Comment by Golodhros** [comment]
Stephen Few is the boss! 
This is exactly what we needed for this ticket, thanks for sharing!!

**Comment by dalerasrorov-eb** [comment]
Thanks a lot for opening the issue. The Bullet chart draft is built:
http://eventbrite.github.io/britecharts/tutorial-bullet.html

**Comment by hrstoyanov** [comment]
Thanks, forgive my memory, but do you have sparklines already? This is another one I am looking for in a chart library.

**Comment by Golodhros** [comment]
Hi @hrstoyanov, we have an implementation of a Sparkline as an area chart.
We will be working on extending it to more types at some point.

**Comment by hrstoyanov** [comment]
Thanks. Condensed mini-chart seems to be the way to go especially on crammed up mobile screens. This book opened [my eyes](http://a.co/89vS03l). I have been looking for a replacement of [this](https://omnipotent.net/jquery.sparkline/#s-about) old library, so if you add the full specter of mini-charts, britecharts will become my favorite chart library!

**Comment by Golodhros** [comment]
Totally, I love that Book of Stephen Few! 
If you want to know more about the Sparklines, this [book of Tuftle](https://www.amazon.com/s/?ie=UTF8&keywords=edward+tufte+beautiful+evidence&tag=googhydr-20&index=aps&hvadid=241886314516&hvpos=1t1&hvnetw=g&hvrand=7307660238735524384&hvpone=&hvptwo=&hvqmt=b&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9031945&hvtargid=kwd-4565190434&ref=pd_sl_641ztf25jy_b) has a good amount of info.

I am not sure if we would go all the way to have every kind of sparkline, but at least we want to add a couple more and optimize them to show within paragraph text.

Thanks a lot for your input @hrstoyanov !

**Comment by dalerasrorov-eb** [comment]
@hrstoyanov great stuff and info, thanks a lot!
