### ISSUE TITLE
Add ability to toggle some data series on/off

### ISSUE THREAD

**Issue by AlfonsoML** [eventbrite/britecharts#220]
It would be a welcome addition the ability to provide a way for the user to toggle the visibility of the series in a graph (I'm thinking lineChart with multiple series, but it can apply to several other ones as well)

## Expected Behavior
When a graph has several series, it can be nice for the user the ability to hide some of them (in Chart.js that's done clicking on the legend) and remove that way the visual clutter and focus on other data.

## Current Behavior
All the series are always visible

## Possible Solution
For example an optional button with an eye, when clicked it shows a pane with the series and allows toggling them on/off

## Steps to Reproduce (for bugs)
Load https://eventbrite.github.io/britecharts/tutorial-line.html and try to remove the Oakland data from the chart

**Comment by Golodhros** [comment]
Thanks for the proposal @AlfonsoML !!

It makes a lot of sense. I like the idea of using the legend as the control panel for this feature. It could also be hooked to more generic events so that it could be triggered programatically with any other logic.

**Comment by Golodhros** [comment]
A basic implementation of this feature would need:
- [ ] Adding click events on the legend items to toggle/untoggle
- [ ] Adding a 'disable' or 'dim' command to the legend (right now it only allows to highlight one, this would be the opposite use case)
- [ ] Create an example where this works by filtering the data to the chart

**Comment by dalerasrorov-eb** [comment]
While trying to implement this, encountered a color inconsistency issue, created an issue for that:
https://github.com/eventbrite/britecharts/issues/431

**Comment by Golodhros** [comment]
We could say this is possible now, we will need to fix the color inconsistencies, and that's reflected in #431. Also a tutorial or how to guide would be great. 
Closing for now.
