### ISSUE TITLE
Black areas of line chart

### ISSUE THREAD

**Issue by Tobbe** [eventbrite/britecharts#225]
## Expected Behavior
Just show a line. No black areas

## Current Behavior
![image](https://cloud.githubusercontent.com/assets/30793/26061370/0f8c5f78-3988-11e7-8684-d7caa6f60b97.png)

## Possible Solution
Since it's probably me doing something wrong, better docs is probably the solution 😄 

## Steps to Reproduce (for bugs)
Create a line chart with the following data:

```
const chartData = {
    dataByTopic: [
        {
            topicName: 'San Francisco',
            topic: 123,
            dates: [
                {
                    date: '2017-01-16T16:00:00-08:00',
                    value: 1,
                }, {
                    date: '2017-01-16T17:00:00-08:00',
                    value: 2,
                }, {
                    date: '2017-01-16T18:00:00-08:00',
                    value: 3,
                }, {
                    date: '2017-01-16T19:00:00-08:00',
                    value: 4,
                }, {
                    date: '2017-01-16T20:00:00-08:00',
                    value: 5,
                }, {
                    date: '2017-01-16T21:00:00-08:00',
                    value: 4,
                }, {
                    date: '2017-01-16T22:00:00-08:00',
                    value: 1,
                }, {
                    date: '2017-01-16T23:00:00-08:00',
                    value: 7,
                },
            ],
        },
    ],
};
```

## Context
Trying to use BriteCharts with Vue.js

## Your Environment
* Version used: 1.5.2
* Browser Name and version: Chrome, latest
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project: N/A

**Comment by Golodhros** [comment]
Hi @Tobbe , thanks for taking the time to open an issue!

It seems you need the CSS styles! You could load the whole bunch `/dist/css/britecharts.min.css` or just the common parts `/dist/css/common/common.min.css` plus the one specific for your chart `/dist/css/charts/line.min.css`.

We will review the docs then, did you follow the Getting Started Guide or did you use a different approach? 

Thanks a lot!

**Comment by Tobbe** [comment]
Wow, thanks for the quick response! 

Yes, I did follow the guide, but obviously not well enough... I see now that it already mentions the CSS needed. My bad :(

What would be nice though are examples of data and margin as I had to look those up in other parts of the documentation :)

**Comment by Tobbe** [comment]
Looks much better now that I managed to load the css files :thumbsup: 
Thanks again for your help!

![image](https://cloud.githubusercontent.com/assets/30793/26072527/1df9cae0-39ac-11e7-815a-0f2cf6aeeeb6.png)

Had to `import` the css:

```
import 'britecharts/dist/css/common/common.css';
import 'britecharts/dist/css/charts/line.css';
```
