### ISSUE TITLE
Add Date Localization to timeAxis

### ISSUE THREAD

**Issue by AlfonsoML** [eventbrite/britecharts#227]
I'm trying to create a chart with a time scale like the line example, including the tooltip.  
The problem is that I need to show the data like month names in Spanish, not English and I can't find a way to do it.  
I've tried to look at D3 documentation, but I don't see the methods or namespace to do it

## Expected Behavior
Being able to use the D3 localization system or something alike.

## Current Behavior
Everything is shown in English

## Possible Solution
Provide or document the way to localize dates (and numbers) and use the BriteCharts in other languages.

**Comment by Golodhros** [comment]
Hi @AlfonsoML, thanks for the issue!

This is indeed a great idea! 
We are actually not doing it at the moment in our product, and we will love to do it. We will be putting this into our roadmap for sure, and hope we can tackle it soon.

Thanks again!

**Comment by rwholey-eb** [comment]
closed in #282
