### ISSUE TITLE
"Eventbrite Copyright" appears when trying to print page

### ISSUE THREAD

**Issue by kazzkiq** [eventbrite/britecharts#228]
## Expected Behavior
When trying to print the webpage (CTRL/CMD + P) the charts should behave the same as in webpage.

## Current Behavior
When trying to print, sometimes a text "Eventbrite Copyright" is shown above the chart. (See red arrows in image bellow)

<img width="984" alt="captura de tela 2017-05-15 as 18 55 51" src="https://cloud.githubusercontent.com/assets/1953194/26080841/af743f90-399e-11e7-9d77-5ae6b9232be1.png">

## Steps to Reproduce (for bugs)
1. Open [this example page](http://eventbrite.github.io/britecharts/tutorial-stacked-area.html)
2. Hit CTRL/CMD + P
3. See the "Eventbrite Copyright" displaying above the first chart.

## Your Environment
* Version used: macOS
* Browser Name and version: Chrome 57.0.2987.133 (64-bit)
* Operating System and version (desktop or mobile): Desktop

**Comment by Golodhros** [comment]
Thanks @kazzkiq  for the issue report!

It seems that our docs footer, that is positioned with `position: sticky` is having some problems when trying to print the page.

An easy solution could involve hiding the footer with a print-only stylesheet.
