### ISSUE TITLE
Create an accessor to singleLineGradientColors in Line Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#234]
We need an accessor to singleLineGradientColors

## Expected Behavior

singleLineGradientColors is configurable

## Current Behavior

It is not

## Possible Solution

Add accessor

**Comment by Tobbe** [comment]
This confused me a lot. I was expecting single line graphs to honor the .colorSchema setting, alas it doesn't. Was just about to write an issue about it when I found this one.

So one idea would be to run the gradient through the colors passed to .colorSchema. What do you think about that?

**Comment by Tobbe** [comment]
I'm working on a PR that implements my idea

**Comment by Golodhros** [comment]
Hi @Tobbe , thanks for the comment!

We already have a set of gradients, the only problem is that they are not configurable. Let us open this option and see if that solves your requirements.

**Comment by Tobbe** [comment]
This is the code I have now:

```
function buildGradient() {
    const data = colorSchema.map(function (color, index) {
        return {
            offset: `${index * 100 / (colorSchema.length - 1)}%`,
            color: color,
        };
    }); 

    console.log('data', data);

    svg.select('.metadata-group')
        .append('linearGradient')
        .attr('id', lineGradientId)
        .attr('x1', '0%')
        .attr('y1', '0%')
        .attr('x2', '100%')
        .attr('y2', '0%')
        .selectAll('stop')
        .data(data)
        .enter()
        .append('stop')
        .attr('offset', ({offset}) => offset)
        .attr('stop-color', ({color}) => color)
}
```

Seems to work 😄 

This way you don't need two different settings/variables for the colors. `singleLineGradientColors` isn't needed any more

**Comment by Tobbe** [comment]
I'll create a proper PR tomorrow

**Comment by Golodhros** [comment]
Hi @Tobbe, thanks for the suggestion!

I have added the accessor on https://github.com/eventbrite/britecharts/pull/241, so that you could use one of our already made gradient colors or specify your own gradient.

I talked with our designer @evb-sun , and she doesn't want us to use the regular color schemas for gradients, as they weren't supposed to be used for that and the contrast/colors won't be right.

Thanks a lot anyways!

**Comment by Tobbe** [comment]
With my patch, and no further configuration, this is what the demo line chart with a single data source looks like:

![image](https://cloud.githubusercontent.com/assets/30793/26140652/46c56510-3ad8-11e7-9220-c25c9a93e249.png)

But of course you can configure it to use your predefined gradient colors as well:

```
.colorSchema(colorHelper.colorGradients.greenBlueGradient)
```

With that the graph looks like this:

![image](https://cloud.githubusercontent.com/assets/30793/26144905/e3368bb0-3aea-11e7-9d0c-b1c5d5006c14.png)
