### ISSUE TITLE
Remove Underscore dependency from Area Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#235]
Underscore is not really necessary and it's weighting on that file and the whole bundle

## Expected Behavior

No underscore in the bundle

## Current Behavior

<img width="360" alt="webpack_bundle_analyzer" src="https://cloud.githubusercontent.com/assets/190833/26095370/28ede744-39d2-11e7-89ec-5a9106bd17ea.png">

## Possible Solution

Refactor our underscore

**Comment by nobitagit** [comment]
You might want to check [Lodash Modularized](https://www.npmjs.com/browse/keyword/lodash-modularized).

It has practically the same API as Underscore and you could import single functions in the bundle like for example [`sortBy`](https://www.npmjs.com/package/lodash.sortby) by installing/importing only want you need like:

var sortBy = require('lodash.sortby');

I can pick this ticket if you're up for it.

**Comment by Golodhros** [comment]
Hi @nobitagit , thanks for the suggestion!

Actually, I have a branch where I am trying to get rid of underscore completely, but I am finding some difficulties. 
If you could move it into Lodash, that would be awesome! Later I could take care of removing the dependency.

**Comment by nobitagit** [comment]
Sure, let me get a PR going for this 👍 I will post here in case I need some help or I have doubts
