### ISSUE TITLE
Month title in X-Axis is cut off at the bottom

### ISSUE THREAD

**Issue by AlfonsoML** [eventbrite/britecharts#237]
Using a line chart, with time axis, the Month isn't correctly displayed and part of the bottom is cut off. 

## Expected Behavior
Show full Month name like in your demo

## Current Behavior
Several pixels aren't shown

## Steps to Reproduce (for bugs)
Load [demo page](https://www.martinezdelizarrondo.com/bugs/britecharts-line-AxisTitle.html) and look at the X-Axis title, 
![imagen](https://cloud.githubusercontent.com/assets/2482331/26115114/6de61d8e-3a5f-11e7-9f6d-7f3ce924eec6.png)

## Your Environment
* Version used: current one at https://cdn.jsdelivr.net/npm/britecharts@1/dist/bundled/britecharts.min.js
* Browser Name and version: Chrome, Edge & Firefox
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://www.martinezdelizarrondo.com/bugs/britecharts-line-AxisTitle.html

**Comment by Golodhros** [comment]
Hi @AlfonsoML , thanks for the issue!

I think that will be easily solved by increasing the amount of bottom margin, give it a bit more and you should see the whole month there.

Thanks!

**Comment by AlfonsoML** [comment]
Hi @Golodhros 

I tried to change it with Dev tools, but I don't find any style on the wrapper or the container to make it fit correctly. If I change the height attribute on the SVG after it has been rendered it works fine, but that's really an ugly workaround.

There's something in your demos that makes it work correctly, but I don't know what it is and as they have so much stuff it's hard to try to guess there.

**Comment by Golodhros** [comment]
Hi @AlfonsoML , sorry, I wasn't especific enough.

By default, the lineChart has a margin of:

           {
                top: 60,
                right: 30,
                bottom: 40,
                left: 70
            }

If you try:
            lineChart
            .margin({
                top: 60,
                right: 30,
                bottom: 60,
                left: 70
            })

it will probably work.

Thanks!

**Comment by AlfonsoML** [comment]
Thank you.
Yes, that works, but it's still a mystery why [your demo](https://github.com/eventbrite/britecharts/blob/master/demos/demo-line.js) doesn't require that change (that's it: other people might face this same problem)

**Comment by Golodhros** [comment]
Great!
That's right, I am not sure why it isn't happening on our demos too. Maybe it's because the font size? Maybe it would be wise to increase the default bottom margin of the line chart.

We'll wait and see...
