### ISSUE TITLE
DonutChartData.percentage shouldn't be required

### ISSUE THREAD

**Issue by AlfonsoML** [eventbrite/britecharts#242]
In the fields of DonutChartData, https://eventbrite.github.io/britecharts/global.html#DonutChartData__anchor there's a percentage that it's marked as required.
Given that the percentage can easily be computed from the sum of all the quantities when the chart is initialized, this field should be computed automatically.

## Expected Behavior
Don't mark it as required. Even don't expose it at all.

## Current Behavior
The percentage is marked as required.

**Comment by Golodhros** [comment]
Hi @AlfonsoML , thanks for the issue!

It makes a lot of sense, we could easily calculate those inside the donut chart!

Thanks a lot!

**Comment by jenjwong** [comment]
@Golodhros, I’m happy to help out with this!

Proposed actions:
1. Leave the percentage API in place, but if the value is not declared, programmatically generate percentages from the quantity input field.
2. Update docs and add tests.

From a product perspective what should be the default number of decimal places for the percentage labels? 

Let me know if you have any other thoughts or preferences!

**Comment by Golodhros** [comment]
Hi @jenjwong , that would be awesome, thanks a lot!!

Your proposal sounds perfect! Let's remove the 'required' part from the docs too.

I would say let's make it use one decimal by default, and if the user needs to show two, let's make them use the percentages entries on the data. This way, we would have a 'default' behavior for people that don't want to complicate themselves and a more specific one for users with more specific requirements.

Thanks again!

**Comment by ryanwholey** [comment]
ah! yes i think this is a great idea!! Definitely shouldnt need percentages

**Comment by jenjwong** [comment]
Great library! I noticed some PRs including bundle.js files and was curious about preferences for including auto-generated files and scripts to run to create a production build of the docs.

**Comment by Golodhros** [comment]
Hi @jenjwong,

As our docs depend a lot of our code, we usually have to run `npm run docs` before we push a PR. This would create the bundle of the demos and the new documentation pages.

On the other side, we don't run `npm run prod` on every PR, we only do that on every release, and that is automatic there.

Thanks a lot!!

**Comment by Golodhros** [comment]
Fixed by @jenjwong  on https://github.com/eventbrite/britecharts/pull/267

**Comment by jolesbi** [comment]
Hey All! Is there any way to **NOT** show percentage at all - and instead just show the quantity? Thanks in advance!
