### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by AlfonsoML** [eventbrite/britecharts#243]
At the moment the way to make the charts responsive is to redraw them. That happens also when there's some change.  
The problem is that each time the whole chart gets a "loading" animation that draws it and it might be useless after the initial creation.

## Expected Behavior
Have a way to redraw the chart without extra distractions, show the chart ASAP.

## Current Behavior
Each time that the chart is created it always use a "loading" animation starting from 0 to max

**Comment by Golodhros** [comment]
HI @AlfonsoML , thanks for the issue!

That's a totally legit request, not the first time I think about it!
It should be pretty straightforward to add an accessor to stop the animation, so that when we redraw the chart, we set to not animate and get the desired outcome.

Thanks a lot!

**Comment by Golodhros** [comment]
Fixed on #257
