### ISSUE TITLE
Incorrect width applied to horizontal bar charts

### ISSUE THREAD

**Issue by Caged** [eventbrite/britecharts#244]
The width of horizontal bar charts appears to be set to `width + margin.left + margin.right` which causes the SVG to break out of its parent container.   

## Expected Behavior
I would expect the resulting SVG to have the exact width set via `.width(n)`.

## Current Behavior

The width of horizontal bar charts appears to be set to `width + margin.left + margin.right` which causes the SVG to break out of its parent container.  If you attempt to subtract the margins from the width before applying it to the chart, the chart elements are squished.  

It'd be great if this matched up with the established  [margin conventions](https://bl.ocks.org/mbostock/3019563) in d3. 

## Steps to Reproduce (for bugs)
Here's an example - https://jsfiddle.net/ru0kqn95/1/
In this example, the green border of the parent container and the red border of the SVG should match and the chart within should fill the space appropriately.  If you remove the left and right margins, the containers will align.

## Context
I've had to result to workarounds to get width working.

## Your Environment
* Version used: GIT HEAD (e7a95a132f0a6e57f51f92de477c6b8a6371222c)
* Browser Name and version: Chrome Version 58.0.3029.110 (64-bit)
* Operating System and version (desktop or mobile): macOS 10.12.4

Thanks for providing this lib!  I was hoping someone would come along with a library that followed the [reusable pattern](https://bost.ocks.org/mike/chart/).

**Comment by Golodhros** [comment]
Hi @Caged , thanks for opening the issue!

You are right! We happen to have some inconsistencies in the way we handle the svg creation and use the D3 margin convention.

We definitely need to fix this! We already have a ticket for a helper that should take care of that process within the chart:  #121. The idea would be to use a helper to create the svg elements and add the margin and g groups.

Thanks and sorry for the inconvenience!

**Comment by Golodhros** [comment]
Fixed on #256
