### ISSUE TITLE
Cannot find customMouseHover event for tooltip

### ISSUE THREAD

**Issue by dnprock** [eventbrite/britecharts#247]
I'm using the distribution js version and it doesn't have customMouseHover tooltip event.

https://raw.githubusercontent.com/eventbrite/britecharts/master/dist/bundled/britecharts.min.js

## Expected Behavior
In this bar example, it shows customMouseHover event. However, javascript distribution file doesn't include such event:

https://eventbrite.github.io/britecharts/tutorial-bar.html

## Current Behavior
When I use customMouseHover event, I get:

Error: unknown type: customMouseHover

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.5.2
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dnprock** [comment]
I just checked the JS code. Looks like the event is now called customMouseOver instead of customMouseHover. Please update the documentation.

**Comment by Golodhros** [comment]
Ooops! Sorry @dnprock !

Here is the fix https://github.com/eventbrite/britecharts/pull/248
