### ISSUE TITLE
Line chart: trace missing values with dashed path

### ISSUE THREAD

**Issue by evb-sun** [eventbrite/britecharts#258]
Related to https://github.com/eventbrite/britecharts/issues/226

Line charts are generally used to illustrate a trend over time, the chart should be able to tolerate missing values in time series.

## Expected Behavior
By default, the line chart should interpolate missing values, the line that represents missing values should visually differentiate from the rest of the chart:

<img width="722" alt="screen shot 2017-05-22 at 16 58 59" src="https://cloud.githubusercontent.com/assets/13459095/26333100/fde09d9c-3f0f-11e7-9b24-075e5acb3ee5.png">

Alternatively, instead of defaulting missing value to "0", we should simply display incomplete data:

<img width="789" alt="screen shot 2017-05-22 at 17 00 18" src="https://cloud.githubusercontent.com/assets/13459095/26333119/2cac8bf4-3f10-11e7-8a18-6f9e851efc0e.png">

**Please refer to Invision for design specs**
https://eventbrite.invisionapp.com/d/main/#/console/9951901/212621488/preview

## Current Behavior
Missing value is set to 0, resulting a "nose dive" look on the chart.

**Comment by crozet-magenta** [comment]
also looking for this feature

**Comment by Golodhros** [comment]
#741 Adds the support for empty spaces on the line chart.

Dashed lines would be ideal, but for the time being, we won't go that way.

Feel free to reopen this issue if that is necessary.
