### ISSUE TITLE
Add human formatted values to Line Chart and Area Chart to be consumed by Tooltips

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#268]
Right now, if the value we are showing is a money value, we don't have a mechanism to add and format the currency properly.

## Expected Behavior
We should be able to see the currency if the values are money values

## Current Behavior
We are showing only regular values

## Possible Solution
We could handle this situation in different ways.
One of it would be to actually support different locales and have logic inside our charts that gives the proper format to money values depending on the locale we pass in or a currency sign.
Another way would be to add a 'human formatted value' to our data inputs, so that if that value is there, that would be the value showed on the tooltip.

I would prefer the last option, as it implies less logic in our charts and less complications. Our users would be responsible on passing the data with the format they desire to be shown in the tooltips.

## Context
We have seen that need in our product at Eventbrite.

**Comment by jbonigomes** [comment]
Can this be done on the yAxis of a bar chart?

**Comment by Golodhros** [comment]
Not at this moment @jbonigomes

**Comment by jbonigomes** [comment]
Is it something in the pipeline? Is there an official workaround?

**Comment by jbonigomes** [comment]
Thanks @Golodhros I will do that

**Comment by Golodhros** [comment]
Fixed in #309
