### ISSUE TITLE
Create a chart type "template" or call it "Basic chart type".

### ISSUE THREAD

**Issue by bung87** [eventbrite/britecharts#269]
## Expected Behavior

Create a basic chart type to illustrate common chart component part creation progress.  

Declare common variable which suitable for most of chart type,make common component variable definition have same name,and the data key value mappings could have same key name,like xAxisLabel,or just call it xLabel somelike.

Some variable could have same default value.

Implements common methods make other chart type could be use .

Code it and document it ,so anyone want to contribute a new chart type to britecharts would have acknowledgments to implement the chart type.

## Current Behavior

have not create yet.

variable used to same purpose have different name.different default value.

**Comment by Golodhros** [comment]
Related to https://github.com/eventbrite/britecharts/issues/264

**Comment by bung87** [comment]
I've just write some piece of typescript code to illustrate the parts of chart creation.may this help?
```
// / <reference types = 'd3-selection' />

import {Selection} from 'd3-selection';

declare function define(...args: any[]): any;

interface ChartCreation{
       (this:void):ChartInterface;
}

interface ChartInterface {
    (_selection:Selection<any,any,any,any>):void;
    exportChart (filename) :void;
    width () :this|number;
    height():this|number;
    margin():this|number;
    on():this;
    colorSchema();
}

define(function(require){
    const {exportChart} = require('./helpers/exportChart');
    let svg;
    let exports:ChartInterface;
    let chartCreation:ChartCreation;
    chartCreation = function():ChartInterface{
        return exports;
    }
    exports =  <ChartInterface> function(_selection:Selection<any,any,any,any>){
          _selection.each(function(_data){
               
            });
    }
    exports.exportChart = function(filename):void{
         exportChart.call(exports, svg, filename);
    }
    

    return chartCreation
   
});
```

**Comment by Golodhros** [comment]
Hi @bung87!
Thanks a lot, however I think typescript is not super evident for everybody (it doesn't feel like that to me). I am working already in a small markdown file with some guidelines as you commented on the issue. 

Also, I was thinking on grabbing one of the simplest charts and comment a lot inside, so that we can have a demo chart that is also a real chart.

Thanks anyways!

**Comment by bung87** [comment]
@Golodhros Good to know,we can move forward first,when this done back to exist code make them unified.still have lot work to do.

**Comment by Golodhros** [comment]
We would point to one of our charts from the code styleguide document.
