### ISSUE TITLE
Move Getting started, cdn page out of demos, make get started as first nav link

### ISSUE THREAD

**Issue by bung87** [eventbrite/britecharts#270]
<img width="836" alt="screen shot 2017-05-25 at 5 28 12 am" src="https://cloud.githubusercontent.com/assets/2238294/26426448/30564c0c-410b-11e7-83e4-de78d338e78f.png">

I've create a branch to make this possible, I'm considering which place to place the cdn page link.any thoughts about this?

## Expected Behavior
We should show links for Github, Twitter, the Getting Started section and the CDN demo

**Comment by Golodhros** [comment]
Hi @bung87 , thanks for the issue!

It seems a good idea, however we will have a problem with the 'search input', as it won't fit for some of the viewport sizes. I experienced this when trying to add another link there for the Twitter account.

@evb-sun  what do you think? It seems we have 3 links we need to add:
- Twitter
- Getting Started
- CDN demo

And probably we want to move the search from there too.

**Comment by bung87** [comment]
branch:https://github.com/bung87/britecharts/commits/demo-scripts-seperate
changes:
1. Seperating demos script to certain page not use combined one.
2. Correcting docs homepage `<title>` from "Index" to jsdoc config's "navOptions.systemName".
3. make cdn page as jsdoc static file named "cdn-iframe.html" and generate cdn.html which contains a iframe reference to "cdn-iframe.html" .
4. combined jsdoc generated api pages to API,flatten the API navigation.
5. include to all chart type demo script to kitchen-sink page.

you can check
docs online:https://bung87.github.io/britecharts/

**Comment by bung87** [comment]
close with pr https://github.com/eventbrite/britecharts/pull/274
