### ISSUE TITLE
A britecharts.js tutorial - want to add a link from the docs?

### ISSUE THREAD

**Issue by perborgen** [eventbrite/britecharts#287]
Hey!

I've created an interactive tutorial on how to use britecharts with Scrimba (a tool I'm building for creating tutorials):

https://scrimba.com/casts/cZWm2tb

I think it can be really valuable for beginners who are interested in britecharts, as the documentation doesn't have any tutorials yet, so I wanted to hear if you'd be interested in linking to this tutorial from e.g. the **See also** section in the README.md?

Cheers
Per

**Comment by martinmanzo** [comment]
Awesome tool!

**Comment by Golodhros** [comment]
Already added. Closing this issue.
