### ISSUE TITLE
Stacked-bar from dist/bundled/britecharts and from dist/umd doesn't work the same 

### ISSUE THREAD

**Issue by sound-matt** [eventbrite/britecharts#288]
Hello,

The stacked-bar chart from dist/bundled/britecharts.min.js and the stacked-bar from dist/umd/stacked-bar.min.js doesn't work the same

## Expected Behavior
In all case, the stacked-bar constructor should be stackedBar(), for now it's `stacked-bar()` in umd file
`chartContainer.datum(dataset).call(barChart); ` shouldn't trigger an error

## Steps to Reproduce (for bugs)
_Exemple with bundled file_
https://codepen.io/sound-matt/pen/weJdMJ

_Exemple with UMD files_
https://codepen.io/sound-matt/pen/gRPmXK

**Comment by Golodhros** [comment]
Hi @sound-matt, thanks for the bug report!

It makes sense, as our build is using the filenames as the namespace for the charts. It should definitely work as you suggest.
