### ISSUE TITLE
Refreshing Graph Data

### ISSUE THREAD

**Issue by rpheath** [eventbrite/britecharts#291]
I render a brush chart initially via a callback from an XHR request, which works perfectly. However, in that callback, I set a timer to "refresh" the chart in N seconds, to keep the chart/data fresh. The first render goes smoothly, but subsequent renders (via the timer) seems to 'stack' the data instead of reset/refresh it.

## Expected Behavior
I would not have expected the data to stack up, but instead when I call `container.datum(data).call(@chart)` the data for the chart would have been reset to whatever the `data` collection contained.

## Current Behavior
The data stacked up so I was showing multiple data sets in the same graph 🤔.

## Possible Solution
Make it so the data handed to `@container.datum(data)` is the exclusive data set for the graph.

## Steps to Reproduce (for bugs)
Example pseudo code:

```coffeescript
loadGraph: ->
  $.get '/my/path.json', { ... }, @graphHandler

graphHandler: (data) =>
  container = d3selection.select('#my-container')
  container.datum(data).call(@chart) # <-- is this not the proper way to set/refresh data?

  _.delay =>
    @loadGraph()
  , 5000
```

## Context
I need to be able to easily refresh a chart with new data.

## Environment
* Version used: 1.5.3
* Browser Name and version: Safari (latest), Chrome (latest)
* Operating System (desktop): macOS Sierra

**Comment by rpheath** [comment]
Ahhh, as it always goes, I've realized my problem after posting this issue!

I'm going to dump the explanation here in case someone else stumbles into this:

I misunderstood the API in that the you have to instantiate a new chart on **EVERY** data refresh. That seemed unintuitive to me, since the chart itself seems to represent the properties of the chart and defines the callbacks (if they exist) on interactions, but the data (I thought) was independent of the chart itself. That was my mistake.

I was instantiating the chart ONE time in the constructor of my class, and then trying to `@container.datum(data).call(@chart)` where `@chart` was that same chart that was already instantiated. This is what was causing the data to stack up.

After realizing that I had to set the data on a `new BrushChart()` each time, it seems to work as I need it to. It may be worth mentioning that in the docs (or being explicit about that in the code examples), as data-refreshing is a common need in charting/graphing.

Closing this issue and apologies if this wasted anyone's time.

**Comment by rpheath** [comment]
Actually, I'm going to re-open this issue with the hopes that someone can at least confirm that refreshing chart data, by design, requires re-instantiating a new chart every time, as it still feels like the chart properties/instantiation are independent of the data it's showing.

Thanks!

**Comment by Golodhros** [comment]
Hi @rpheath, thanks for the bug report!

Yes, this should work fine without having to instantiate a new chart.

**Comment by Golodhros** [comment]
This is happening on different charts:
- Brush chart: Happening, but we are almost certain that we don't want to allow reloads there, as it could interact badly with the brush selection. For now we will encourage to remove the chart and render it again.
- Donut chart: Working on fixing the error at this moment.

There could be more charts where this is happening, we will keep on checking on the rest of charts after we fix the Donut.

Thanks for your patience!

**Comment by Golodhros** [comment]
The fix for the Donut chart is on the latest release.

We will keep on checking the rest of charts and see if it happens.

**Comment by Golodhros** [comment]
I think we have solved this issue, please reopen if any issue is detected.
