### ISSUE TITLE
LineChart filled with black color

### ISSUE THREAD

**Issue by wiadev** [eventbrite/britecharts#292]
Hi

I'm created a linechart followed by example and it works but it was filled with darkcolor.
I've attached the screenshot, as well.

![screenshot](https://user-images.githubusercontent.com/18234060/27470884-dc3270d2-5830-11e7-92bb-5110c1dd6a8e.png)

`lineChart
          .tooltipThreshold(600)
            .height(300)
            .margin(lineMargin)
            .grid('vertical')
            .width(containerWidth)
            .dateLabel('fullDate')
            .on('customMouseOver', function() {
                chartTooltip.show();
            })
            .on('customMouseMove', function(dataPoint, topicColorMap, dataPointXPosition) {
                chartTooltip.update(dataPoint, topicColorMap, dataPointXPosition);
            })
            .on('customMouseOut', function() {
                chartTooltip.hide();
            });`

I've just followed the example exactly , nothing more or less.
Is there anything I'm missing?

Thanks.

**Comment by Golodhros** [comment]
Hi @wiadev , thanks for the issue!

It looks like you are missing the CSS styles for that chart. Loading `https://cdn.jsdelivr.net/britecharts/latest/britecharts.min.css` should work.

**Comment by wiadev** [comment]
Thanks. it works perfectly.
Also, I can't find any documentation for JSON format.

Do I always need to use 'dataByTopic' as a field? What is 'dataByDate' for? @Golodhros

**Comment by Golodhros** [comment]
Hi @wiadev,

the data inputs are specified on http://eventbrite.github.io/britecharts/global.html

Yes, 'dataByTopic' is required. You shouldn't need to provide a 'dataByDate' object though, it was something we use to do, but now the chart will calculate that object by himself using 'dataByTopic'.

**Comment by wiadev** [comment]
I've tried your solution but got the following error.
Error: <path> attribute d: Expected number, "MNaN,189LNaN,32LN…"

```
dates: [
{date:"2017-04-30", value:261}
]
```

Thanks. @Golodhros

**Comment by wiadev** [comment]
FYI, after going through linechart process, the dates has been updated with the following json.

```
{date: Invalid Date,
value:261}
```

**Comment by wiadev** [comment]
@Golodhros I've added another field fullDate and it solved the above issues. 
is it correct way?

Also, check out the following screenshot, please. 
![screenshot](https://user-images.githubusercontent.com/18234060/27596001-3ce15f7c-5b99-11e7-9531-76b0a08671b4.png)

Right now, in x-axis, it shows all days but I wanna set 5 days interval, like 1, 5, 10, for example.

Is it possible?

Thanks.

**Comment by Golodhros** [comment]
Hi @wiadev, thanks for the question and for using Britecharts!

So, it seems that from the code you copied from the demos, you are setting the 'dateLabel' as 'fullDate', so that's why your chart was expecting data with a date label of 'fullDate'.

Regarding the 'ticks' on the x axis, D3 doesn't allow us to pick a specific interval, so we have exposed 'forcedXTicks'. You will pass to it the number of ticks you want on the chart, and you will see something more or less like that (again, D3 doesn't allow us to specify it strictly).

Cheers

**Comment by Golodhros** [comment]
@wiadev, did this fix your issue?

**Comment by wiadev** [comment]
@Golodhros Yes, it worked. Thanks.
