### ISSUE TITLE
Wrong number precision in horizontal chart legend

### ISSUE THREAD

**Issue by cpuy** [eventbrite/britecharts#295]
Hey there,
In horizontal chart legend, the quantity number precision is changed (i.e. integer numbers are displayed as float). I would expect that quantity is displayed as it is specified in `datum` object

## Expected Behavior
Quantity displayed in chart legend should be displayed as it is specified in the datum object. As an alternative we should be able to override the default number formatter in legend object (which is currently hardcoded `d3Format.format('s')`)

## Current Behavior
Quantity in the datum object are displayed with a different precision than specified (e.g. `4` is displayed `4.00000`)

## Steps to Reproduce (for bugs)
```
import Legend from 'britecharts/src/charts/legend'
import {select} from 'd3-selection';

...

var data = [
            {
                name: 'On time',
                quantity: '4'
            },
            {
                name: 'Late',
                quantity: '3',
            }
        ];

select('.my-chart-legend').datum(data).call(new Legend());
```

![capture d ecran 2017-06-28 a 17 59 22](https://user-images.githubusercontent.com/1671164/27647858-f65b636a-5c2c-11e7-97d2-184aa57154e4.png)

## Context
We would like to use brightchart to display a donut with late and on time tasks but we don't want the legend to display `4.000000 on track tasks`.  Sadly this is blocking for us to use brightchart in our app

**Comment by Golodhros** [comment]
Hi @cpuy, thanks for opening an issue!

You are right on the analysis and we should definitely have an accessor for the number format. We will try to tackle it soon!

**Comment by martinmanzo** [comment]
Hi! I could tackle this. Just let me know if you want to.

**Comment by Golodhros** [comment]
@martinmanzo that would be awesome!! Thanks a lot!

**Comment by martinmanzo** [comment]
You are welcome!

Regarding this issue, which do you think is the best approach:
1. The accessor gets a string as parameter and internally converts it to d3 format object as d3Format.format(_param_).
2. The accessor gets the d3 format object directly.

I think the first is the way to go.

**Comment by Golodhros** [comment]
Totally, let's go with the first option. 
The second is fine, but it would require the user to also require the D3 format submodule.

Thanks a lot!!

**Comment by martinmanzo** [comment]
Just submitted a PR!
