### ISSUE TITLE
Issue working with Framer.js

### ISSUE THREAD

**Issue by davo** [eventbrite/britecharts#298]
I'm experiencing an unexpected behavior while trying to implement the [donut demo](http://eventbrite.github.io/britecharts/tutorial-donut.html) on [Framer](https://framer.com/).

In order to bind a Framer Layer to an external JS library I need to create a div element with an id within a framer layer.

```coffeescript
viz = new Layer
	width: Screen.width
	height: Screen.height
	html: "<div id='dataviz'></div>"
	ignoreEvents: false
```

After that I can use britechart to generate a donut chart.

```coffeescript
createDonutChart = ->
	donutChart = britecharts.donut()
	# Get legend object   
	legendChart = getLegendChart(data)
		
	donutChart.width(Screen.width).height(Screen.height / 2)
		.externalRadius((Screen.width/2)/1.5)
		.internalRadius((Screen.width)/5)

	d3.select('#dataviz').datum(data).call donutChart
```

Run the createDonutChart function

```coffeescript
createDonutChart()
```

The chart is created as expect but it's not getting access to the legend element, so it's not possible to use the custom mouse over event that's been showed in the demo.

```coffeescript
donutChart.on('customMouseOver', (data) ->
	legendChart.highlight data.data.id
)
```

## Demo

[Demo](https://framer.cloud/ljLVd)
[Source Code Demo](https://framer.cloud/ljLVd/14/app.coffee)

## Context

* Version used: 1.7.2
* Browser Name and version: Custom WebKit (Framer)
* Operating System and version: MacOS, Desktop
* Link to your project: https://framer.cloud/ljLVd

**Comment by Golodhros** [comment]
Hi @davo, thanks for the issue!

In the source code link you attached, the getLegend function doesn't seem to be returning anything. Check if by returning the legend your issue gets solved.

**Comment by davo** [comment]
Indeed, I forgot to return the legend object. Thanks!

[Fixe Demo]https://framer.cloud/ljLVd)

**Comment by Golodhros** [comment]
Great! It looks good!

Thanks for using Britecharts!!
