### ISSUE TITLE
Create Heatmap

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts#299]
We love the heatmaps on github and Google Analytics, let's build our own!

## Expected Behavior
![analytics](https://user-images.githubusercontent.com/9063187/27715115-de42bb94-5ce9-11e7-994d-ea399554bcdf.png)

## Context
A heat map is a way to visualize data in tabular format, where in place of (or in addition to) the numbers, you leverage colored cells that convey the relative magnitude of the numbers.

We use color saturation to reduce the mental processing or reading the data, providing visual cues. It makes easy to get the min and max numbers easily.

It could show activity by hour and day or by day and month.

**Comment by miglesiasEB** [comment]
Github's
![miglesiaseb__marcos_iglesias_](https://user-images.githubusercontent.com/9063187/27715081-a6d7aba6-5ce9-11e7-88a4-8011897777c9.png)

**Comment by rwholey-eb** [comment]
@evb-sun !!!!!!!!!! 💃

**Comment by evb-sun** [comment]
**Basic heatmap, more to come**
**[Invision](https://eventbrite.invisionapp.com/static-signed/live-embed/51160798/242147421/2/latest/0zfA613bclEAUbewnzmtnT38JwABiRBAf3A8I6sPBNlEw4izNMzBGHlEPyqNZaj3hYe1lEADHdlE5gJ4uuend7QbggQlE/Heatmap-Specs-2x.png)**

![heatmap specs 2x](https://user-images.githubusercontent.com/13459095/27845926-29c4035a-60e8-11e7-92d5-8a0d13a45b99.png)

**Comment by evb-sun** [comment]
@miglesiasEB @rwholey-eb ^

**Comment by miglesiasEB** [comment]
Great work @evb-sun! Let's do it!

**Comment by gabitoju** [comment]
Hi!
Is there and estimate date for the release of this feature?

**Comment by Golodhros** [comment]
Hi @gabitoju, thanks for asking!

This is actually at 30% more or less. I have a branch with an mvp, so it is highly likely that we are going to release this as soon as we get rid of the current bugs.

**Comment by gabitoju** [comment]
If there's  anything even in pre-alpha that we could test that would be great!

**Comment by Cospel** [comment]
Anyone has update on this? It looks to me as a very cool feature.

**Comment by Golodhros** [comment]
This is going to be the next chart, hope I can get to it in this month.

**Comment by dalerasrorov-eb** [comment]
Heatmap is implemented and available in `2.9.3` release.
