### ISSUE TITLE
Britecharts API Guidelines

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#311]
## Abstract
It’s easy to create new features and charts for Britecharts. However, naming the API methods is hard. How can we help our contributors choose the right API for their PR and make it easy to choose it?

The proposed API guidelines will help developers figure out the name of their getters-setters so that is consistent with the rest of the library.

## Background
At the moment, we have been more or less consistent with our API. However, we have been experiencing some discrepancies here and there, and some contributors pointed out to problems related to this.

Attached an image of the current API for all charts:
![BritechartsAPIJul17](http://static.gitscout.com/fb3b780c0d5facaaf1334484dc08871d2d2f552924445b42dc30a89accdb0117.png)

## Proposal
We want to introduce the following guidelines (still draft):

### General Considerations
In general, the api names would be on camelCase, and will try to use only one word that will be the same as the internal variable we implement.
For example: _height, width, margin, title_.

### Event dispatchers
They are attached to the chart will always be ‘on’.
As in: _.on('customHover')_

### Booleans
We want them to be prefixed with one of the following:
* should
* has
* is

as in: _isAnimated, hasFixedHighlightedSlice_ 

### Data labels
For API entries that configure the keys of the input data, we will suffix them with ‘label’.
As in: _dateLabel, valueLabel

### Commands
They must be a single verb, one word when possible.
As in: _hide, show, exportChart_

### Formats
A simple name with the property name and ‘format’ suffix.
As in: _numberFormat, xLabelFormat_

### Ticks
Use 'axis' and ‘ticks’ suffix
As in: _xTicks, yTicks_

## Impact
Pros:
*It will make the library API more consistent.
*This new format will make it easier to choose the name of the getters and setters of the components.
*It would reduce the entry barrier to contribute to Britecharts.
*Will make it easy to solve naming discrepancies when reviewing code.

Cons:
*We will introduce breaking changes
*We will need to do some refactors (list of refactors at the bottom)

## Alternatives
Doing Nothing
We keep on extending the API without thinking about it. It won't break anything.

Change to a different API
We could talk about it!

Do this and keep the old methods
We would have more dead code, a bit more weight and more code to maintain.
We could have a 'support window' of one release and mark this methods as deprecated.

----
## Refactors
In order to update the current API to match this proposal, we would need to change the following getters/setters:

* Boolean
    * Bar - usePercentage, horizontal, reverseColorList -> shouldReverseColorList
    * Grouped Bar - horizontal
    * Legend - horizontal
* Removing Force
    * Brush - forceAxisFormat, forcedXFormat, forcedXTicks
    * Line - forceAxisFormat, forcedXFormat, forcedXTicks
    * Stacked Area - forceAxisFormat,forcedXFormat, forcedXTicks
    * Tooltip - forceDateRange, forceOrder
* Dispatchers
    * Brush - onBrush
* Ticks
    * Grouped Bar - numOfHorizontal/VerticalTicks
    * Line - verticalTicks
    * Stacked Area - verticalTicks
    * Stacked Bar - numOfHorizontal/VerticalTicks
    * Step: numOfVerticalTicks

**Comment by martinmanzo** [comment]
Hi @Golodhros, I like the changes.

They will make the API clearer and create a line that would improve the quality of both Britecharts and the pull requests.

I think that the method reverseColorList in the bar chart should be added to the refactor list and changed to shouldReverseColorList, right?

**Comment by Golodhros** [comment]
Good call @martinmanzo! Yes, shouldReverseColorList sounds good, adding it to the refactor list!

**Comment by rwholey-eb** [comment]
This is a great idea! Is there anything else we should include in a major bump like this?

**Comment by Golodhros** [comment]
I have started refactoring the code. Changing seems easy thanks to our test coverage.

We were talking about keeping the old accessors with a `@deprecated` mark and a console log that warns about the deprecation and points to the new method. Testing with one keeping the behaviour, or we shouldn't?

It seems keeping the old method will be a bit annoying and pollute the code, but I guess would be much better for our users that migrate from the previous version.

Any opinions?

**Comment by martinmanzo** [comment]
I think that decision is up to you and how you intend to release the new version.

If it's a minor bump then it is more friendly to warn about method deprecation.
If you plan to make a 2.0 release the just remove the old code and make reference to the change in the CHANGELOG.

**Comment by Golodhros** [comment]
It makes sense. I was thinking on an major release, so maybe the warnings are not necessary.
Thanks!

**Comment by Golodhros** [comment]
Refactors done!
