### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by martinmanzo** [eventbrite/britecharts#313]
Hi team, any news on when are you going to release a new build?

Thanks!

**Comment by prsolucoes** [comment]
+1

**Comment by Golodhros** [comment]
I'm on it!
I hope I can find the time this weekend!

**Comment by Golodhros** [comment]
This is really hot, we have closed almost all our API changes and we are really close to have the release ready!

**Comment by Golodhros** [comment]
Britecharts 2.0 is here!
https://github.com/eventbrite/britecharts/releases/tag/2.0.0

Let us know what you think!

**Comment by martinmanzo** [comment]
Awesome!
With this done we can publish our first version of the Angular2 library!
Check it out: https://github.com/colapdev/ngx-britecharts

**Comment by Golodhros** [comment]
That's pretty cool!! So glad to see it spreading, thanks a lot Martin!
And thanks for the shoutout! it was a pleasure!
