### ISSUE TITLE
Line Chart Demo Brush Chart Doesn't Do Anything

### ISSUE THREAD

**Issue by mshenfield** [eventbrite/britecharts#324]
## Expected Behavior
The brush chart underneath the **Line Chart with fixed Aspect Ratio** in the [Line Demo](https://eventbrite.github.io/britecharts/tutorial-line.html) should change the domain of the line chart above, or the brush chart should be removed.

## Current Behavior
Creating a brush has no impact on the line chart.

<img width="795" alt="screen shot 2017-08-05 at 6 22 22 am" src="https://user-images.githubusercontent.com/4812055/28995141-7647f912-79a6-11e7-96c8-6df044d8324b.png">

## Possible Solution
Update the demo code to sync the line and brush charts, or delete the brush chart.

## Steps to Reproduce (for bugs)
1. Navigate to the [Line Demo](https://eventbrite.github.io/britecharts/tutorial-line.html).
2. On the brush chart below **Line Chart with fixed Aspect Ratio**, select a fixed area.
3. Observe that no change occurs in the line chart above.

## Context
This issue is a small distraction in the documentation.

## Your Environment
Chrome 59.0.3071.115

**Comment by Golodhros** [comment]
Thanks for the bug report @mshenfield !!
I have been changing stuff, so it makes sense.
