### ISSUE TITLE
Line gradient not applied to single line graph path 

### ISSUE THREAD

**Issue by rtorino** [eventbrite/britecharts#331]
Line gradient not applied to single line graph path when all data points are equal (either all 0s or all 100s)

## Expected Behavior
A straight horizontal line should be visible

## Current Behavior
Graph path not visible
<img width="532" alt="screen shot 2017-08-10 at 11 59 48 pm" src="https://user-images.githubusercontent.com/1680608/29180116-557bfa3a-7e29-11e7-86da-58dc55845b71.png">
<img width="525" alt="screen shot 2017-08-11 at 12 00 17 am" src="https://user-images.githubusercontent.com/1680608/29180120-5794eba6-7e29-11e7-9e2a-ec2328976b43.png">

## Possible Solution
Remove condition on this line in line.js file:
`.style('stroke', (d) => (
    dataByTopic.length === 1 ? `url(#${lineGradientId})` : getLineColor(d)
));`

## Context
Users will be confused since they can see nothing on the graph

**Comment by Golodhros** [comment]
Hi @rtorino , thanks for open the issue!

One question, does your data have more than one entry?

**Comment by rtorino** [comment]
@Golodhros Yes, it does have more than one entry. For the one week span, it has also 7 data entries.

**Comment by Golodhros** [comment]
Thanks! It must be a bug.
Could you share a codepen or a json file with the data?

Thanks for taking the time!

**Comment by rtorino** [comment]
@Golodhros here's a JSON data with all values equals 0

`dataByTopic: [{
  "topic": 5,
  "topicKey": "Price",
  "topicName": "Price",
  "dates": [{
    "date": "2017-07-31T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-01T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-02T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-03T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-04T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-06T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-07T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-08T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-09T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-10T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-11T16:00:00.000Z",
    "value": 0
  }, {
    "date": "2017-08-13T16:00:00.000Z",
    "value": 0
  }]
}]`

**Comment by Golodhros** [comment]
Thanks @rtorino , I will try to take a look at this soon!

**Comment by rtorino** [comment]
Cool!
