### ISSUE TITLE
Donut + Legend colors don't match when some quantities are 0

### ISSUE THREAD

**Issue by DJTB** [eventbrite/britecharts#336]
I have a donut and legend that accept a dataset that can include quantity values which are 0.
If only 3 of the values are above 0, the donut shows 3 slices, and the legend 6.
This is fine, however the colors do not align. I assume that both graphs are using colors incrementally for the values which are shown in them.

There might be a simple fix for this that I've overlooked!

## Expected Behavior
Donut and legend should match colors by ID - not by order.

## Current Behavior
Donut uses first 3 colors, Legend uses all 6.
![image](https://user-images.githubusercontent.com/5353151/29368436-5f288458-82a8-11e7-9ec1-16bf34f7ad73.png)

## Possible Solution
1) Match by id, or apply colors for full dataset in donut (though some slices won't be shown).
2) Allow color as a key for each object in dataset?

## Steps to Reproduce (for bugs)
 ```
  const dataset = [
    { 
      name: 'first',
      quantity: 2,
      id: 0,
    },
    { 
      name: 'second',
      quantity: 0,
      id: 1,
    },
    { 
      name: 'third',
      quantity: 6,
      id: 2,
    },
];
  donutContainer.datum(dataset).call(donutChart);
  legendContainer.datum(dataset).call(legendChart);
```
The color on donut for 'third' will not match the color on legend for 'third'

## Your Environment
* Version used: 2.0.0
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): Ubuntu

**Comment by Golodhros** [comment]
Hi @DJTB , thanks for the issue!!

Makes sense, it must be a bug.

**Comment by lnufnu** [comment]
@Golodhros Similarly, when calling stackedArea chart with a dataset with `value: 0`, the chart does not render fully and the console logs errors.

They begin with `Error: <rect> attribute height: A negative value is not valid. ("-0.015625")`, then repeating `Error: <path> attribute d: Expected number, "M0,NaNL709,341.0202…"` in a loop. When the chart renders, I think the areas after which it started throwing are blank.

<img width="211" alt="screen shot 2017-09-14 at 2 10 04 am" src="https://user-images.githubusercontent.com/11732163/30416469-e7912354-98f1-11e7-8993-cf94186e6f76.png">

**Comment by Golodhros** [comment]
Yeah, the stacked area chart needs values: http://eventbrite.github.io/britecharts/global.html#areaChartData__anchor
Probably the effects of values not being there are really unpredictable.
