### ISSUE TITLE
Background behind chart during animation is always white

### ISSUE THREAD

**Issue by Twisterking** [eventbrite/britecharts#340]
## Expected Behavior
If my container has for example a red background, the (line-)chart should just animate inside this container and build up from left to right. No white background should be visible.

## Current Behavior
the background of the svg chart during animation is always white. So a white rectangle is drawn in the DOM, which is then "filled up" with the chart from left to right.

## Possible Solution
Have some setting to set the background color of the chart, which is also used during animation.

## Steps to Reproduce (for bugs)
1. copy sample linechart code from [here](https://github.com/eventbrite/britecharts/blob/master/demos/demo-line.js)
2. set the background-color of the container div to red
3. see the glorious white rectangle 😁 

## Your Environment
Most current version (just installed), Chrome on OSX

**Comment by Golodhros** [comment]
Hi @Twisterking , thanks for the issue!

Totally understand. That animation is a bit hacky and we will love to make it more 'real'. In the meanwhile, what you propose makes sense, it shouldn't be hard to implement either.

Thanks!

**Comment by Twisterking** [comment]
Thanks for the quick reply! Sounds good!
Just a side note: Just setting a CSS `background-color` for the `<svg>` element did not change anything, during animation the background is **always white**.

**Comment by Golodhros** [comment]
Oh, yeah, as it is an svg element it would need to be 'fill'.

You can workaround this issue for the time being by doing:
  rect.overlay {
    fill: red;
  }

**Comment by Golodhros** [comment]
Hi @Twisterking , did this solution work for you?

**Comment by Twisterking** [comment]
Sorry for the late response @Golodhros - yes the solution works for me!

**Comment by robertmclaws** [comment]
Hey folks! Just an FYI, I had to implement this solution on a LineChart because redrawing the chart on window.resize was causing extra MaskingRectangles to be generated. But I had to use fill: transparent instead. Might be a bug in the rendering code. HTH!
