### ISSUE TITLE
Grouped bar with tooltip does not render properly

### ISSUE THREAD

**Issue by lnufnu** [eventbrite/britecharts#344]
## Expected Behavior
The chart should be able to be reconstructed from the demo with both tooltips and grouped bars.

## Current Behavior
When creating a grouped bar with tool tip as shown in the demo, the chart renders with `style=opacity: 0`. Without tooltips, it renders the grouped bars. It does not render the tooltips.

The grouped bars and tooltips render in the [codepen](https://codepen.io/marumarulson/pen/qXwbea), but when I use the same dataset, html, and js in my project, I get the error `Exception from Tracker Autorun TypeError: n.style(...).transition is not a function` when `isAnimated(true)` and `TypeError: t.exit(...).transition is not a function` when `isAnimated(false)`.

`t.exit(...).transition is not a function` is also thrown with the stacked area chart with tooltips, which do not appear.

## Possible Solution
`require('d3-transition')` in `grouped-bar.js` and `stacked-area.js` and maybe retest transitions on `drawGroupedBar()` starting at https://github.com/eventbrite/britecharts/blob/e6d59f8831c2b44f07ff4889ec7ef37be324b606/src/charts/grouped-bar.js with other datasets and selectors. Document necessary jquery selectors.
It would also be helpful if all charts were available in Codepen and JSBin. The [CDN page](https://eventbrite.github.io/britecharts/cdn.html) is blank right now. It may be overkill, but a viewer like https://bl.ocks.org/ would be helpful, especially if there are more charts added to the library.

## Steps to Reproduce (for bugs)
Here is a working demo in [codepen](https://codepen.io/marumarulson/pen/qXwbea)
1. Install Meteor
2. Meteor npm install & meteor npm install britecharts d3-selection
3. Change hello world template in `main.html` to `groupedBarTemplate`
4. Add this to your `main.js` and wrap everything in the codepen inside the `onRendered()` function
```import groupedBar from 'britecharts/dist/umd/groupedBar.min';
import colors from 'britecharts/dist/umd/colors.min';
import tooltip from 'britecharts/dist/umd/tooltip.min';
var d3Selection = require('d3-selection');

Template.groupedBarTemplate.onRendered(function() {...}
```
5. Change `britecharts.groupedBar()` to `groupedBar()` and `d3.select()` to `d3Selection.select()`
6. change to your directory and run `meteor` 

## Context
I am trying to create a grouped bar chart with a tool tip with a test data set in a Meteor project. 

## Your Environment
* Version used: 2.15.9
* Browser Name and version: Chromium 62.0.3 & Chrome 60.0.3
* Operating System and version: OSX Desktop

**Comment by Golodhros** [comment]
Hi @lnufnu, thanks for opening this issue!

That's interesting, we had some issues with the transitions not being loaded before and we thought we did fix it, it seems we didn't!

Could you try something real quick? Could you try to use the CDN version (https://cdn.jsdelivr.net/npm/britecharts@2.0.0/dist/bundled/britecharts.min.js) and see if that solves it? I am guessing that maybe our build process is removing the d3-transition library from our bundled versions.

In your codePen, as you are loading the whole d3 library, that problem won't happen. This should not be necessary, as we just need d3-selection.

Thanks for the feedback about the docs, we really appreciate it! We are definitely changing the demos format soon, although we haven't agreed on the best solution yet.

I just created a ticket for the blank CDN page: https://github.com/eventbrite/britecharts/issues/345

Thanks a lot!

**Comment by lnufnu** [comment]
Thanks @Golodhros for the quick response!

Using the CDN version solved it. Both the grouped bars and stacked bars worked this way.

Thank you for all the work on the library! It's awesome.

**Comment by Golodhros** [comment]
Thanks a lot @lnufnu, that means a lot to us!

So it must be that, our build system is taking d3Transition out of our bundled versions as it thinks we don't use it. We will try to solve it ASAP.

Closing this issue for now. Thanks for your support!

**Comment by Golodhros** [comment]
Solved, actually it was already solved, but we didn't have the proper release.
