### ISSUE TITLE
Cannot update selection on Donut charts

### ISSUE THREAD

**Issue by lnufnu** [eventbrite/britecharts#347]
When calling a second donut chart with the same selection, it does not update the chart. When binding a dataset to a new selection, it does not instantiate a second one.

## Expected Behavior
It should enter into the original selection, bind the data, and call the chart.

## Current Behavior
The original chart from the first selection disappears, when the chart is called with both a new selection and the original selection.

## Possible Solution
Not sure, but maybe look at line 204 of donut.js where data is being bound
```            if (!svg) {
                svg = d3Selection.select(container)
                  .append('svg')
                    .classed('britechart donut-chart', true)
                    .data([data]);  //TO REVIEW

                buildContainerGroups();
            }
```

## Steps to Reproduce (for bugs)
Here is [a pen](https://codepen.io/marumarulson/pen/WEVeNX) showing the bug.
The [bar chart](https://codepen.io/marumarulson/pen/qXwbea) works as expected.

## Context
I am trying to create a chart that updates with different datasets based on user input or a database cursor.

## Your Environment
2.15.9
Chrome 60.0.3
Max OSX

**Comment by Golodhros** [comment]
Hi @lnufnu , thanks for the issue!

Yes, this is a known bug of the Donut chart (https://github.com/eventbrite/britecharts/issues/291) and I am working on solving it right now. 

Thanks for your research and for your patience!!

**Comment by lnufnu** [comment]
Sorry, I did not realize there was an open issue for this. I will close this one.

Thank you!

**Comment by Golodhros** [comment]
Hi @lnufnu, this issue should be solved in the last release!

**Comment by lnufnu** [comment]
@Golodhros Awesome! Thank you so much!
