### ISSUE TITLE
Split Documentation in Tutorials, How To Guides, Reference and Discussions

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#349]
## Introduction
We want to have great docs. The approach explained in [this article](https://www.divio.com/en/blog/documentation/) makes a lot of sense and feels it will be a great organization for our docs. We can also get inspiration from the [Django docs](https://docs.djangoproject.com/en/1.11/ ).

We will split our docs in four groups:

*Tutorials*
A tutorial:
* is learning-oriented
* allows the newcomer to get started
* is a lesson
Analogy: teaching a small child how to cook

*How-to guides*
A how-to guide:
* is goal-oriented
* shows how to solve a specific problem
* is a series of steps
Analogy: a recipe in a cookery book

*Topics*
A topic:
* is understanding-oriented
* explains 
* provides background and context
Analogy: an article on culinary social history

*Reference*
A reference guide:
* is information-oriented
* describes the machinery
* is accurate and complete
Analogy: a reference encyclopaedia article

## Current Docs state
Our docs right now are formed by:
* Readme/Homepage
    * Key Features
    * Usage
    * API and Demo links
    * Installation
    * Roadmap
    * Links
    * Acknowledges
    * License
* Getting Started with BC
    * Installing Britecharts (npm/bower/git/cdn)
    * Using BC
    * Making it responsive
* Kitchen Sink
* Demos
* Contributing Guide
    * Setup
        * Getting setup to contribute
        * Creating feature branches
        * Running the Documentation and Demos
    * Modifying a chart
    * Creating a new chart
    * Pull Requests
        * Making pull requests
    * Reporting an Issue/Feature Requests
    * Standards
        * Test Driven Development
        * JSDoc
    * The Workflow
        * ES6 transpiling
        * yarn Tasks
    * Project Structure
* API
    * Charts
    * Types
* CDN Demo page
* Changelog
* Code Styleguide
    * API guidelines
    * Code Structure
    * JsDoc Comments

### Dev Docs
* Readme/Homepage
    * Key Features
    * Usage
    * API and Demo links
    * Installation
    * Roadmap
    * Links
    * Acknowledgements
    * FAQ
    * Contributors
    * License
* Changelog
* Contributing Guide
    * Project Structure
    * Reporting an Issue/Feature Requests
    * Pull Requests
        * Making pull requests
    * The Workflow
        * ES6 transpiling
        * yarn Tasks

### Documentation
Tutorials
* Getting started using BC
* Understanding Britecharts Structure
* Creating your first Data visualization
    * Making Charts interact between them

How To Guides
They guide you through the steps involved in addressing key problems and use-cases. They are more advanced than tutorials and assume some knowledge of how BC works.
* How to customize your chart's colors
* How to configure your time scales
* How to contribute
    * How to create feature branches
    * How to Run the Documentation and Demos
* How to modify a chart
* How to create a new chart

Topics
Discuss key topics and concepts at a fairly high level and provide useful background information and explanation.
* Reusable Chart API
* Test Driven Development
* JSDoc generated documentation
* API Guidelines

Reference
technical reference for APIs and other aspects. They describe how it works and how to use it but assume that you have a basic understanding of key concepts.
* Types
* Charts

## Change Process
We can create the new docs in markdown files and once we are ready, integrate them into the homepage docs using docstrap. The temporal files would be:
* _Topics
* _How to guides
* _Tutorials

We will start by letting the Readme as it is, adding the new sections. Then we can move the contents of the Contributing file to the new sections.

How does this look like?

**Comment by lnufnu** [comment]
I would like to help with guides and tutorials if you are looking for contributors.

I have reassembled the kitchen sink charts in the [Sandbox](https://codepen.io/lnufnu/pen/RLGbaG). I'm not sure if they already existed somewhere, but if not, hopefully they will be helpful to someone else starting out with Britecharts.

I would be interested in working on tutorials for getting started, guides for customizing charts, and discussions about the reusable pattern and D3 integration.

**Comment by Golodhros** [comment]
Hi @lnufnu,

That would be awesome! We would really appreciate your contribution on this!
Let's do this: I will create a shared doc with a summary of the current state of our docs and a proposed outline for the future. This way we will be able to get feedback and discuss the best approach. I will try to tackle it this weekend, should I use your github's account email to share it?

Regarding the Sandbox Codepen, thanks a lot for it! I was thinking last week, as some other people suggested, to move more demos into CodePen. I think having a 'Britecharts' account in CodePen would have sense, and we could try to populate it with nice examples and advanced configurations. 

I will create a different issue for this initiative: https://github.com/eventbrite/britecharts/issues/357 Let's move the conversation there.

Thanks a lot!

**Comment by Golodhros** [comment]
Hey @lnufnu , what do you think about the proposal?

**Comment by lnufnu** [comment]
It's awesome! I think that structure will work well.

**Comment by Golodhros** [comment]
This is a cool example of this method: https://www.algolia.com/doc/

**Comment by Golodhros** [comment]
I just created the structure in https://github.com/eventbrite/britecharts/pull/392

**Comment by Golodhros** [comment]
I would love to have a docs homepage with sections like in https://www.algolia.com/doc/.
I liked the simpliciyt of the blocks in http://bradfrost.github.io/style-guide-guide/guidelines/
