### ISSUE TITLE
Enable number formatting on all chart types.

### ISSUE THREAD

**Issue by piotrsucharski** [eventbrite/britecharts#350]
I'd propose to add numberFormat() method on all chart types not only on Legend. As I see you are using the numberFormat variable on all chart/tooltip types, but it's exposed only on Legend type. I don't see any reason for not exposing it for other types.

## Expected Behavior
Formatting a number is possible for all chart/tooltip types where numberFormat is used.

## Current Behavior
Formatting a number is possible only for Legend type.

## Possible Solution
It should be as simple as adding numberFromat method to exports as it is on Legend.

```
 exports.numberFormat = function(_x) {
            if (!arguments.length) {
                return numberFormat;
            }
            numberFormat = _x;

            return this;
        };
```

## Context
I use charts only for showing full numbers without any 0.5, 0.23 etc. I'd like to present number 4 to the user as just 4 not 4.00.

## Your Environment

* Version used: 2.0.0
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): Win 7

**Comment by Golodhros** [comment]
Hi @piotrsucharski , thanks for the issue!

That seems doable. There is a bunch of parameters that we haven't make open because we didn't know if they would be, so it makes sense for us to make them available as users like you need them.

Out of curiosity, in which specific charts would you need this?

Thanks!

**Comment by piotrsucharski** [comment]
I am using the following components:
- Bar
- Donut
- Legend
- Mini Tooltip
- Tooltip
- Brush
- Line

**Comment by Golodhros** [comment]
Thanks!
