### ISSUE TITLE
ES2015 preset needed when I import non-minified versions

### ISSUE THREAD

**Issue by piotrsucharski** [eventbrite/britecharts#352]
I'm using several components from britecharts library, and when I want to use latest version from master branch my webpack compilation fails because of es2015 preset missing. Everything works fine when I use latest 2.0.0 version from npm.

I'm using babel-loader from code transpilation and britecharts folder is included in my webpack config

## Expected Behavior
The compilation should work fine without es2015 preset, as it does for version 2.0.0 on npm.

## Current Behavior
The following error appears:
```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\TFS\\WorkZone Client\\Main\\Source\\client\\node_modules\\britecharts"
```

## Steps to Reproduce (for bugs)

1. import any britechart component using ES6 imports
2. Try to build the project with webpack

## Context
I want to use non-minified versions for development and debuging.

## Your Environment

```
"babel-core": "6.26.0",
"babel-loader": "7.1.2",
"babel-plugin-dedent": "2.0.0",
"babel-plugin-lodash": "3.2.11",
"babel-plugin-syntax-dynamic-import": "6.18.0",
"babel-plugin-transform-class-properties": "6.24.1",
"babel-plugin-transform-function-bind": "6.22.0",
"babel-plugin-transform-object-rest-spread": "6.26.0",
"babel-polyfill": "6.26.0",
"babel-preset-env": "1.6.0",
"britecharts": "git://github.com/eventbrite/britecharts.git#master",
"style-loader": "0.18.2",
"url-loader": "0.5.9",
"webpack": "3.5.6",
"webpack-merge": "4.1.0"
```

* Version used: latest
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): Win 7 desktop

**Comment by Golodhros** [comment]
Hi, thanks for the report!

Actually, we never thought of Britecharts used that way, but I guess it makes sense that it should be possible. Let me talk with @ryanwholey and see how should we approach this issue.

Thanks!

**Comment by piotrsucharski** [comment]
The possible solution could be that you ship a non-minified es5 versions of britecharts. Firstly it's easier to debug and secondly and that's more important:
 -If we include minified versions in the project and build it with webpack it tries to 'minify' them once again which heavily affects the performance (also it breaks the Resharper).

Moreover this will allow users of Britecharts to control the minification process by their build system and not by the library owners.

The suggestion for you is to drop es2015 and stage-0 presets as they're already deprecated in the latest version of Babel. You can just switch to use babel-preset-env.
https://github.com/babel/babel-preset-env

**Comment by Golodhros** [comment]
Thanks for the suggestion! It shouldn't be hard for us to include un-minified versions of our charts in ES5.

We will update our babel and webpack stuff soon, I hope that will solve this.

**Comment by Golodhros** [comment]
We just merged the update of Babel with the preset-env (#753)

The rest of this ticket's task will be tabled in #429
