### ISSUE TITLE
Brush chart does not have .locale() method

### ISSUE THREAD

**Issue by creage** [eventbrite/britecharts#354]
I'm using a **Line** chart combined with **Brush**, and want to display data in custom locale. **Line** chart, as some of others, has a [``.locale()``](https://eventbrite.github.io/britecharts/module-Line.html#.locale__anchor) method, and is fine, but **Brush** [does not](https://eventbrite.github.io/britecharts/module-Brush.html).

So, when you render your Line data in, let's say, ``.locale('da-DK')``, the Brush labels are still in English, which is confusing.

**Comment by Golodhros** [comment]
Hi @creage , thanks for filling the issue!

That's legit, the brush should have a locale as the line chart.

**Comment by martinmanzo** [comment]
Hi! I could tackle this the next week and add the locale() method to every chart that is missing it.

Mind making a list of which charts are missing it?

**Comment by creage** [comment]
According to API docs, these charts don't have a ```.locale()``` method
[Bar](https://eventbrite.github.io/britecharts/module-Bar.html)
[Brush](https://eventbrite.github.io/britecharts/module-Brush.html)
[Donut](https://eventbrite.github.io/britecharts/module-Donut.html)
[Grouped-bar](https://eventbrite.github.io/britecharts/module-Grouped-bar.html)
[Legend](https://eventbrite.github.io/britecharts/module-Legend.html)
[Mini-tooltip](https://eventbrite.github.io/britecharts/module-Mini-tooltip.html)
[Sparkline](https://eventbrite.github.io/britecharts/module-Sparkline.html)
[Stacked-bar](https://eventbrite.github.io/britecharts/module-Stacked-bar.html)
[Step](https://eventbrite.github.io/britecharts/module-Step.html)

**Comment by Golodhros** [comment]
Ah, it should not be that many.
Locale only make sense when the timeAxis is being used, so we will need it on the Brush and the Stacked Area charts.

Thanks a lot @martinmanzo !!

**Comment by martinmanzo** [comment]
Thanks to both!

I'll tackle this issue this week.

**Comment by Golodhros** [comment]
Thanks a lot @martinmanzo !

**Comment by martinmanzo** [comment]
Made a pull request!

While making the change I saw that Stacked Area already had a locale method so assumed that you meant Stacked Bar and added locale to it.

Let me know if that wrong to change it back.

Regards!

**Comment by Golodhros** [comment]
I actually wasn't, but it makes sense!
Thankss
