### ISSUE TITLE
Create and Populate a Britecharts account in CodePen

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#357]
Our demos are useful and help us maintain the library. 
But they are limited and we don't think it will be the best place to show less common configurations.
How can we create great examples for our users that can be shared and forked for their commodity?
Creating an official Britecharts account in CodePen and reproducing our demos there can solve this problems and raise more visibility for the project.

## Benefits
* Improved visibility
* Allows forking and modifications
* Makes it easier for our users to report bugs

## Cons
* It could be challenging to keep updates of all demos as the library and API changes (hopefully not too much)

## Alternatives
Using blocks of http://blockbuilder.org/
PRO: Move visibility for the D3 community
CON: It works by user, not organization

Using JSBin

## Demos to Upload
* We must have at least a simple example of all our charts
* We should provide most of the evident charts with tooltips and legends
* We should have another one with the kitchen sink (Inufnu provided [one](https://codepen.io/lnufnu/pen/RLGbaG) already)
* We should have a couple of charts with brushing
* Simple chart using the update pattern with cascading functions to change color or bind new data
* Demonstrating formatting values using line.xAxisFormat and/or d3-format
* Creating custom colorSchemas

Please provide feedback about this issue!

**Comment by lnufnu** [comment]
Hey @Golodhros! My github email is perfect if you would like to share your outline.

CodePen is great for small demos and how-tos, but it can be difficult to parse more complex examples. I think it is well suited for the demos you listed.

Blockbuilder might be more suited for full examples utilizing all of the API methods of a chart. Utilizing blockbuilder.org would allow users to rapidly create more structured Britecharts demos as well as build on existing charts without formally submitting a proposal. As the API changes, we could update charts by version, allowing others find examples of deprecated methods and the current usage.

Those demos would be great.
If we work on charts to recreate them in CodePen, would a set of the charts exactly as they are in the Github documentation be beneficial? If you would like them to differ, how would you like them to deviate?

Some demo/tutorials that might be beneficial are:
* simple chart using the update pattern with cascading functions to change color or bind new data
* Demonstrating formatting values using `line.xAxisFormat` and/or `d3-format`
* Creating custom colorSchema
* Instantiating the chart as a function like this for charts repeatedly called with the same configuration: https://codepen.io/lnufnu/pen/gGLZjV

**Comment by Golodhros** [comment]
Hi @lnufnu, thanks for your quick feedback!

Yes, I think a basic set of demos will make sense. Those in the docs demos have grown arbitrarily (there is no reason why we are showing some of the features and not others), so I guess it will make sense to create the most basic ones, and then show more customized charts.

Your suggestions make a lot of sense, I will add them to the proposal. 

Regarding the chart creation function, I think that's something users could do if they wanted to abstract out that process, although I don't think we should show it on the demos. The function signature won't scale for all the chart's configuration options.

Thanks a lot for the demos!! I have just created the Britecharts CodePen account and I will start forking your CodePens to fill it up!

**Comment by Golodhros** [comment]
It seems that if I fork Pens, they don't show up on the account's main page, just on the 'forks' section: https://codepen.io/Britecharts/#

We could also use the 'collections', I just created one with some Bar Charts: https://codepen.io/Britecharts/collections/popular/#
