### ISSUE TITLE
Choose a sort order for Bar Graph

### ISSUE THREAD

**Issue by samuraijane** [eventbrite/britecharts#358]
Similar to #303, it would be helpful if we could choose a sort order for the items listed in a bar graph.

For example, sort in ascending or descending order by:
  • name
  • value (percentage or quantity)

**Comment by Golodhros** [comment]
Hi @samuraijane , thanks for opening an issue!

This seems legit, it will make totally sense to add this feature. It should also work and have a similar API as the Donut chart.

Thanks!

**Comment by Golodhros** [comment]
Fixed by Daler with #415
