### ISSUE TITLE
New Custom Theme

### ISSUE THREAD

**Issue by rpheath** [eventbrite/britecharts#362]
The themes seem to be pretty straight-forward (array of colors). How should one go about creating their own theme?

I'm currently just passing an array of colors to the `chart.colorSchema(['...', '...'])` method, which I believe is all that it is, but there's nothing I could find in the documentation that outlined which item in the array is corresponding to which thing in the graph(s).

I'm assuming the schema's are pulling double-duty for multiple graph types, so not all array elements are needed from one graph to another, is that correct?

Is there somewhere that explains which each item relates to?

Thanks!

**Comment by Golodhros** [comment]
Hi @rpheath, thanks for the issue!

Yes, you are right, the creation of color schemas is as simple as an array with hex values. Yes, also the schema array doesn't need to have any given size. If you know the size of your data, having as many colors as the number of entries should work fine.

The assignation of colors to data entries is usually automatic, as we are using an ordinal scale from d3. There is a couple of proposals https://github.com/eventbrite/britecharts/issues/303 and https://github.com/eventbrite/britecharts/issues/358 about allowing to sort the elements of the chart. We are going to implement them, but I think that just doing the sorting yourself before injecting the data will work in most of the cases.

It's a good call you make for more docs about it. We are going to restructure the docs https://github.com/eventbrite/britecharts/issues/349, I will add a how to guide for customizing your colors.

Thanks again!
