### ISSUE TITLE
Keep donut chart slices highlighted

### ISSUE THREAD

**Issue by jbonigomes** [eventbrite/britecharts#365]
## Expected Behavior
I would like to keep the last highlighted donut chart slice highlighted on mouse out.

## Current Behavior
On mouse out, all donut chart slices highlight are cleared.

## Possible Solution
Highlight slice by id on mouse out.

## Steps to Reproduce (for bugs)
```javascript
import DonutChart from 'britecharts/dist/umd/donut.min';

const chart = (new DonutChart)
  .width(150)
  .height(150)
  .isAnimated(true)
  .internalRadius(35)
  .externalRadius(70)
  .highlightSliceById(1)
  .on('customMouseOut', (data) => {
    // the line below does not work
    chart.highlightSliceById(data.data.id);
  });

d3Selection.select(klass).datum(chartsData.donut).call(chart);
```

## Context
Just want to keep the slices highlighted for aesthetic reasons.

## Your Environment
* Version used: 2.0.1
* Browser Name and version: Chrome (latest)
* Operating System and version (desktop or mobile): Vagrant running Debian hosted on Windows 10
* Link to your project: Not available

**Comment by Golodhros** [comment]
Hi @jbonigomes, thanks for the issue!

Actually that option alread exists, it is called 'hasFixedHighlightedSlice', check it out in http://eventbrite.github.io/britecharts/module-Donut.html#.hasFixedHighlightedSlice__anchor

Cheers,

**Comment by jbonigomes** [comment]
Thanks Golodhros, works perfectly

**Comment by Golodhros** [comment]
Glad to help!
I hope you enjoy your experience with Britecharts!!

**Comment by jbonigomes** [comment]
Thanks @Golodhros you did an excellent job with Britecharts!!

**Comment by jbonigomes** [comment]
Hi @Golodhros I ran into another issue with it, when I hover out of the donut chart, it generally behaves as expected (the required slice gets highlighted, the first slice in my case), however, if I hover out from donut chart from the slice that is supposed to be highlighted (first slice in my case) then the slide does not highlight.

**Comment by Golodhros** [comment]
Interesting! We will take a look!

**Comment by jbonigomes** [comment]
Thanks @Golodhros
