### ISSUE TITLE
X-Axis Labels won't render

### ISSUE THREAD

**Issue by samturner** [eventbrite/britecharts#368]
On our charts we are unable to render any labels on the x-axis. Please see the image below for an example of what the chart looks like.

<img width="1158" alt="screen shot 2017-09-27 at 7 00 01 pm" src="https://user-images.githubusercontent.com/327959/30904714-1b1effec-a3b6-11e7-94fb-87a716c58d52.png">

## Expected Behavior

We expect the x-axis to show the date as it relates to each data point. In what circumstances do the labels render on the x-axis? I've seen some examples here: https://eventbrite.github.io/britecharts/tutorial-line.html that show dates on the x-axis. 

We also have the ability to filter our data on a per Minute/Hour/Day basis. We want to be able to force the granularity of the x-axis depending on the filter.

I've noticed that `.xAxisFormat` and `.xAxisCustomFormat`  exist as methods on Line, but am unsure if these are event the correct methods to use and have run into errors when trying to do so.

Below is a sample of data we're using to populate the graph:

```
{ "dataByTopic": [ 
{ "topicName": "Direct", "topic": 1, "dates": [ { "date": "2016-08-18T02:14:00+10:00", "value": 1 }, { "date": "2016-08-18T03:56:00+10:00", "value": 2 }, { "date": "2016-08-18T03:57:00+10:00", "value": 3 }, { "date": "2016-08-18T03:58:00+10:00", "value": 4 }, { "date": "2016-08-18T03:59:00+10:00", "value": 5 }, { "date": "2016-08-18T04:00:00+10:00", "value": 6 }, { "date": "2016-08-18T04:44:00+10:00", "value": 9 } ] }, 
{ "topicName": "Viral", "topic": 2, "dates": [ { "date": "2016-08-18T04:43:00+10:00", "value": 16 } ] }, 
{ "topicName": "Total", "topic": 3, "dates": [ { "date": "2016-08-18T02:14:00+10:00", "value": 1 }, { "date": "2016-08-18T03:56:00+10:00", "value": 2 }, { "date": "2016-08-18T03:57:00+10:00", "value": 3 }, { "date": "2016-08-18T03:58:00+10:00", "value": 4 }, { "date": "2016-08-18T03:59:00+10:00", "value": 5 }, { "date": "2016-08-18T04:00:00+10:00", "value": 6 }, { "date": "2016-08-18T04:43:00+10:00", "value": 16 }, { "date": "2016-08-18T04:44:00+10:00", "value": 9 } ] } 
] }
```

## Your Environment
* Version used: 2.0.1
* Browser Name and version: Google Chrome (Latest)
* Operating System and version (desktop or mobile): MacOS High Sierra

**Comment by Golodhros** [comment]
Hi @samturner , thanks for opening an issue!

Yes, in theory something like: 
```line.xAxisFormat(line.axisTimeCombinations.HOUR_DAY)```

would work for you.

Maybe you are experiencing problems with the margin? Try to add some more bottom margin, I think maybe the axis are there but you can't see them.

**Comment by samturner** [comment]
Hey @Golodhros, thanks for getting back to me!

I had my fingers crossed that it would be something silly like the margin issue, I tried that but unfortunately it didn't resolve the issue.

I've tried the following to set the `xAxisFormat`:

```
const chart = new britecharts.line()

chart
    .aspectRatio(isSmall() ? 1 : 0.3)
    .width(width)
    .grid('horizontal')
    .colorSchema(colorScheme)
    .isAnimated(shouldAnimate)
    .xAxisFormat(britecharts.line().axisTimeCombinations.HOUR_DAY)
    .on('customMouseOver', tooltip.show)
    .on('customMouseMove', tooltip.update)
    .on('customMouseOut', tooltip.hide)

container.datum(data).call(chart)

```

Which results in the following error that is not present without the `.xAxisFormat` call.

```
chart.aspectRatio(...).width(...).grid(...).colorSchema(...).isAnimated(...).xAxisFormat is not a function
```

We're running the latest Britecharts (2.0.1). Is there some syntactical thing I'm missing here?

**Comment by Golodhros** [comment]
I see.
In theory you don't need to 'new' the chart, and you could do:
  .xAxisFormat(chart.axisTimeCombinations.HOUR_DAY)

That said, could you try to reproduce your error in a codePen or JSBin and send me a link?

Thanks!

**Comment by samturner** [comment]
@Golodhros No worries. I'll put together a JSBin as soon as I get the chance!

**Comment by samturner** [comment]
I've put together a JSBin that illustrates the issue: https://jsbin.com/zirofok/edit?html,js,output.

If you uncomment the line that I've documented, you'll should see the error that I described above in the console.

I'm not very confident that this will resolve our issue this. Playing around in JSBin with some of our data appears to show the x-axis labels with no issue.

**Comment by Golodhros** [comment]
Hi @samturner, thanks for taking the time to create the JSBin and post here!

So, it seems you are importing the latest britecharts 1.X from the CDN. If you try with Britecharts 2.X it seems to work properly:
   <script src="https://cdn.jsdelivr.net/npm/britecharts@2/dist/bundled/britecharts.min.js"></script>

**Comment by samturner** [comment]
@Golodhros - Hah, of course! I based it off the Britecharts example JSBin and just assumed it would be using the latest.

This led me to investigate our own installation and confirm the version number, it looks as though Britecharts was not being including from NPM like I thought, but there was a britecharts.min.js file that was being included elsewhere meaning that our install was still running version 1 of Britecharts.

I fixed this up and can now properly use the `xAxisFormat` method. And after changing the format to `MINUTE_HOUR` which is the correct time scale for our data, I can see the labels! It seems as though the reason they weren't rendering before was because the time scale of our data is < 1 day (I'm assuming V1 just used some kind of default time scale?).

![screen shot 2017-10-03 at 2 29 30 pm](https://user-images.githubusercontent.com/327959/31108813-56cf061e-a847-11e7-8ea8-04704c04a5d3.png)

Thanks for your help, really appreciate it - just a bunch of assumptions and mistakes on my end. It's probably an edge case that people are using data sets with time scales as small as ours, but it might be worth making the caveat more clear in the docs somewhere.

**Comment by Golodhros** [comment]
Glad you figure it out!
Oh, I see, I will update the JSBin example right now! Sorry for that.
Totally, we should create a doc about scales, are a bit tricky.

Thanks for your time!
