### ISSUE TITLE
Stacked bar with tooltip does not render properly

### ISSUE THREAD

**Issue by lnufnu** [eventbrite/britecharts#372]
When trying to render a stacked bar chart with tooltips, I get errors. Am I calling this [chart](https://codepen.io/lnufnu/pen/aLLdQo) correctly?

## Expected Behavior
Instantiating a `tooltip()` and calling `show()` with `stackedBar` should render a tooltip.

## Current Behavior
The chart throws an error starting with 
```Uncaught TypeError: Cannot read property 'style' of undefined
    at Function.t.show (tooltip.js:637)
    at SVGSVGElement.<anonymous> (pen.js:15)
    at e.call (d3-dispatch.js:64)
    at U (stacked-bar.js:664)
    at SVGSVGElement.<anonymous> (stacked-bar.js:173)
    at SVGSVGElement.<anonymous> (d3-selection.js:124)
```

The stacked bar chart renders correctly otherwise (highlighting works).

## Possible Solution
It's probably unrelated, but the grouped bar chart was rendering without tooltips for me before the changes in #356.

## Steps to Reproduce (for bugs)
1. Create a chart with the most recent version of Britecharts
2. Instantiate a stacked bar and tooltip
3. Call both
[Live example](https://codepen.io/lnufnu/pen/aLLdQo)

## Your Environment

* Britecharts 2.15.9
* Meteor 1.5.1
* Chromium 62.0.3 & Chrome 60.0.3
* OSX Desktop

**Comment by Golodhros** [comment]
Hi @lnufnu, thanks for the issue!
I have just checked and something wrong is going on. I will try to make some time soon to see in more detail. It could be I broke it these days with the last refactors.

Thanks!

**Comment by lnufnu** [comment]
Awesome, thanks!

**Comment by Golodhros** [comment]
Hi! 
I checked the code and there were several issues.
The first was the selector of the tooltip container, it was missing a '.' at the beginning and it was using the 'stacked-area' container instead of the grouped bar one.
Also the dateLabel and topicLabel of the tooltip were wrong.
I have made a fork with it: https://codepen.io/Britecharts/pen/MEqZmq?editors=1010
