### ISSUE TITLE
gitter.im

### ISSUE THREAD

**Issue by lnufnu** [eventbrite/britecharts#377]
Would you consider fostering a community around https://gitter.im/ ?

## Expected Behavior
The gitter.im should be linked to the repository, and members of the organization should be Admins, free to participate as they wish. 

Some benefits others have noted:
* there's also an IRC bridge: https://irc.gitter.im/
* It might be a nice addition to the issue queue, e.g. to discuss things before an issue is even created
* issues can be easily referenced
* supports markdown
* it doesn't require people to create separate accounts
* indexed by Google
* good way for newcomers to connect to community

## Current Behavior
Currently, to discuss issues related to troubleshooting charts, features, and the future of the library you must create an issue. 

## Context
I have been running into small bugs that I'm not really sure need an issue. I have questions about charts and would love the chance to talk to other developers about Britecharts, as well as answer any questions if I can. I'd like to be able to get feedback about guides, tutorials, and maybe even some new charts.

**Comment by Golodhros** [comment]
Hi @lnufnu , thanks for opening an issue!

So, we have been talking about this for a while and maybe it's time to actually do it.

I was thinking on having a channel in the d3 slack community (d3js.slack.com), as most of the team is already there and Slack is pretty popular nowadays.

I just ping one of the admins there to see if that will be OK.

**Comment by rwholey-eb** [comment]
@lnufnu i like the idea of our community not having to create separate accounts, I can't be the only one who has trouble keeping track of all their slack accounts!!

**Comment by Golodhros** [comment]
It was approved, so we will host our discussions and tech support in https://d3js.slack.com (#britecharts channel)

Come and join us!

**Comment by Golodhros** [comment]
Just need to add the info in the docs, will do soon.
