### ISSUE TITLE
Fix a colour for a donut slice

### ISSUE THREAD

**Issue by jbonigomes** [eventbrite/britecharts#378]
## Expected Behavior
I would like to be able to stipulate a colour for each slice in the donut chart, for example, my client may run a report today where 'Sales values' show up in the colour of blue, maybe tomorrow when the data changes, 'Sales values' may show up as green.

## Current Behavior
Not able to stipulate the colour for slices in a donut chart.

## Possible Solution
Maybe change the data schema of the donut chart to allow a colour parameter to be passed in.

## Your Environment
* Version used: 2.0.1
* Browser Name and version: Chrome (latest)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: N/A

**Comment by Golodhros** [comment]
Hi @jbonigomes , thanks for creating an issue!

Will this be the same as proposed in https://github.com/eventbrite/britecharts/issues/359 ?

**Comment by jbonigomes** [comment]
That's exactly it, closing this one, sorry for the duplication.

**Comment by jbonigomes** [comment]
Out of curiosity, is there a workaround at the minute?

**Comment by Golodhros** [comment]
Yes, you should order the data by quantity descending, and then add the colorschema you want in the same order, it should let you map the data to the colors.

Let me know if that works!

**Comment by jbonigomes** [comment]
Thanks @Golodhros, would this solution work if I have missing slices? Maybe I could fill them with 'zero'?

**Comment by Golodhros** [comment]
Hi @jbonigomes , it wont' right now, but it will once we release, as I have just fixed a bug to include the zeroed slices.

If you use the github link to load the library, it should work right now.

**Comment by jbonigomes** [comment]
Thanks @Golodhros, what I will watch this space. Just for reference, what version will it be it?

**Comment by Golodhros** [comment]
I would be 2.0.2

**Comment by jbonigomes** [comment]
Thanks @Golodhros
