### ISSUE TITLE
Add human formatted values to Bar Chart yAxis

### ISSUE THREAD

**Issue by jbonigomes** [eventbrite/britecharts#380]
Right now, if the value we are showing is a money value, we don't have a mechanism to add and format the currency properly.

# Expected Behavior

We should be able to see the currency if the values are money values

# Current Behavior

We are showing only regular values

# Possible Solution

Add a 'human formatted value' to the chart configuration. Similar to the xAxisCustomFormat for Brush Charts

# Context

This will make Bar charts displaying monetary values clearer

**Comment by matix-eb** [comment]
Already accomplished by `labelsNumberFormat` 

http://eventbrite.github.io/britecharts/module-Bar.html#.labelsNumberFormat__anchor
