### ISSUE TITLE
Hover over bar chart for tooltip

### ISSUE THREAD

**Issue by jbonigomes** [eventbrite/britecharts#382]
When hovering over a bar chart that has tooltips using the mouse scroll function (middle wheelie button, or two fingers swipe), the tooltip appears in a blank state. I have a screenshot if needed.

## Expected Behavior
The obvious solution is to show it with the correct content, however, not showing it at all if the content is blank is also an option.

## Current Behavior
Tooltip is blank

## Possible Solution
Same as the expected behavior.

## Steps to Reproduce (for bugs)
In a page that has a bar chart with tooltips enabled, get to hover over the bar chart without actually moving the mouse, you may either use a trackpad and move the screen with two fingers swipe or use a mouse that has a 'wheelie' scroll button.

## Your Environment
* Version used: 2.0.1
* Browser Name and version: Chrome (latest)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: N/A

**Comment by Golodhros** [comment]
Hi @jbonigomes , thanks for the issue!

This is interesting, it seems that moving the mouse that way triggers the 'mouseOver' but it doesn't trigger the 'mouseMove' event, that is the one that fills in the tooltip.

I can't think about a lot of cases where this use case is common, but if this is an issue for you, as a workaround, you could basically remove the `tooltip.show` from the c`ustomMouseOver` event and add it to the beginning of the 'customMouseMove', so it would look like:
 
  .on('customMouseMove', function(dataPoint, topicColorMap, x,y) {
                tooltip.show();
                tooltip.update(dataPoint, topicColorMap, x, y);
  });

Let me know if that helps you.

**Comment by jbonigomes** [comment]
Hi @Golodhros, once again, you saved the day, thanks very much.
