### ISSUE TITLE
Stacked Area Chart Weirdness in 2.1

### ISSUE THREAD

**Issue by rpheath** [eventbrite/britecharts#397]
I'm using a stacked area chart with just **a single data source**. This has always worked in all versions prior to 2.1 — I like this over the line chart because it provides a nice background fill. After upgrading to 2.1, the chart now renders a bit of weirdness.

## Expected Behavior
This is how the chart rendered on 2.0, before upgrading, and what I was expecting:

![screen shot 2017-10-16 at 9 16 58 pm](https://user-images.githubusercontent.com/789/31642235-ddd131c6-b2b7-11e7-840f-0bfbe3268b07.png)

## Current Behavior
This is how the chart now renders on 2.1, after the upgrade:

![screen shot 2017-10-16 at 9 15 54 pm](https://user-images.githubusercontent.com/789/31642238-e7e4ed10-b2b7-11e7-8ba2-ce1f26393dc1.png)

## Possible Solution
I'm not sure what changed with the stacked area chart rendering, but something seems a little off? I don't have any suggestions for a solution.

## Steps to Reproduce (for bugs)
I'm not doing anything differently from what the documentation says to do, and my dataset matches the expected dataset format. The only change that caused this bug was upgrading from 2.0 to 2.1 😕

## Your Environment
* Version used: 2.1
* Browser Name and version: Latest Safari/Chrome
* Operating System and version (desktop or mobile): macOS Sierra
* Link to your project: [private]

**Comment by Golodhros** [comment]
Hi @rpheath , thanks for the issue!
It looks like a CSS problem. In this release we are adding a new element on the stacked area, so maybe that is what is failing.

Try to update the CSS styles and let me know if that fixed it.

**Comment by rpheath** [comment]
@Golodhros thanks, yes that was it! I updated the CSS from the release but didn't realize there was a linting issue and it didn't build my scss... Sorry about the false alarm! All's well now, thanks a lot 👍

**Comment by Golodhros** [comment]
No problem @rpheath, happy to help!
