### ISSUE TITLE
Drawing Axis Labels

### ISSUE THREAD

**Issue by Zangdarr** [eventbrite/britecharts#400]
For the purpose of a better chart reading, I would like to suggest the possibility to show labels for both the X and Y axes on the line chart (for my case, but can be extended to any type of chart).

## Expected Behavior
I thought about something like :
```
lineChart
    .setAxisLabelX("Production date")
    .setAxisLabelY("Product amount")
    .showAxisLabelX(true)
    .showAxisLabelY(true);
```
[https://imgur.com/a/VGOya](url)

## Current Behavior
Currently, I didn't find any way within the API to make it happen.

## Possible Solution
In britecharts/charts/lines.js
1. Add 4 variables : 
    - string axisLabelX
    - string axisLabelY
    - boolean showAxisLabelX
    - boolean showAxisLabelY

2. Add 4 functions : 
    - setAxisLabelX(string)
    - setAxisLabelY(string)
    - showAxisLabelX(boolean)
    - showAxisLabelY(boolean)

3. Update the function drawAxis() to draw the axes label if the corresponding flags are green.

**Comment by Golodhros** [comment]
Hi @Zangdarr , thanks for the issue!

We have not had this necessity but I guess it will make sense for some of our users.

The API you propose is fine, although I would prefer to not use the booleans, as the presence of the label would be enough to determine if we should show it or not.
