### ISSUE TITLE
Question: Tooltip DateTime Formatting?

### ISSUE THREAD

**Issue by rpheath** [eventbrite/britecharts#402]
I could be wrong, but it seems like the `tooltip.dateFormat()` expects one of the `HOUR_DAY`, `DAY_MONTH`, etc formats. Is there a reason why we can't just pass an acceptable d3 formatting string instead? i.e.

`tooltip.dateFormat('%m/%d @ %H:%M %p')`

When I try to do the `MINUTE_HOUR` format, I get something like "Oct 18, 08 PM" — that's hardly a very friendly date format to use.

My ultimate question: **Is there any way currently to use a truly custom date format in the tooltips? Something more granular?**

Thanks!

**Comment by Golodhros** [comment]
Hi @rpheath , thanks for the question!

Yeah, at this moment we don't support a fully custom date format in the tooltip.

I guess the solution would be to add a custom format like we do in the line chart with the xAxisCustomFormat variable: https://github.com/Golodhros/britecharts/blob/master/src/charts/line.js#L292

**Comment by rpheath** [comment]
@Golodhros awesome, thanks. I really do need the ability to support custom dates, so I made a PR to hopefully get that functionality in!

https://github.com/eventbrite/britecharts/pull/403

I wasn't able to request a review from anyone, but hopefully someone can take a look at it soon!
