### ISSUE TITLE
Change styling on Search results

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts#406]
## Expected Behavior

We want to see a styling of the search results that is a bit more good looking

## Current Behavior

It looks like this:
![britecharts_-_d3_js_based_charting_library_of_reusable_components](https://user-images.githubusercontent.com/9063187/31843505-3d0a1098-b5a8-11e7-959c-63820e11e966.png)

## Possible Solution

We should change the generated markup to use something less ugly

## Steps to Reproduce (for bugs)

1. Go to the homepage docs
2. Do a search for 'bar'
3. See the results in a modal

**Comment by Golodhros** [comment]
Closing this, let's tackle it along with https://github.com/eventbrite/britecharts/issues/395, as it seems we will probably change the whole thing after all.
