### ISSUE TITLE
line chart with animate and display problems

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#418]
This is screenshots 

http://uploads.im/npe7R.gif

My code is here:

```js
    let container = d3Selection.select('.ui-line')
    let line = new Line()
    if (container.node()) {
      line
        .isAnimated(true)
        .height(this.height)
        .width(this.width)
        .grid('horizontal')
        .tooltipThreshold(600)
        .lineCurve('basis')
        .on('customMouseOver', () => {})
        .on('customMouseMove', () => {})
        .on('customMouseOut', () => {})
      console.log(this.thisValue)
    }
    let valueObj = {}
    valueObj.dataByTopic = this.thisValue
    container.datum(valueObj).call(line)
```
most of this codes is from your website's demo. where is the problem?

* Version used: 2.3.1
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): Windows 10 64 bit

**Comment by jchen-eb** [comment]
Hi @Dieber, thanks for filing an issue. It looks like the CSS is not being loaded, can you check to see that you're including it on the page where you're using britecharts?

**Comment by Dieber** [comment]
Got it! Thank you
