### ISSUE TITLE
Line chart y-axis labels don't render when chart loads in a hidden document / background tab

### ISSUE THREAD

**Issue by CoryDuncan** [eventbrite/britecharts#424]
The problem appears to be the `transition()` call in https://github.com/eventbrite/britecharts/blob/master/src/charts/line.js#L552-L553. D3 runs `transition()` in a `requestAnimationFrame()` and in most browsers, calls to `requestAnimationFrame()` are paused for hidden documents. In this case, it seems to prevent the line chart y-axis labels from rendering. Tested using Chrome 61.

## Expected Behavior
Line chart y-axis labels are rendered when chart loads regardless of document visibility.

## Current Behavior
Line chart y-axis labels are not rendered when chart loads while the document is hidden.

## Steps to Reproduce (for bugs)
With a line chart containing y-axis labels, load the chart while the document is hidden.

**Comment by Golodhros** [comment]
As mentioned in the PR, let's get rid of that transition.
