### ISSUE TITLE
Add Barchart customClick event

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#442]
I haven't found 'click' event in britecharts
when I use 
 .on('click', () => {
    // Do sth
 })
but it doesn't work and throw me an error.
Is Britecharts only customMouseOut/Over/Move can use?

**Comment by Golodhros** [comment]
Hi @Dieber , thanks for opening an issue!

Yeah, usually the name of the events have a custom in front of them. You can find the specifics of every chart on our homepage http://eventbrite.github.io/britecharts/index.html, in the 'API' dropdown.

Thanks

**Comment by Dieber** [comment]
Hi @Golodhros Thanks for your answering my question
but I don't understand yet whether it provide a click or touchstart event,if those event can be used,how can I use that?

**Comment by Golodhros** [comment]
Hi @Dieber,
It depends on the chart. Which one are you using?

**Comment by Dieber** [comment]
Hi @Golodhros 
Bar.
and I found that Bar component provides 3 events:customMouseOver,customMouseMove and customMouseOut.
but click or customClick don't exist.
so,Bar doesn't provide that?

**Comment by Golodhros** [comment]
Nope. We could add it though.
Out of curiosity, what's your use case? Why do you need to listen for click?
Thanks!

**Comment by Dieber** [comment]
@Golodhros Thanks for your patient.
i just wanna click it and show up a toast in my application
but no matter the case is...
It's wired that it have mouseover and mouseout event but haven't click event which is more basically.. isn't it?😀

**Comment by Golodhros** [comment]
Sure, no problem!
Well, our use case has been only a permanent tooltip. I can see why you want that. For us it is a matter of whether the user knows that she can click the bar.

We could add it to the backlog, it's pretty easy. I can't give you a timeline though.

**Comment by Dieber** [comment]
@Golodhros Thanks for your helping. I'll use mouseOver instead of click...temporarily...and good night

**Comment by Golodhros** [comment]
Thanks for using Britecharts!

Mouse over will give you this as arguments:
```event, dataPoint, [mouseXPosition, mouseYPosition], [chartWidth, chartHeight]```

Good night!

**Comment by Golodhros** [comment]
Implemented by @DalerAsrorov
