### ISSUE TITLE
Error: originalData.reduce is not a function

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#445]
Me Again~

When I use the stackedArea, there is an error:
**TypeError: originalData.reduce is not a function
 at cleanData (stackedArea.min.js?71a5:13937)**

my code is:

    let container = d3Selection.select('.stacked-area-container')
    let stackedArea = new StackedArea()
    if (container.node()) {
      this.thisValue = {
          'data': [
              {
                  "date": "2011-01-05T00:00:00Z",
                  "name": "sample1",
                  "value": 0
              }, {
                  "date": "2011-01-06T00:00:00Z",
                  "name": "sample2",
                  "value": 0
              }, {
                  "date": "2011-01-07T00:00:00Z",
                  "name": "sample3",
                  "value": 0
              }
          ]
      }
    container.datum(this.thisValue).call(stackedArea)

so,How it happen? look forward to your reply😄.

**Comment by Golodhros** [comment]
Interesting.
In theory, the call to the chart needs to happen within the 'if' that checks for the container. If that check is false, you would call the chart with undefined data.

Check to move that line 1 position up. Let me know if it works.

**Comment by Dieber** [comment]
Ok, I did what you said..But it doesn't work and the error is same as before..

Avoid misunderstandings, Here is the code:

    if (container.node()) {
      console.log(123)
      this.thisValue = {
          'data': [
              {
                  "date": "2011-01-05T00:00:00Z",
                  "name": "sample1",
                  "value": 0
              }, {
                  "date": "2011-01-06T00:00:00Z",
                  "name": "sample2",
                  "value": 0
              }, {
                  "date": "2011-01-07T00:00:00Z",
                  "name": "sample3",
                  "value": 0
              }
          ]
      }
      stackedArea.on('customMouseOver', (e) => {
        this.$emit('customclick', e)
      })
      .on('customMouseMove', (e) => {
      })
      .on('customMouseOut', (e) => {
      })
      container.datum(this.thisValue).call(stackedArea)
    }

**Comment by Dieber** [comment]
OK, problem solved..
I tried to import that css and it works..

**Comment by mpoqq** [comment]
I hat today the same problem and I did the same mistake. Your problem was not the css, but you had to do `container.datum(this.thisValue.data).call(stackedArea)`.
originalData.reduce can only be called on an array and 'thisValue' is not one. 
On [this](https://github.com/eventbrite/britecharts/blob/85ae67bfbb303975ce27dcf7cf94798ab519b53c/demos/demo-stacked-area.js#L57) line in the Demo you can see that the reference to the array in the data object.

**Comment by mpoqq** [comment]
I looked in the API on the homepage and it says that "the data to attach and generate the chart"  is: [areaChartData](https://eventbrite.github.io/britecharts/global.html#areaChartData). 
Therefore, I used this JSON format as input, which was wrong.
So maybe change this in the documentation  :smile:.

**Comment by Golodhros** [comment]
Oh, I see.
It seems we are not consistent on adding the 'data' object in the data definitions. 
We should definitely fix it.

Thanks!

**Comment by Golodhros** [comment]
Created https://github.com/eventbrite/britecharts/issues/445#issuecomment-352200048

**Comment by mpoqq** [comment]
That would be great.
Thank your for your awesome work :smile:
