### ISSUE TITLE
Data requirements

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#447]
## Expected Behavior

The documentation points out the proper data structure.

## Current Behavior

Sometimes  we add a 'data' key and sometimes we don't.

## Possible Solution

Make this consistent and accurate.

## Context

See https://github.com/eventbrite/britecharts/issues/445

**Comment by interdigitize** [comment]
Hi Golodhros, I am a first-time contributor looking into fixing this...

**Comment by Golodhros** [comment]
Hi @interdigitize , thanks for helping us with this and welcome!!

Please check out the contributing guide and let me know if there is something not clear enough, any feedback will be appreciated! We want to make easy to contribute to Britecharts!

Regarding this issue in particular, the data types are getting extracted from the comments in the code, that you can find in /src/charts/*.js, in the 'typeDef' comments. Those are getting extracted and generated into the docs.

thanks a lot!!

**Comment by interdigitize** [comment]
Thanks @Golodhros! The contributing guide seems straightforward. I forked it, installed dependencies and set up a fix-branch. I am looking at the typeDefs in js files in the /src/charts folder. 

Before I change anything, just want to clarify. All chart components have a data key with an array value, but not all chart documentation examples show the data key. So I don't need to refactor anything. All I need to do is update the type declarations and examples so when JSdocs, or something similar, recompiles it to markdown, the documentation for all charts will show the data key, similar to https://eventbrite.github.io/britecharts/global.html#areaChartData and https://eventbrite.github.io/britecharts/global.html#GroupedBarChartData

Is that right?

**Comment by Golodhros** [comment]
Great!
So yeah, basically that, but I think we **don't want** to show the 'data' key, as the chart is expecting an array, not an object with a data key.

Thanks a lot!

**Comment by interdigitize** [comment]
Ah okay. Remove it from those chart examples that have it. Will do!

**Comment by interdigitize** [comment]
@Golodhros just submitted a PR! Let me know if any edits are needed.

**Comment by Golodhros** [comment]
Thanks for your first contribution!! 🎆 🍾
