### ISSUE TITLE
Add Loading states to charts

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#449]
## Description

We want to have loading states with an svg drawing and an animation available in our charts.

## Possible Solution

Use SVG and CSS animations
The SVGs are the ones added in https://github.com/eventbrite/britecharts/pull/451
For the animations, use the styles in https://codepen.io/albybarber/pen/YEbEZr

The solution will be based on showing this loading states when the chart is called over 'null' data.
We would probably store this svgs as templates. We should also add a getter/setter to allow users to provide their own, and to provide the loading state to Britecharts-react charts.

## Context

Making our user experience awesome for asynchronous loading charts

**Comment by evb-sun** [comment]
![loading](https://user-images.githubusercontent.com/13459095/34222099-401c7126-e56f-11e7-9582-a3c674d4bdd3.png)
To prevent loading states from becoming too literal, line and area charts (including the multiple values variants) will be using the same loading states.
https://github.com/eventbrite/britecharts/pull/451
