### ISSUE TITLE
[Bug]Line Chart's X-axis and data position dot is not justified

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#453]
this bug appeared both of line Chart and Stacked Area Chart

Screenshots:

https://i.loli.net/2017/12/25/5a40c8033476b.png

https://i.loli.net/2017/12/25/5a40c626ee0b4.png

Thanks for you guy's help and Merry X'mas

**Comment by Golodhros** [comment]
Hi @Dieber, thanks for the issue!

Aligning ticks and data entries is something we have tried before but it is not possible. The way D3 scales work don't allow us to specify at that level the positioning of the ticks.

Thanks for checking though!
