### ISSUE TITLE
Add 'areaCurve' configuration option to Stacked Area 

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#455]
We want to be able to configure the interpolation function used by the stacked area in order to draw the curves between data points. This will be similar to the 'lineCurve' option in the line chart ( http://eventbrite.github.io/britecharts/module-Line.html#.lineCurve__anchor).

We should:
* Find in the code where we are setting this interpolation
* Create a variable to parametrize it (if it wasn't there already)
* Create a getter/setter (with its tests) to allow this modification

**Comment by Golodhros** [comment]
Hi @Dieber, thanks for the proposal.
Just to understand, you mean you would like to have a areaCurve accessor the same way we have a lineCurve option in the line chart: http://eventbrite.github.io/britecharts/module-Line.html#.lineCurve__anchor ?

**Comment by Dieber** [comment]
@Golodhros 
Yes, That's right.

**Comment by dalerasrorov-eb** [comment]
Thanks for raising the issue @Dieber, the functionality should be available after this https://github.com/eventbrite/britecharts/pull/504 gets merged. Shares same curve configurations as the line chart.
