### ISSUE TITLE
Add touchmove event to line and stacked area charts

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#456]
Is it possible to consider adding a 'touchmove' event in order that updating position of tooltip when finger moving on linecharts?

Thanks n Merry X-mas

**Comment by Golodhros** [comment]
Hi @Dieber , thanks for the proposal.
That makes sense and it shouldn't be hard to add a 'touchmove' event along with the current 'mousemove' events we are using.

**Comment by dalerasrorov-eb** [comment]
@Dieber I am trying to understand what you mean by ```...in order that updating position of tooltip when finger moving on linecharts?```

Could you provide more details on what you need and what in this case `touchmove` mean? The `touchmove` event sounds more like a drag-and-drop movement, but it seems like it's not the same in your case. Would appreciate more information.

**Comment by ISMAELMARTINEZ** [comment]
I believe @Dieber is talking about adding touch events to the charts (We are also really interested in that feature!!).

https://github.com/d3/d3-selection/blob/master/README.md#touch

It does seem to be possible to add it via d3 in a similar way as the mouse events are handle, but might be better creating a common "eventsHandling" object that all the charts can use (so to avoid code duplication).

We don't have bandwidth at the moment to develop it, but I am happy to review or comment and test that code. 

Thanks,

**Comment by dalerasrorov-eb** [comment]
Thanks for helpful info @ISMAELMARTINEZ that sounds like a nice feature to add to charts. First we would create it for one chart, see how it is used, and then create a sharable function that can be used by other charts. Will keep you posted.

**Comment by ISMAELMARTINEZ** [comment]
are you looking also into adding click and touch events? Thanks.

**Comment by ISMAELMARTINEZ** [comment]
I will add a comment in that commit. Great job.
