### ISSUE TITLE
[question]Can I change the Tooltips Color?

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#457]
Hey Me again~

I want to change the tooltips'color in my project, is this impossible?

thanks for your helping

**Comment by Golodhros** [comment]
Hi @Dieber , thanks for the question.

I understand you want to change the styling of the tooltip, right? In theory you can do several things by overriding the CSS styles of the tooltip. You will need to use SVG attributes like 'fill' and 'stroke' to style these elements.

Let me know if that worked for you.

**Comment by miglesiasEB** [comment]
Did this work?

**Comment by Golodhros** [comment]
Closing for now, feel free to reopen.
