### ISSUE TITLE
Add option to draw permanent highlight points to line chart

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#459]
We want to allow users to keep the dots highlighted on the line chart.

They should probably have a slightly different styling as when we show them when hovering.

![](https://user-images.githubusercontent.com/17017234/34381051-fc6d1598-eb40-11e7-996b-cf144e0da919.png)

**Comment by Golodhros** [comment]
Hi @Dieber,
I am not sure to understand this issue. Could you give us a bit more context?

**Comment by Dieber** [comment]
@Golodhros 
Thx for your reply, I'm amazing that you response all my question even my English sucks lol.


I mean add a hollow circular point on each data, like this
![feature](https://user-images.githubusercontent.com/17017234/34381051-fc6d1598-eb40-11e7-996b-cf144e0da919.png)

Thanks

**Comment by Golodhros** [comment]
Ah, yeah, that makes sense. Adding it as a proposal.

**Comment by dalerasrorov-eb** [comment]
You can use `shouldShowAllDataPoints ` in the next release
