### ISSUE TITLE
BarChart - PercentageLabels

### ISSUE THREAD

**Issue by mrbongiolo** [eventbrite/britecharts#462]
https://github.com/eventbrite/britecharts/blob/6f56064e2215903a47c4d9d6637a1c0574a8ff0b/src/charts/bar.js#L87

Why the `verticalLabelFormat` is using `".0f"` as format? Could I add 2 new functions to be able to update the formats of `verticalLabelFormat` and `horizontalLabelFormat`?

**Comment by mrbongiolo** [comment]
TBH instead of having an `enablePercentageLabel` it would be better to have more generic `enableLabel`, and a `labelFormat` options. And then `labelFormat` could automatically be set to a percentage format when `hasPercentage(true)` is used, or just use it with any custom format from d3-format.

**Comment by Golodhros** [comment]
Hi @mrbongiolo, thanks for opening an issue!

Yeah, we were looking into adding that option for the formats: https://github.com/eventbrite/britecharts/issues/380. 

What you comment about having a more generic enableLabel sounds great. It would be awesome if you could create an issue or edit this one to describe that change.

Feel free to check the Contributing guide and send us a PR with it, we are super responsive :)

**Comment by mrbongiolo** [comment]
@Golodhros Thanks for answering so promptly :)

I'll add another issue with the `enableLabel` suggestion and see if I can open a PR with it also.
