### ISSUE TITLE
Replace enablePercentageLabels() with a generic enableLabels() on BarChart

### ISSUE THREAD

**Issue by mrbongiolo** [eventbrite/britecharts#463]
## Expected Behavior
When `enableLabels` is set to `true` it will enable labels over the bars.
The label text format should use the default bar value format or the one set on `numberFormat`.
When `hasPercentage(true)` is set it will change `numberFormat` and so the text format of the label will change as well.
Optional: add a `labelFormat` that could be set instead of `numberFormat`, so the barAxis could be shown with a percentage format and the label could have another format. Useful if one wants to show % on the bar, but the actual numbers on the label.

## Current Behavior
Currently the `enablePercentageLabels` on vertical bars is broken (see #462), besides of that, `enablePercentageLabels` seems too rigid. A generic approach should be easy enough to implement.

**Comment by mrbongiolo** [comment]
I'll try to open a PR for this on the weekend or in the next week.

**Comment by Golodhros** [comment]
Thanks a lot @mrbongiolo!
