### ISSUE TITLE
Question/Bug: 'usePercentage' on BarChart

### ISSUE THREAD

**Issue by mrbongiolo** [eventbrite/britecharts#464]
https://github.com/eventbrite/britecharts/blob/6f56064e2215903a47c4d9d6637a1c0574a8ff0b/src/charts/bar.js#L922

The `v2.0.0` notes on the CHANGELOG said that `usePercentage` was changed to `hasPercentage`, but it's still active, both options are displayed on the docs also, and looking on the source it seems like both change the same variable >.<

**Comment by Golodhros** [comment]
Oh, good call!
It seems that never got cleaned, thanks!

**Comment by Golodhros** [comment]
Fixed in #478 by @mrbongiolo
