### ISSUE TITLE
Add a demo for the Legend

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts#469]
## Expected Behavior

Our legend component has some extra features, let's create a demo for it

## Current Behavior

We are using the donut demo to demonstrate the legend

**Comment by rumshenoy** [comment]
Hi, I would like to work on this.

**Comment by Golodhros** [comment]
Hi @rumshenoy, that would be awesome!

The process would be the same as described in the [Contributing Guide](https://github.com/eventbrite/britecharts/blob/master/.github/CONTRIBUTING.md#creating-a-new-chart) for creating a new chart, but only from the step 7 and forward. 

Take a look at a simple demo page like the one for the [sparkline](http://eventbrite.github.io/britecharts/tutorial-sparkline.html) as an example.

Let me know if you hit a blocker!
Thanks!

**Comment by rumshenoy** [comment]
Hi, Ive been a little busy over the past week and will be for this weekend as well. In case, anyone wants to take this issue, please go ahead. I will be back to this on Tuesday and if anyone hasn't picked this then, will continue. Sorry and thank you. Just thought I'd inform.
