### ISSUE TITLE
Add legend text size configuration to Donut Chart

### ISSUE THREAD

**Issue by nediljko** [eventbrite/britecharts#474]
Is it possible to show only percentage (without name) in donut chart ?

**Comment by nediljko** [comment]
Or to reduce the size of text so it fits ?

**Comment by Golodhros** [comment]
Hi @nediljko, thanks for the question!
Right now we don't support that option, but it should be easy to add.

As a workaround, you could hide the name using CSS with:
   .donut-text .label {
     display: none;
   }

**Comment by nediljko** [comment]
Hi, thanks a lot I made it work

**Comment by mrbongiolo** [comment]
@Golodhros would it make sense to have a custom method for the `text` on `drawLegend`?
Right now it calls this: `text( () => `${obj.data.percentage}% ${obj.data.name}` )`, imho it would be nicer to have a `legendTextFunction` options, that accepts a new function, it's called with the `obj.data`.
If it's ok with you I would create a new issue & PR for this feature.
The default function should still be the same.

**Comment by Golodhros** [comment]
@mrbongiolo That would be great! Thanks for doing this!!

**Comment by dalerasrorov-eb** [comment]
Looks like a duplicate from https://github.com/eventbrite/britecharts/issues/481, this feature was implemented and is available.
