### ISSUE TITLE
Handle long labels on bar chart

### ISSUE THREAD

**Issue by chinaowl** [eventbrite/britecharts#486]
## Expected Behavior

I think it would be nice if long labels in bar charts automatically wrapped.

## Current Behavior

If the labels are too long, they overlap each other and become unreadable.

## Steps to Reproduce (for bugs)

Here is a pen to demonstrate: https://codepen.io/chinaowl/pen/KZGzXB

## Your Environment

* Version used: 2.4.11
* Browser Name and version: Chrome 63

Thank you in advance!

**Comment by dalerasrorov-eb** [comment]
Thank you for pointing it out and providing an example of that. It definitely doesn't look good. One of the things that come to mind is to have a different wrap-text property. If there is better suggestions let us know.

**Comment by Golodhros** [comment]
Hi China, thanks for the issue.
This is a fairly common issue of vertical bar charts.
A workaround can be to use CSS transforms to rotate the labels. However,
the best solution is to directly use a horizontal bar chart. Ours also has
some extra options for adjusting label positions and it has text wrapping.

**Comment by Golodhros** [comment]
Given the number of issues we have pending, the difficulty of doing this with guarantees and that there is an easy workaround, I will close this issue for now.
