### ISSUE TITLE
Horizontal gridlines do not update on Bar Chart

### ISSUE THREAD

**Issue by chinaowl** [eventbrite/britecharts#487]
## Expected Behavior

The horizontal dashed gridlines on a bar chart should be spaced evenly, and/or it would be nice to specify how many of those lines to draw.

## Current Behavior

I don't really understand the current behavior. If you look at [this pen](https://codepen.io/chinaowl/pen/EoOjdB), only the first chart has nicely spaced gridlines. I varied the data for the other three and there are always three lines grouped at the top 3 ticks for some reason.

## Steps to Reproduce (for bugs)

https://codepen.io/chinaowl/pen/EoOjdB

## Your Environment

* Version used: 2.4.11
* Browser Name and version: Chrome 63

**Comment by chinaowl** [comment]
I have a very similar issue here: https://codepen.io/chinaowl/pen/opQxBK

It seems like the horizontal gridlines do not update when the data changes. I'm hoping to avoid having to destroy the entire chart and initialize everything again.

**Comment by Golodhros** [comment]
Hi @chinaowl, thanks for the issue!

You are right, this should get updated automatically. I did a sweep some time ago doing a change like this, I guess I missed this one. We should fix it.

thanks!
