### ISSUE TITLE
SVGSVGElement error

### ISSUE THREAD

**Issue by shiyafei** [eventbrite/britecharts#488]
When hover a bar, then error:
`
tooltip.js?0762:699 Uncaught TypeError: Cannot read property 'style' of undefined
    at SVGSVGElement.exports.show (tooltip.js?0762:699)
    at Dispatch.call (stackedBar.min.js?cc8a:5235)
    at handleMouseOver (stackedBar.min.js?cc8a:13704)
    at SVGSVGElement.eval (stackedBar.min.js?cc8a:13278)
    at SVGSVGElement.eval`

Mine code is:
`const dataset = {
        data: [
          {stack: 'vivid', name: 'Direct1', views: 0, date: '2011-01-05'},
          {stack: 'vivid', name: 'Direct2', views: 10, date: '2011-01-06'},
          {stack: 'vivid', name: 'Direct3', views: 16, date: '2011-01-07'},
          {stack: 'vivid', name: 'Direct4', views: 23, date: '2011-01-08'},
          {stack: 'sparkling', name: 'Eventbrite1', views: 23, date: '2011-01-05'},
          {stack: 'sparkling', name: 'Eventbrite2', views: 16, date: '2011-01-06'},
          {stack: 'sparkling', name: 'Eventbrite3', views: 10, date: '2011-01-07'},
          {stack: 'sparkling', name: 'Eventbrite4', views: 0, date: '2011-01-08'},
          {stack: 'sunny', name: 'Email1', views: 10, date: '2011-01-05'},
          {stack: 'sunny', name: 'Email2', views: 20, date: '2011-01-06'},
          {stack: 'sunny', name: 'Email3', views: 26, date: '2011-01-07'},
          {stack: 'sunny', name: 'Email4', views: 33, date: '2011-01-08'}
        ]
      }

      let stackedBar = new StackedBar()
      let chartTooltip = tooltip()
      let container = d3Selection.select('.js-stacked-bar-chart-tooltip-container')
      let tooltipContainer = d3.select('.metadata-group')

      stackedBar
        .tooltipThreshold(600)
        .width(800)
        .grid('horizontal')
        .isAnimated(true)
        .stackLabel('stack')
        .nameLabel('date')
        .valueLabel('views')
        .betweenBarsPadding(0.3)
        .on('customMouseOver', chartTooltip.show)
        .on('customMouseMove', function(dataPoint, topicColorMap, x, y) {
          chartTooltip.update(dataPoint, topicColorMap, x, y)
        })
        .on('customMouseOut', chartTooltip.hide)
      container.datum(dataset.data).call(stackedBar)

      chartTooltip.title('Testing tooltip')

      tooltipContainer.datum([]).call(chartTooltip)`

**Comment by Golodhros** [comment]
Hi @shiyafei , thanks for opening an issue!

Could you add this to a codePen in order for us to take a look at it? You could use this one as a template: https://codepen.io/Britecharts/pen/oGBEeO

**Comment by smchae** [comment]
@Golodhros If I have more than 7 labels on x-axis, `rec` element does not have a height attribute.

You can reproduce on your codePen above https://codepen.io/Britecharts/pen/oGBEeO with data 

```
{stack: "vivid", name: "Direct1", views: 0, date: "2011-01-01"},
    {stack: "vivid", name: "Direct2", views: 10, date: "2011-01-02"},
    {stack: "vivid", name: "Direct3", views: 16, date: "2011-01-03"},
    {stack: "vivid", name: "Direct4", views: 23, date: "2011-01-04"},
    {stack: "sparkling", name: "Eventbrite1", views: 23, date: "2011-01-05"},
    {stack: "sparkling", name: "Eventbrite2", views: 16, date: "2011-01-06"},
    {stack: "sparkling", name: "Eventbrite3", views: 10, date: "2011-01-07"},
    {stack: "sparkling", name: "Eventbrite4", views: 0, date: "2011-01-08"},
    {stack: "sunny", name: "Email1", views: 10, date: "2011-01-10"},
    {stack: "sunny", name: "Email2", views: 20, date: "2011-01-06"},
    {stack: "sunny", name: "Email3", views: 26, date: "2011-01-07"},
    {stack: "sunny", name: "Email4", views: 33, date: "2011-01-08"}
```

**Comment by Golodhros** [comment]
Hi @smchae,

There were some errors on the setting of the keys on the tooltip and the class to create the container, the proper values are:
```
    chartTooltip
      .topicLabel('values')
      .dateLabel('key')
      .nameLabel('stack')
      .title('Tooltip title');
  
    tooltipContainer = d3.select('.js-stacked-bar-chart-tooltip-container .metadata-group');
```

**Comment by Golodhros** [comment]
Hi @smchae, did this work for you?

**Comment by smchae** [comment]
@Golodhros Yes it did worked. Sorry for the late follow up.

**Comment by Golodhros** [comment]
thanks, no prob!
