### ISSUE TITLE
[question] How to show the correct ticks when I use the customFormat function

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#490]
{ //block a
              lineChart1.xAxisFormat('custom')
              .xAxisCustomFormat('%dday')
      }

      { //block b
           lineChart1.xTicks(2) 
      }
  
      the performance I expected is use customFormat with block a
      but it shows different with not using the customFormat, it shows
      more ticks which is I don't expect.. 
  
      I try to call the xTicks api in block b, but it shows less ticks
      so how to show the same ticks as not using the customFormat model?

code:

https://codepen.io/Dieber/pen/opJZGq

**Comment by Golodhros** [comment]
Hi @Dieber , thanks for the issue!

I am not sure to understand you question, but regarding the xTicks, those are only applied when the format is 'custom'. They are also 'approximate', as D3 doesn't allow us to specify a fixed number of ticks, just an approximate number.

**Comment by Dieber** [comment]
@Golodhros Thanks for your quick response..again:)


![fce 4 tt qjc7 2 qmuo87](https://user-images.githubusercontent.com/17017234/35203095-55d5f148-ff61-11e7-8f11-adb9b1d3374d.png)
as you can see, this performance is wierd,

I dont' want that shows the ticks every half-day..

but this charts becomes normal when I don't use xAxisCustomFormat function.

so how to make that shows more normal when I use xAxisCustomFormat?

**Comment by Golodhros** [comment]
Hi @Dieber,
I guess the only you could do is to play with different values of the xTicks until you get something  you like:
  lineChart1
       .xAxisFormat('custom')
       .xTicks(NUMBER_OF_DAYS)  //for example, it could need something different
       .xAxisCustomFormat('%dday')

All the fine tuning with axis is pretty tricky, hope this works!

**Comment by Golodhros** [comment]
Hi @Dieber , did this work for you?
