### ISSUE TITLE
Move eslint-loader to devDependencies

### ISSUE THREAD

**Issue by schmkr** [eventbrite/britecharts#506]
In PR #497 `eslint-loader` was added to `dependencies` in package.json. 

## Expected Behavior
When Britecharts is installed as dependency in another project, it should not warn about missing peer dependencies.

## Current Behavior
With ESLint added a dependency, after installing Britecharts, an warning is shown regarding missing peer dependencies:
```
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
```

## Possible Solution
Move `eslint-loader` to `devDependencies`

## Your Environment
* Version used: `2.0.5`

**Comment by Golodhros** [comment]
Thanks for the issue @schmkr!

**Comment by dalerasrorov-eb** [comment]
@schmkr great catch! Should definitely be in `dev`. Thanks for the issue.

**Comment by dalerasrorov-eb** [comment]
Moved it to `dev`, thanks again!

**Comment by schmkr** [comment]
👍 Thanks!!
