### ISSUE TITLE
[BUG] Labels are not cleaned up when updating BarChart data

### ISSUE THREAD

**Issue by mrbongiolo** [eventbrite/britecharts#510]
## Expected Behavior
When using `.enableLabels(true)` to show a label over the bar it should be cleaned if the chart data is updated.

## Current Behavior
The label is not cleaned, so multiple labels are stacked over each other. Possible introduced by myself when fixing #463.

## Possible Solution
Remove current labels before drawing the new ones on `drawLabels`.

**Comment by mrbongiolo** [comment]
I'll add a PR for this today or tomorrow.

**Comment by Golodhros** [comment]
Awesome @mrbongiolo ! Thanks for catching this one!!

**Comment by dalerasrorov-eb** [comment]
Thanks for opening the issue! Fixed in #517
