### ISSUE TITLE
Add Group Ordering function to the Grouped Bar Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#511]
## Expected Behavior

We should allow the ordering of the groups on the group bar chart or disabling the current ordering so that it uses the ordering in the data.

## Current Behavior

From a request on https://github.com/eventbrite/britecharts/issues/303, the user is trying to have a group bar chart by days and getting this ordering instead:
"monday, tuesday, thursday, friday, saturday, sunday, wednesday"

## Possible Solution

We could add an ordering function for the groups on the group bar chart or disabling the current ordering so that it uses the ordering in the data.

**Comment by ISMAELMARTINEZ** [comment]
Hi,
https://codepen.io/ismaelmartinez/pen/yvbWYa

This seems to be related to the order the elements are inserted the 1st time. 

Probably can be close as:
* Right order can be provided by providing the data in order
* Another workaround could be to populate the chart with the order but empty elements.

Thanks!

**Comment by Golodhros** [comment]
Hmm... Maybe this is a non issue?

I just saw that your data has the wednesday of the first week in the wrong position. I changed it and it worked as expected, see https://codepen.io/Britecharts/pen/OQgXLN

Let me know if that solves it.

**Comment by ISMAELMARTINEZ** [comment]
Hi, 

Yeah, you can close it. As I mention in my comment it is not really an issue, just an inconsistency between the different charts. Some do order the data and other do not. 

I, personally, prefer the later.

Close it!

Ta

**Comment by Golodhros** [comment]
Cool!
Thanks for the issue anyways @ISMAELMARTINEZ !
