### ISSUE TITLE
Add .yAxisLabel() to grouped and stacked bar charts and stacked area chart

### ISSUE THREAD

**Issue by faulkiebear** [eventbrite/britecharts#514]
## Summary:
I'm using a groupedbar chart and would like to set a y axis label but this isn't a valid method on this type of chart. Neither is it valid on any other type of graph except for two mentioned above.
Is this intentional behavior or has it just not been implemented yet?

**Comment by Golodhros** [comment]
Hi @faulkiebear, thanks for the issue!

It hasn't been implemented yet! For some of the issues we wait until our users need them, we don't want to overcomplicate things!

I will transform this ticket into a feature proposal for the grouped bar chart, do you need it somewhere else?

**Comment by dalerasrorov-eb** [comment]
@faulkiebear thanks for the issue. We added `yAxisLabel` and `yAxisLabelOffset` methods to `stackedArea`, `stackedBar`, and `groupedBar` charts. Let us know if you have any issue with those in a new issue.
