### ISSUE TITLE
Provide accessor for yAxisLabelPadding

### ISSUE THREAD

**Issue by bratter** [eventbrite/britecharts#524]
(Great library by the way!) 
Feature request to add accessor for yAxisLabelPadding.

## Expected Behavior
Y axis labels do not overlap with the tick labels.

## Current Behavior
My focus was on line, but will apply to all charts with yAxisLabelPadding property.

## Possible Solution
Add accessor for existing yAxisLabelPadding property. I am aware it adds more methods to the API, but this is one that I think is necessary. Happy to do a PR if you are interested.

## Steps to Reproduce
<https://codepen.io/bratter/pen/aqjQVM/> (see the chart on the right, one on the left is for another issue).

## Your Environment
* Version used: 2.5.1
* Browser Name and version: Chrome 63

**Comment by Golodhros** [comment]
Thanks @bratter , that makes a lot of sense!

**Comment by bratter** [comment]
Thanks, super fast! Wondering about the same behavior in the other charts (I think called yAxisLabelOffset elsewhere)? But perhaps best dealt with my larger comment about consistency in #527 if that is something you are interested in looking at.

Cheers!

**Comment by dalerasrorov-eb** [comment]
Thanks for opening the issue @bratter, the `yAxisLabelOffset` does similar thing for other charts, we may need to think about renaming to one single method. Will take a look at #527, thanks!
