### ISSUE TITLE
Change behavior of buildAxis method to not automaticall constrain yTicks

### ISSUE THREAD

**Issue by bratter** [eventbrite/britecharts#526]
The buildAxis method in line chart constrains the yTick count, but I think it would be better if it didn't.

## Expected Behavior
See [codepen](https://codepen.io/bratter/pen/aqjQVM/) for example. I'd expect the graph on the left to look the same as the graph on the right, but show ticks on 10%, 20%, 30%. However it doesn't because the domain of [0.1, 0.3] causes the tick count to be reduced to 1 from the default 5 automatically.

## Current Behavior
In line charts, when the domain of the yScale _in whole numbers_ is less than the yTickNumber (5 by default) the buildAxis method truncates the number of ticks to the domain extent. 

## Possible Solution
While I can understand the use case of a domain extent that is expected to be > 5 not vanishing down to nothing if data happens to be small, I think this is quite restrictive. Two potential solutions:

* Remove the yTickNumber stuff in buildAxis and revert to the d3 default
* Add an accessor to control the min and max extent (more complex, but gives ability to not crunch axes) - you could call this yExtentBounds for instance.

I'd go for the default behavior for simplicity. Happy to do PR.

## Steps to Reproduce
<https://codepen.io/bratter/pen/aqjQVM/>.

## Context
I was trying to display data as percentages on a line chart, but the yTicks were collapsing to 1. There are many use cases where the natural domain of the result is not whole numbers (percentages just being one of them)).

## Your Environment

* Version used: 2.5.1
* Browser Name and version: Chrome 63

**Comment by Golodhros** [comment]
I @bratter , thanks for the issue!!

I will check this with more time, I think there was a reason for it, but can't recall it off the top of my head. I will get back to you soon.

**Comment by Golodhros** [comment]
Hi @bratter, 
Just checked that logic and you are right, it is not working properly and overall it doesn't make a lot of sense. I know we added it to precisely deal with small value ranges, but obviously, it wasn't performing.

Changed in https://github.com/eventbrite/britecharts/pull/530

Thanks a lot, and good call!

**Comment by bratter** [comment]
Thanks! No problems.
