### ISSUE TITLE
Hidden charts don't render when un-hidden

### ISSUE THREAD

**Issue by hisnameisjimmy** [eventbrite/britecharts#547]
If I have a chart's container hidden, then make it un-hidden, the chart does not render. 

See this JSBin: http://jsbin.com/yofibum/edit?html,css,js,output

Removing the 'hidden' class via jquery/javascript does not render the chart. If you remove the hidden class in the html and cause a re-render via jsbin, the chart renders correctly.

## Expected Behavior
Hidden classes shouldn't affect chart rendering.

## Current Behavior
Hidden classes prevent chart rendering.

## Possible Solution
Not sure best solution, but perhaps a workaround is that on unhide, I could update chart rendering. Maybe something similar to recommendations for responsiveness.

## Steps to Reproduce (for bugs)
See this JSBin: http://jsbin.com/yofibum/edit?html,css,js,output

1. Add a hidden css class where the result is display: none
2. Remove the class via jquery/javascript
3. Weep

**Comment by hisnameisjimmy** [comment]
My solution was to copy out of one of your demo pages your redraw code:

```
    let redrawCharts = function(){
        d3Selection.selectAll('.bar-chart').remove();
        createRaceBarChart();
    };

    $('.js-nav-reports-button').on('click', function () {
        redrawCharts();
    });
```

This did the job for me, but it might be nice to have this documented.

**Comment by hisnameisjimmy** [comment]
Hi @bratter, that might be a bit too sophisticated for me, I'm just kinda hacking away at the code here. I ultimately have a child-like understanding of what I'm doing.

In addition, I noticed the negative width rectangle errors as well, but just assumed I was doing something stupid (as is common).

**Comment by hisnameisjimmy** [comment]
Also, I just wanted to say, thank you so much. This is such a highly polished and design centric graph library. If you guys made this easier to approach for noobs/hackers, I think you could get pretty significant adoption. Right now your docs assume a pretty decent level of sophistication, and I think (as noted by my other PR), that making stupid simple examples that people like me could pick up and implement within 20 minutes (or less) would really increase your audience. That may be less than desired, considering the issues that people might bring up, but who doesn't want their library to get used?

**Comment by bratter** [comment]
Yeah, the EB team have done quite a good job, haven't they? That's why I started to contribute (a little)  to this project.

Your easiest solution to this specific problem would just be set a specific width for the chart. All you'd need to do is replace the containerWidth variable in the `.width(containerWidth)` line with a number like you've done for height a couple of lines below.

**Comment by Golodhros** [comment]
Thanks @hisnameisjimmy and @bratter!

It is one of our favorite moments when we discover that people is having a good time using our library! 

@hisnameisjimmy, we would really love to make Britecharts easier to approach, it is one of our main goals, along with allowing D3 developers to write structured charts. We agree our demos need some work, and that we need a better tutorial to get people started and have Britecharts installed without problems. We will work on it, promised!

@bratter, thanks a lot for chiming in and helping other users with their issues, it helps us a lot and feels great to have a community around Britechartrs!
