### ISSUE TITLE
Display Tooltip outside of Chart

### ISSUE THREAD

**Issue by hisnameisjimmy** [eventbrite/britecharts#549]
Is it possible to display the tooltip outside of the `'.line-chart  .metadata-group'` classes?

I'm trying to do this here, and running into errors: http://jsbin.com/quqipiy/edit?html,js,console,output

It _almost_ works, but doesn't output the actual value, which is really all I want (and the date).

This would ideally allow me to show tooltip-like functionality in any situation where space was a significant constraint.

## Expected Behavior
Date and Value should be shown

## Current Behavior
Only date is shown

## Steps to Reproduce (for bugs)
http://jsbin.com/quqipiy/edit?html,js,console,output

## Context
In limited spaces, it would be useful to output chart values to another location/div to allow flexibility in revealing chart details.

**Comment by Golodhros** [comment]
Hi @hisnameisjimmy, thanks for the question!

Yes, you can do anything with the information you get from customMouseOver/Out/Move.
In general, those handlers will give you:
 function(e, d, [x, y]){}

where e is the event, d is the datapoint you are hovering and x and y the position of the mouse in that moment. Probably the datapoint will have the data you need, along with the date and any extra info you are passing to the chart.

You can use that information to update any other element. You don't need to use a tooltip at all.

**Comment by hisnameisjimmy** [comment]
Thanks for getting back @Golodhros, not to be greedy, but is there anyway you could show me an example of this?

**Comment by Golodhros** [comment]
Sure, no problem!
It will be similar to what we do in the brush chart demo: https://github.com/eventbrite/britecharts/blob/master/demos/demo-brush.js but instead of using brushStart/End you will use the mouseOver/mouseMove events.
