### ISSUE TITLE
Putting y-axis labels on top of horizontal charts

### ISSUE THREAD

**Issue by hisnameisjimmy** [eventbrite/britecharts#550]
I would like to lay the y-axis labels on top of horizontal charts to take advantage of the space that I have to display them. However, you don't have direct options to do this. If you remove margin, all the y-axis labels disappear to overflow states. Further, the only way to set the text attribute is via jquery (at least in an easy, direct way for me). 

http://jsbin.com/nunozaz/edit?html,css,js,output

In this example, if you increase the margins the names will appear, but this is overall hacky. Further, the chart ends up pushed over to the right significantly.

## Expected Behavior
There should be a way to lay labels on top of horizontal bar charts.

## Current Behavior
No ability to do this

## Context
Limited space requires creative solutions. Putting labels on top of horizontal graphs allows you to take advantage of widths as small as 285px.

**Comment by Golodhros** [comment]
Hi @hisnameisjimmy, thanks for the question!

I am not sure to understand your requirements. What do you mean by putting the labels on top of the bars? You mean the labels that show the values of each chart or the ones of each of the charts?

**Comment by bratter** [comment]
I think this is what he is after:
![image](https://user-images.githubusercontent.com/10243813/37256347-45bb23d2-2527-11e8-8e0e-a7a15e8b640b.png)

Is that right @hisnameisjimmy? 

I have a couple of thoughts:
* It's not at all hacky to change the margins - doing so to make your chart look good is a core part of the d3 reusable chart paradigm
* What you are after is quite an edge case, so unlikely to be worth building explicitly into a library, however it is easy enough to layer your own logic on top if you need to (see below)
* Generally you should not use jQuery and d3 together - lot of overhead for duplicate functionality - in fact, you can avoid jQuery and put the tick labels where you want in one line of d3 (see below)

So I think to get what you want, you just need to replace the last line in your bin with the following:
`d3.select('.y-axis-group.axis').attr('text-anchor', 'start').attr('transform', 'translate(5, 0)');`

Cheers,
Brendan

**Comment by hisnameisjimmy** [comment]
@bratter This is exactly what I was looking for, thank you for this! Also thank you for the insight on d3 select, I'm not really familiar with d3 so I just leaned on an easy jquery solution.

**Comment by bratter** [comment]
No problems @hisnameisjimmy. The d3 selection and data binding system is both incredibly powerful and mind bending!
