### ISSUE TITLE
Donut chart with Lines and Labels

### ISSUE THREAD

**Issue by fireworks2005** [eventbrite/britecharts#552]
Is possible to convert donut chart to a donut chart with lines and outside labels  (refer to link)? 

<img width="654" alt="pie_charts_labels_-_bl_ocks_org" src="https://user-images.githubusercontent.com/190833/37293120-b3537e28-25cf-11e8-8cbd-e86169ba7532.png">

http://bl.ocks.org/dbuezas/9306799

How to do so ?

**Comment by Golodhros** [comment]
Hi @fireworks2005, thanks for the question!

Not at the moment. I could add this as a proposal though.
