### ISSUE TITLE
The margin API method should be more flexible

### ISSUE THREAD

**Issue by DalerAsrorov** [eventbrite/britecharts#556]
Charts break if one of the margins is not specified.

```       
 barChart
     .margin({
         left: 120,
         right: 20,
         top: 20,
         bottom: 20
     })
```
The chart doesn't render and shows errors in console (see screenshot).

## Expected Behavior
Should be able to pass a specific margin position and still render the chart, setting the non-specified margin positions as default.

## Current Behavior
If one of the margins is not set, the chart doesn't render.

## Possible Solution
A margin for the positions not specified by the user should be assigned to default value. This will render the chart and apply the margins to positions that the user wants without breaking charts.

## Steps to Reproduce (for bugs)

Create a simple Bar chart and specify only some margins, ex:
```        
barChart
            .width(500)
            .height(300)
            .margin({
                left: 120,
                top: 20,
                // missing 'right' and 'bottom'
            })
```

## Screenshots (if appropriate):
<img width="965" alt="screen shot 2018-03-12 at 9 46 41 pm" src="https://user-images.githubusercontent.com/9118852/37323134-e6f0f6d8-263e-11e8-8894-3e2ed1b062b5.png">

## Context
I think it is a good idea for the user to decide if the user wants to keep the margins at specific position and instead set positions that the user wishes.

## Your Environment
Chrome

**Comment by Golodhros** [comment]
Thanks @DalerAsrorov, this makes a lot of sense!

Maybe instead of assigning the margin object, we can do a spread of the newly passed margin over the previous version (the default at the beginning) and that will be it!

Good call!
