### ISSUE TITLE
Brush Chart: customBrushEnd event not dispatched when clearing selection

### ISSUE THREAD

**Issue by namoscato** [eventbrite/britecharts#576]
## Expected Behavior

When clearing the selection of the Brush Chart (i.e. clicking on the chart without dragging), the `customBrushEnd` event should be dispatched, enabling external bindings to react to the change.

Related to this issue but a lower priority from my perspective: Is there a reason why the events dispatched by this chart do not match the [`d3-brush` event types](https://github.com/d3/d3-brush#brush_on) (`start`, `brush`, and `end`)? The current `customBrushStart` event seems to more closely resemble `brush` but is similarly not called on _start_ (i.e. mousedown).

## Current Behavior

Currently, `customBrushEnd` is not dispatched when the selection is empty:

https://github.com/eventbrite/britecharts/blob/84d1265a8163aab8e8f9b975e77c7bb1ebd1b650/src/charts/brush.js#L373

## Possible Solution

I think it would make sense to pass:

```javascript
[null, null]
```

as an argument to registered `customBrushEnd ` handlers, but I am open to suggestions.

This would be a minor breaking change, so I am not sure how that is handled.

## Steps to Reproduce (for bugs)

1. Click on brush chart without dragging
2. `customBrushEnd` event is _not_ dispatched

**Comment by Golodhros** [comment]
Hi @namoscato, thanks for opening the issue!

Interesting, we probably didn't think that was necessary. Out of curiosity, could you tell us more about your use case?

Regarding the event names, we are ultimately wrapping the behavior of D3, but simplifying it as much as we can. The naming could be discussed, although a change would need to be library-wide, but I still think not naming them the same as D3's is a good idea, as they don't map one to one.

That said, we are open to suggestions. We haven't had the occasion to work with the brush in any of our production code, so it is not the most 'battle-tested' charts.

Thanks a lot!

**Comment by namoscato** [comment]
Thanks for the reply @Golodhros!

I'm ultimately trying to couple this chart with date picker form controls, using the chart as an alternative means to select two dates. The UI will probably look something like:

<img width="590" alt="screen shot 2018-04-01 at 9 28 31 am" src="https://user-images.githubusercontent.com/847532/38173618-8870db22-358f-11e8-969f-140d47c6059b.png">

In my context, it is certainly valid to _not_ select either date, effectively not applying that filter. Thus, the ability to clear these form control values when clearing the brush selection would be ideal.

Also, I'm cool with the current event names; no worries on that front.
