### ISSUE TITLE
ScatterPlot : Only left half of vertical grid lines are rendered

### ISSUE THREAD

**Issue by HeikoMueller** [eventbrite/britecharts#587]
Hi,
I am trying to render a basic scatter plot. I assign width(containerWidth) and grid('full') and I leave all other properties to its default values. The dataset is copy/pasted from data.js. 

## Expected Behavior
Equally distributed gutter lines (grid) appear horizontially and vertically, covering the whole range of the tow dimensions

## Current Behavior
While the horizontial lines are rendered correctly, only the left half of the vertical grid lines get renderd. The right half of the chart remains without vertical grid lines. If I change the .grid property from 'fully' to 'vertical', the problem remains : Only the left half of vertical lines are renderd. 

## Steps to Reproduce
see above

## Screenshot
![bildschirmfoto 2018-04-05 um 14 18 46](https://user-images.githubusercontent.com/2492274/38365880-4071d82e-38de-11e8-8d1e-7eed8ded59ae.png)

## My Environment
* Version used: Britecharts 2.8.0, installed via NPM
* Firfox 59.02, Safari 11.03
* Operating System macOS High Sierra 10.13.3

Best,
Heiko

**Comment by Golodhros** [comment]
Hi @HeikoMueller, thanks for opening this issue!

It definitely looks like a bug. Could you try to set up a codepen using this template: https://codepen.io/Britecharts/pen/PRyZNy?editors=1010#0 ?

Thanks a lot!

**Comment by DalerAsrorov** [comment]
Hi @HeikoMueller ! Apologize for the bug, the scatter plot is actively being improved. Thanks a lot for opening the issue, will look into this!

**Comment by HeikoMueller** [comment]
Hi @Golodhros , thanks for your quick reply. I am not sure how to properly include node modules in codepen. This is the code I used:

`'use strict';

const d3Selection = require('d3-selection');
const scatterPlot = require('britecharts/dist/umd/scatterPlot.min');

var instances = {};

function init(id, selector, data) {

    const grid = d3Selection.select(selector),
          dataset = [
                {
                    name: 'topic',
                    x: 123,
                    y: 24,
                },
                {
                    name: 'topic1',
                    x: 53,
                    y: 31,
                },
                {
                    name: 'topic2',
                    x: 631,
                    y: 321,
                },
                {
                    name: 'topic1',
                    x: 231,
                    y: 111,
                }
            ];

    
    let wrapper,
        scatterPlotChart,
        chartContainer,
        containerWidth;

    const redraw = function() {
        wrapper.remove();
        createScatterPlotChart(false);
    }
    
    const createScatterPlotChart = function(animated) {
        scatterPlotChart = scatterPlot();

        wrapper = grid.append('div')
        chartContainer = wrapper.append('div')
        containerWidth = chartContainer.node() ? chartContainer.node().getBoundingClientRect().width : false;
        
        scatterPlotChart
            .width(containerWidth)
            .grid('full');
            
        chartContainer.datum(dataset).call(scatterPlotChart);
    }
    
    window.addEventListener('resize', redraw);

    return {
        createChart: createScatterPlotChart
    };
}
    
exports.getInstance = function(id, selector, data) {
    if (typeof id === 'undefined') {
        return null;    
    }
    if (!instances.hasOwnProperty(id)) {
        instances[id] = init(id, selector, data);
    }
    return instances[id];
};`

Hope that helps
Best, Heiko

**Comment by HeikoMueller** [comment]
Hi @DalerAsrorov , one suggestion though unrelated to this issue , just because you mentioned that scatter plot is in active development : I'd fancy the possibility to fix the x and y axis crossing point at the center, meaning that both range for example from -10 to +10 . In this way, the scatter plot became a proper 4-field matrix. Also, the possibility to label not the four fields seperately would be of great advantage...

**Comment by dalerasrorov-eb** [comment]
@HeikoMueller thanks a lot for the suggestion. This make sense. I would imagine a sinusoidal graph would need a fixed crossing point at the center. I will work on it ASAP.

**Comment by dalerasrorov-eb** [comment]
@HeikoMueller Submitted the change and released it. Let us know if you have any issue. I would be happy to create another issue for range `-10` between `+10`.

**Comment by HeikoMueller** [comment]
@DalerAsrorov Hey man, super cool! Fastest bug fix ever :) And I am happy that you like the idea of having a centered axes crossing point for the 4-field matrix. Nice work!
