### ISSUE TITLE
Feature request - trendline for Scatter Plot

### ISSUE THREAD

**Issue by dalerasrorov-eb** [eventbrite/britecharts#593]
## Expected Behavior
Should draw a trend line if user wants to see it (via some API function most likely).

## Current Behavior

No trendlines available yet

## Possible Solution

Calculate trendline by calculating slope and y-intercept based on data points. Would need more detailed explanation, not exactly sure myself.

## Context

Relevant feature for scatter plots

**Comment by bratter** [comment]
The API function (probably is the simplest way to do it) could then simply be `hasTrendline(hasTrendline: boolean)`. The x-extent could then be calculated from the dataset directly using `d3.extent(data, d => d.x)`. The one complication that may be worth having is an optional parameter or overloaded form that allows a custom x-extent. Then calculate y points using the following (or similar) helper function:

```
function linest(data) {
  let n = 0, x = 0, y = 0, xy = 0, x2 = 0, y2 = 0;

  data.forEach(d => {
    n++;
    x += d.x;
    y += d.y;
    xy += d.x * d.y;
    x2 += d.x * d.x;
    y2 += d.y * d.y;
  });
  
  const denominator = (n * x2) - (x * x);
  const intercept = ((y * x2) - (x * xy)) / denominator;
  const slope = ((n * xy) - (x * y)) / denominator;
  
  return { intercept, slope };
}
```

**Comment by Golodhros** [comment]
Looks great! Is that a usual calculation to find trends?

**Comment by bratter** [comment]
Yeah, that is just my super quick implementation of the standard least squares regression formula. There may be a more efficient way to do it, but I didn't investigate.

**Comment by Golodhros** [comment]
Great! Thanks for this!!

**Comment by dalerasrorov-eb** [comment]
Hi @bratter ! Thanks a lot for proposing the formula for calculation. I would appreciate your review in this PR: https://github.com/eventbrite/britecharts/pull/621

**Comment by bratter** [comment]
FWIW I looked quickly at the code and looks fine. Two suggestions though: 
1. Might be worthwhile having a test or so to check the correctness of the regression formula.
2. Stylistically, why not put the math in a helper function and out of the main code?
Cheers!

**Comment by dalerasrorov-eb** [comment]
@bratter thanks for reviewing! We could separate calculations from the main code - I just didn't see the case for the linear regression calculation for other charts other than Scatter Plot, but I can see that it will keep code cleaner. It would also be easier to write tests for the function since currently it's private function but if it's in a helper, we could write tests for validation of the calculations in helper tests. That makes sense. Thanks a lot for your great suggestions!
