### ISSUE TITLE
No way to provide an alternative formatter for numbers

### ISSUE THREAD

**Issue by adrm** [eventbrite/britecharts#594]
## Expected Behavior

I would like to have some way to use any function to format numbers in tooltips or mini-tooltips. It would suffice to be able to set the valueFormatter property. I have not found a way to do this. Is it? Would you accept a pull request making this property available to the user of the library?

## Current Behavior

No way to format numbers without using d3-format.

## Possible Solution

Make valueFormatter accessible.

## Context

I am using this library in Angular app and I would like the Angular function (pipe) that I use to format every other number in the app to be used also in tooltips inside britecharts.

**Comment by Golodhros** [comment]
Hi @adrm, thanks for the issue!

I see, we didn't think on that use case. I guess it makes sense and we could add it to those components.

If you are so kind to create a PR for both Tooltip and Mini-tooltip, that would be awesome!

**Comment by adrm** [comment]
Perfect, I'm on it. I wanted to confirm with you that you are ok with this feature before implementing.
