### ISSUE TITLE
Trouble with responsive line chart

### ISSUE THREAD

**Issue by DamonCool** [eventbrite/britecharts#606]
First off, thanks for the great library.  I'm looking forward to using it on a new project!

## Expected Behavior
I'm trying to get the responsive charts working.  It seems that the axis is scaling fine, but the lines don't seem to redraw.  

## Current Behavior
When I resize the window the axis grows or shrinks correctly, but the lines stay the original width.

## Possible Solution
I'm sure I missed something.

## Steps to Reproduce (for bugs)
```
        <script>
            // Line
            var lineChart = britecharts.line();
            var tooltip = britecharts.tooltip();
            var lineData = data;

            lineChart
                  .margin({
                      top: 60,
                      bottom: 50,
                      left: 100,
                      right: 20
                  })
                  .lineCurve('cardinal')
                  .grid('full')
                  // .width(init_ContainerWidth)
                  .height(350)
                  .on('customMouseOver', tooltip.show)
                  .on('customMouseMove', tooltip.update)
                  .on('customMouseOut', tooltip.hide);

              tooltip
                  .title('.');

              d3.select('.line').datum(lineData).call(lineChart);

              d3.select('.line .metadata-group .vertical-marker-container').datum([]).call(tooltip)

              const redrawChart = () => {
                  let container = d3.select('.line');
                  let newContainerWidth = container.node() ? container.node().getBoundingClientRect().width : false;

                  // Setting the new width on the chart
                  lineChart.width(newContainerWidth);

                  // Rendering the chart and line again
                  container.datum(lineData).call(lineChart);
                  d3.select('.line .metadata-group .vertical-marker-container').datum([]).call(tooltip)
              };

              const throttledRedraw =  _.throttle(redrawChart, 200);

              window.addEventListener("resize", throttledRedraw);
        </script>
```

## Screenshots (if appropriate):
Initial Load:
<img width="1033" alt="at_demo_-_britecharts" src="https://user-images.githubusercontent.com/2454397/39949088-a45c02f4-552d-11e8-989a-ff6863e318e3.png">
After making the window wider:
<img width="1381" alt="at_demo_-_britecharts" src="https://user-images.githubusercontent.com/2454397/39949158-f4e17010-552d-11e8-9bb9-ee78e4626f77.png">

## Context
One of the key requirements for my project is responsive and mobile friendly UI.

## Your Environment
Version 65.0.3325.181 (Official Build) (64-bit)
Mac OS High Sierra

**Comment by dalerasrorov-eb** [comment]
Would be very helpful to have a codepen for this one. Could you add it? Will be easier to reproduce and have either a fix (if it's a bug) or suggestion

**Comment by DamonCool** [comment]
Here's a codepen.  Let me know if you have any questions.
https://codepen.io/damoncool/pen/gzQWdx

**Comment by mhammo** [comment]
Hi, I had this problem on my end too.

It seems to be to do with the .merge() in the drawLines() method of line.js, I moved the .merge() to further down the method chain, and that seemed to fix it for me (haven't had chance to test it fully yet though).

```
paths = lines.enter()
              .append('g')
                .attr('class', 'topic')
              .append('path')
                .attr('class', 'line')
                .merge(lines)
                .attr('id', ({topic}) => topic)
                .attr('d', ({dates}) => topicLine(dates))
                .style('stroke', (d) => (
                    dataByTopic.length === 1 ? `url(#${lineGradientId})` : getLineColor(d)
                ));
```

**Comment by Golodhros** [comment]
Looks like #657 solved this issue!
