### ISSUE TITLE
Support for gradients on bar chart

### ISSUE THREAD

**Issue by ronvenna** [eventbrite/britecharts#608]
I am using the horizontal bar chart and want to fill the bars with a gradient. I see you have support for gradients on line chart but not bar chart. Do you have any advice on if this is achievable?

## Expected Behavior
Something like a `colorGradient` option would be nice 
```
barChart
    .colorGradient(['#39C7EA', '#4CDCBA']) // pass in a start color to end color
    .width(500)
    .height(300);
```

## Current Behavior
This would be an additional field compared to the current `colorSchema` field
```
barChart
    .colorSchema(['#39C7EA', '#4CDCBA'])
    .width(500)
    .height(300);
```

## Possible Solution
Listed my solution above in the Expected Behavior section

## Context
Mostly for styling not a big issue but would be a nice to have. Since you have this for linecharts it only makes sense to make this available to all charts to un-fragment this feature. 

## Your Environment
* Version used: 2.8.6
* Browser Name and version: Chrome 66
* Operating System and version: Mac OSX 10.13
* Link to your project or codepen: Private project

**Comment by dalerasrorov-eb** [comment]
Hi @ronvenna ! Thanks for creating the issue! This sounds interesting, I marked it as a proposal and will work on it some time to see if it's plausible (i.e. looks good to add it)

**Comment by dalerasrorov-eb** [comment]
<img width="631" alt="screen shot 2018-05-18 at 1 05 36 am" src="https://user-images.githubusercontent.com/31934144/40216873-ae4e346c-5a37-11e8-8fb8-b53941da389b.png">
I started some work. Des this look like something you would want? It's orange to pink gradient

**Comment by ronvenna** [comment]
@dalerasrorov-eb yes this looks great! I appreciate the fast response.

**Comment by dalerasrorov-eb** [comment]
No problem @ronvenna ! This PR got merged: https://github.com/eventbrite/britecharts/pull/609 - should be available next release
