### ISSUE TITLE
Add Annotations to Donut Chart and other charts

### ISSUE THREAD

**Issue by Robiig** [eventbrite/britecharts#614]
Hi ! First, thank you very much for this great librarie! 👍 
I open this issue because I was wondering if it could be possible to add the legend of the donut chart in a better way than just under it.

## Expected Behavior
The goal is to see more clearly the data, without moving the mouse over the donut

## Current Behavior
The legend is just under the chart now (I think)

## Possible Solution
Check d3pie.js. With it it's possible to add the legend all around the donut with the percentage on each slice. 
I don't have a very beautifull english so maybe that one image could sum up my needs. ;)

## Screenshots (if appropriate):
![pie](https://user-images.githubusercontent.com/11925424/40419607-23d21576-5e86-11e8-965d-bd562267904b.PNG)

sincerely yours :)

**Comment by Golodhros** [comment]
Hi @Robiig, thanks for opening this issue!

I understand. We usually call those labels + lines 'annotations'. We will definitely want to have an annotation solution integrated into Britecharts at some point. 

I don't know if the right solution would be to integrate http://d3-annotation.susielu.com/ or build our own helpers. We would need to do some research on it.

As a workaround, I would recommend you to use a bar chart. The example you show is something we don't suggest to do, as it is noisy and not usable. We recommend limiting the use of donut charts to, at the most, three slices. More than that would call for using a bar chart.

I will transform this issue in a feature proposal for Annotations. 

Thanks a lot!

**Comment by Golodhros** [comment]
Oh, this was also talked about in https://github.com/eventbrite/britecharts/issues/473. Will close this for now and move the conversation there.

**Comment by Robiig** [comment]
Thank you for the response. I really appreciate you taking the time to write all that. :)
