### ISSUE TITLE
Create semi-donut chart

### ISSUE THREAD

**Issue by Robiig** [eventbrite/britecharts#620]
Hi ! 
I've a question quiet similar as  [605](https://github.com/eventbrite/britecharts/issues/605)
Is this possible to implement a semi donut chart as the screenshot below ?

![demidonut](https://user-images.githubusercontent.com/11925424/40547094-3ad64aa6-6031-11e8-9b39-355003e14739.PNG)

sincerely yours :)

**Comment by Golodhros** [comment]
Hi @Robiig, thanks for opening this issue!

That is not an option at the moment. I could transform this into a feature proposal and see if there is enough support from the community to create this chart.

In the meanwhile, if you really need it, I would suggest to fork Britecharts and create a copy of the donut chart, modifying it so it looks like this one.

Thanks a lot!

**Comment by DalerAsrorov** [comment]
Hi @Robiig, just to add to what Marcos said, there is multiple proposals of different types of Donut charts among issues/proposals. To give you more context, our next closest new charts will be Heatmap and maybe Sankey. We should decide on what type of Donut chart would be most relevant and supported. We will keep this as proposal and if it gets enough support we can build it. In the meantime, hope you can also use the existing charts to help you visualize data you need. Cheers!
