### ISSUE TITLE
Stacked bar chart not rendering all bars when `isAnimated(true)`

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [eventbrite/britecharts#624]
Some bars of the stacked bar chart are not being rendered, this is only an issue when `isAnimated(true)`

## Expected Behavior
All groups should have displayed bars:
![image](https://user-images.githubusercontent.com/8518288/41370077-df393bc2-6f03-11e8-81ff-e4c5e9971213.png)

## Current Behavior
In the figure below, "group 8" should have a bar:
![image](https://user-images.githubusercontent.com/8518288/41369963-960ad12c-6f03-11e8-9fcd-a536cb320708.png)

## Possible Solution
Dunno

## Steps to Reproduce (for bugs)
[codepen](https://codepen.io/constantinoschillebeeckx/pen/WyOJOW)

**Comment by Golodhros** [comment]
Hi @ConstantinoSchillebeeckx, thanks for reporting this bug!

It is definitely a bug. The funny thing is that the tooltip works perfectly, indicating the right data.

Thanks again!

**Comment by dalerasrorov-eb** [comment]
Thanks @ConstantinoSchillebeeckx ! Trying to reproduce it via local dev environment now. Hope to get back to you ASAP
