### ISSUE TITLE
Format x-axis dates on Stacked Area chart

### ISSUE THREAD

**Issue by Hypersapien** [eventbrite/britecharts#631]
## Expected Behavior
Need a way to format the dates in the x-axis of a stacked area chart in some way other than the default

## Current Behavior
The dates currently display as "D MMM". I'm feeding in monthly data, so I want the dates to format as "MMM YYYY"

**Comment by Golodhros** [comment]
Hi @Hypersapien, thanks for your question!

You can use [xAxisCustomFormat](http://eventbrite.github.io/britecharts/module-Stacked-area.html#.xAxisCustomFormat__anchor) to pass any [d3 format](https://github.com/d3/d3-3.x-api-reference/blob/master/Time-Formatting.md) into the chart. Remember to first set xAxisFormat to 'custom' first.

**Comment by Golodhros** [comment]
Hi @Hypersapien, did this work for you?

**Comment by Hypersapien** [comment]
I can't seem to get it to work. I put in .xAxisCustomFormat('%m/%Y') but it's still displaying the date  as "1 May", "1 Jun" and so on.

**Comment by Golodhros** [comment]
Are you setting .xAxisFormat('custom') too?

**Comment by Golodhros** [comment]
Awesome!
