### ISSUE TITLE
Getting error for Stacked Bar chart: <rect> attribute y: Expected length, "NaN".

### ISSUE THREAD

**Issue by sagardalvi** [eventbrite/britecharts#636]
## Expected Behavior
Either error should be removed from the browser console or pass default 0 to the rectangle generated using d3 code

## Current Behavior
Getting too many errors in the browser console

## Possible Solution
This might be helpful :) 
https://stackoverflow.com/questions/40746319/error-rect-attribute-width-expected-length-nan-and-text-attribute-dx

## Steps to Reproduce (for bugs)
A height of generated SVG is 310
A width of generated SVG is 800

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/13640403/42722419-45e7069c-8769-11e8-9194-493a3e38b03e.png)
![image](https://user-images.githubusercontent.com/13640403/42722422-4fd26caa-8769-11e8-975b-edd52c2f23a6.png)

## Context

Getting too many errors in the browser console results in a bad impact on web page

## Your Environment
* Britechart Version used: 2.9.0
* Browser Name and version: Chrome
* Operating System and version: Mac OS X

**Comment by Golodhros** [comment]
Hi @sagardalvi, thanks for creating this issue!

Could you create a codepen with the context of this bug? You could use this one https://codepen.io/Britecharts/pen/QqaogP as a starting point.

This way we will be able to help you better, thanks!!

**Comment by sagardalvi** [comment]
Here is the example link
https://codepen.io/sagardalvi/pen/bjEZpK 

The primary observation regarding the issue is 
dataset created is as below
[
    {name: "A", value: 0.12, stack:"stack1"},
    {name: "A", value: 0.32, stack:"stack2"},
    {name: "B", value: 0.22, stack:"stack2"},
    {name: "C", value: 0.45,stack:"stack1"},
    {name: "D", value: 0.55,stack:"stack2"},
  ]

For name A we have 2 stacks [stack1 & stack2] But for B, C, D we have given only one stack (either stack1 or stack2) so while rendering it is giving errors on the browser console as shown in below screenshot.

![image](https://user-images.githubusercontent.com/13640403/42750071-8052c24e-8903-11e8-9db8-3ce854e0eae0.png)

**Comment by dalerasrorov-eb** [comment]
Submitted fix, hope it resolves your issues. It will be available next release.

**Comment by sagardalvi** [comment]
@dalerasrorov-eb Thank you for your support.
