### ISSUE TITLE
Add yAxis Formats to Bar and time series charts

### ISSUE THREAD

**Issue by VGawade** [eventbrite/britecharts#645]
Hello @Golodhros, @rpheath, @simonw 

I want to customize the YAxis of the charts.

## Expected Behavior
1. If the API returns the time values the YAxis should show the time returned from the API with "H" string appended next to YAxis values.
2. If the API returns the data in Bytes format the YAxis should render in "GB" format.

## Current Behavior
It is rendering the default YAxis as of now which is not required. The YAxis should be customizable.

Can you please help me with this as I am trying to fix this since couple of weeks but no success.

Thanks,
Vijay

**Comment by VGawade** [comment]
@Golodhros, Is this possible to have a custom YAxis.

**Comment by Golodhros** [comment]
Hi @VGawade, sorry for the delay. Which chart are you using?

**Comment by VGawade** [comment]
hi @Golodhros I am using Four charts from you library.
1. Stacked-Bar
2. Stacked-Area
3. Donut Chart
4. Line Chart

I need to customize the YAxis of all of them according to data retrived from the API.
The data will be in "Bytes" & "Hours" format and the YAxis has to be rendered accordingly.

Please let me know if you need more inputs.

Thanks.

**Comment by Golodhros** [comment]
Hi @VGawade, we aren't supporting yAxisFormats in any of those charts. Also, we probably won't ever have them for the Donut chart.

I will transform this into a feature proposal. In the meanwhile, a workaround I guess would be to add the units in the yAxisLabel.

Thanks!

**Comment by dalerasrorov-eb** [comment]
Hey @VGawade, could you give an example of how you would use it and how y axis of the chart would look like approximately? Sorry it's hard to visualize and understand without usage. Thanks!

**Comment by VGawade** [comment]
Hi @dalerasrorov-eb, Here is how the YAxis should look like when the data is in time and Bytes format.

![chart_in_gb](https://user-images.githubusercontent.com/13359456/42991030-06975862-8c22-11e8-901a-87eb6b60d5bb.jpg)
![chart_in_hours](https://user-images.githubusercontent.com/13359456/42991032-06e38336-8c22-11e8-957f-9093ea0e5efc.jpg)

Please let me know if required more information.

Thanks.

**Comment by dalerasrorov-eb** [comment]
Hi @VGawade ! The feature request is implemented here: https://github.com/eventbrite/britecharts/pull/647
However, due to the fact that this addition should then be copied/integrated over to other charts, it would need more support from the community (since it's a medium-size change that impacts a lot of charts). We will keep this branch alive and merge when the demand is high enough.
One thing you could do is fork the remote branch `feat-ticks-labels` and use this forked branch to add changes to your charts. Thanks a lot!

**Comment by VGawade** [comment]
Hi @dalerasrorov-eb, It is very helpful. Appriciate your help. 

Thanks.

**Comment by dalerasrorov-eb** [comment]
No problem @VGawade - feel free to re-open this issue if something comes up.

**Comment by jjphung** [comment]
Hi, 

I was looking through the source code. How does the ticklabel mb, gb, etc get calculated? I can't seem to find it anywhere. Thank you!

reposted question from: [original comment](https://github.com/eventbrite/britecharts/pull/647)

**Comment by Golodhros** [comment]
Hi @jjphung, 

Have you checked in the feat-ticks-labels branch?

**Comment by jjphung** [comment]
@Golodhros Thanks for replying. No such branch exists anymore. It seems like it was merged into master and deleted, which means it could be somewhere in master branch?

> Have you checked in the feat-ticks-labels branch?

**Comment by Golodhros** [comment]
Oh, I see, bummer!

you can get the code from this change here: https://github.com/eventbrite/britecharts/pull/647/files

if you go ahead add those changes, you should be able to have this feature.

**Comment by jjphung** [comment]
Ah! The feature is there already 👍. It's just that for the calculation of size (mb, gb, etc) for the axis labels, somewhere the conversion is 1000 bytes between the sizes, instead of 1024. Therefore the converted values displayed is slightly off. Perhaps this is a possible bug?

**Comment by Golodhros** [comment]
I see. Is that 1000 constant in our code then?

**Comment by jjphung** [comment]
I wasn't able to find it here. Perhaps I may have missed it somewhere in the codebase. Or maybe a 3rd party library that may have done the conversion.
