### ISSUE TITLE
Export does not work in Internet Explorer

### ISSUE THREAD

**Issue by flacoman91** [eventbrite/britecharts#648]
## Expected Behavior
Clicking the Export button, or using the Export Chart should create an image and download the png of the chart.

## Current Behavior
An error is thrown. "Unable to get property 'replace' of undefined or null reference.

## Steps to Reproduce (for bugs)
1. Using Internet Explorer 11, go to any demo chart such as https://eventbrite.github.io/britecharts/tutorial-bar.html
2. Click on the Export button
3. image is not downloadable and the error appears in the console
4.

## Context
We still have people who use Internet Explorer 11 and Edge as their default browsers and they would not be able to download an image of charts.

## Your Environment
* Version used: 2.9.3
* Browser Name and version: Internet Explorer 11 (11.0.9600.19035)
* Operating System and version: Windows 7

**Comment by Golodhros** [comment]
Hi @flacoman91, thanks for creating this issue!

Yes, we should fix this bug. I guess we haven't stated anywhere, but we are supposed to support IE11.

Thanks again!

**Comment by dalerasrorov-eb** [comment]
Addressed in this PR: https://github.com/eventbrite/britecharts/pull/652
