### ISSUE TITLE
Stacked Area chart colour is not displayed properly 

### ISSUE THREAD

**Issue by sagardalvi** [eventbrite/britecharts#656]
Stacked Area charts color is not displayed properly if we have not provided value for a stack on a particular date
e.g we have 2 stacks and 7 dates values then dataset requires (7 * 2) values.

## Expected Behavior
Chart stacked Colour should display

## Current Behavior
Currently, Library requires a value for all the stacks and for all dates

e.g we have 2 stacks and 7 dates values then dataset requires (7 * 2) values.

## Possible Solution
If we do not provide value for any stack then it should consider 0

## Steps to Reproduce (for bugs)
https://codepen.io/sagardalvi/pen/zLyaYw

For below dataset I donot have value for **Stack1**  on date 2017-02-16. so graph is not showing stacked colour.

```
[
  {
    date: "2017-02-16T00:00:00-08:00",
    name: "Stack2",
    value: 0
  },
  {
    date: "2017-02-17T00:00:00-08:00",
    name: "Stack2",
    value: 1
  },
  {
    date: "2017-02-17T00:00:00-08:00",
    name: "Stack1",
    value: 13
  },
  {
    date: "2017-02-18T00:00:00-08:00",
    name: "Stack1",
    value: 15
  },
  {
    date: "2017-02-18T00:00:00-08:00",
    name: "Stack2",
    value: 1
  },
  {
    date: "2017-02-19T00:00:00-08:00",
    name: "Stack1",
    value: 15
  },
  {
    date: "2017-02-19T00:00:00-08:00",
    name: "Stack2",
    value: 1
  },
  {
    date: "2017-02-20T00:00:00-08:00",
    name: "Stack1",
    value: 15
  },
  {
    date: "2017-02-20T00:00:00-08:00",
    name: "Stack2",
    value: 1
  }
]
```

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/13640403/43943880-c63d547c-9c9a-11e8-8b82-de97a76f24ec.png)

## Context

In my scenario, I am not able to populate the value for the **Stack1**.

In my case Stacks are the usernames, and suppose that user is created on 2017-02-17 so for 2017-02-16, I will not get any information for the user. so the graph is not plotted properly.

Users are increasing day by day so for last date users are always in a higher number, then it is impossible to generate a dataset for all users and for every date (no.of.users * dates)

## Your Environment
* Britechart Version used: 2.9.0
* Browser Name and version: Chrome
* Operating System and version: Mac OS X

**Comment by sagardalvi** [comment]
@Golodhros, the same issue is coming when any stack is not available for any date in the passed dataset
Can you please look into this?

Thanks,
Sagar

**Comment by Golodhros** [comment]
Hi @sagardalvi, thanks for the issue!

I guess that behaviour is expected given the way the internal cleaning functions are made through the library. I am afraid they only do some basic number/string casting.

Sometimes I have thought about extending the functionality of the cleaning functions with some typing, and filling missing entries like your case would be an option. Or it could be a configurable function too.

There are no plans to do this, but you could create a feature proposal about it. In the meantime, you will need to do the data normalization before feeding the chart.

Thanks!
