### ISSUE TITLE
Grouped bar chart does not render if isAnimated is true

### ISSUE THREAD

**Issue by mikerhyssm** [eventbrite/britecharts#658]
If `isAnimated` is set to true on the grouped bar chart the chart does not render at all.

## Expected Behavior
The Grouped bar chart should render with animations.

## Current Behavior
The Grouped bar chart axis render but the bars do not

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/OwYgoL

It looks like the tween function isn't been triggered from within `drawVerticalBars` : https://github.com/eventbrite/britecharts/blob/master/src/charts/grouped-bar.js#L566

## Context
Trying to render the grouped bar chart with animations, can work around without using animations for now but it would be good to have the option :-) 

Happy to submit a fix, but I've not been able to identify why it isn't entering the tween as of yet !

## Your Environment

* Version used: 2.9.2
* Browser Name and version: Chrome 68
* Operating System and version: Mac OSX High Sierra
* Link to your project or codepen: https://codepen.io/anon/pen/OwYgoL

**Comment by Golodhros** [comment]
Hi @mikerhyssm, thanks for creating this issue!

This looks like a bug. It is pretty weird though, it seems that the demo Grouped Bar[http://eventbrite.github.io/britecharts/tutorial-grouped-bar.html] works fine, but your example doesn't.

We will look at it!
Thansk!!

**Comment by mikerhyssm** [comment]
I think the issue is on this line: https://github.com/eventbrite/britecharts/blob/master/src/charts/grouped-bar.js#L584

The current version published to npm `2.9.2`  has `layers[0]` as opposed to `layers` this results in `NaN` and the tween not happening.

I wonder if this will be fixed if the latest version `2.9.4` is published to npm ?

**Comment by dalerasrorov-eb** [comment]
Hey @mikerhyssm - we just updated NPM token and it seems like the publish version is now updated with new changes. The fix should be there, let me know if it's not.

**Comment by mikerhyssm** [comment]
All sorted, thanks for you quick response 🙌
