### ISSUE TITLE
Create a Demo page for the Color schemas

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts#661]
## Expected Behavior
We should provide a demo section to show the different color palettes we support.

## Current Behavior
At this moment, you will need to dive into the code to discover the different color palettes.

## Possible Solution
A demo page for colors?

**Comment by Golodhros** [comment]
I just saw that lyft open sourced a color tool: https://github.com/lyft/coloralgorithm
You can try it in https://www.colorbox.io/

Wouldn't be great to have something like that applying it to a chart!
It could be part of the sandbox too!

**Comment by sennab** [comment]
Fancy! That would be super cool. I'm working on a pretty simple solution though to start for the demo pages :)

**Comment by miglesiasEB** [comment]
Perfect!
