### ISSUE TITLE
Make stacked-area Outline optional

### ISSUE THREAD

**Issue by tgallice** [eventbrite/britecharts#670]
## Expected Behavior
Disable stacked-area outline

## Current Behavior
The stacked-area outline is by default enabled and can not be disabled / removed.

## Possible Solution
Make the outline rendering optional. We can add an option set up by a method like `disableOutline(x bool)` or `hideOutline(x bool)` to handle this.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
An outline was added to the stacked-area which is nice, but this changed the rendering of the stacked-area and It's not possible to go back to the previous style. For my usage, I need to display the stacked-area without the outline

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @tgallice, thanks for the issue!

About this issue, I would simply add a stylesheet rule to hide it:
```
.area-outline {
    display: none;
}
```

Adding a boolean as you suggested wouldn't be hard, but this way we avoid doing anything. Would this work for you?

**Comment by Golodhros** [comment]
Well, it is true you will be drawing elements that you don't need, but unless they are a lot of them it should be fine.

In which way do you think is not flexible?

**Comment by tgallice** [comment]
Sorry for the delay. An option seems much easier to me to use. No need to add a global/precise rule for each graph you have. All the behavior is handled by the config of the graph, insted of a css rule that overrides default ones.

**Comment by Golodhros** [comment]
I see. The API could be something like:
```
stackArea.hasOutline(true/false)
```
With the default set as true.
