### ISSUE TITLE
Bar chart - transition animation still applied when isAnimated is false

### ISSUE THREAD

**Issue by mikerhyssm** [eventbrite/britecharts#671]
When isAnimated is false and data is toggled on a chart from a larger amount of bars to a smaller number of bars, an opacity transition animation occurs even when isAnimated is false.

## Expected Behavior
Expecting no transition between graph states on the bar chart.

## Current Behavior
When changing the data on a chart from a larger number of bars to a smaller number, the original chart fades out on top of the new data. The transition to opacity 0 occurs in the drawBars function so always occurs regardless of whether the isAnimated property is set.
```
 bars.exit()
    .transition()
    .style('opacity', 0)
    .remove();
```

## Possible Solution
Potentially move the transition into `drawAnimatedBars`  so it only occurs when animation is required.

Happy to submit a PR if there is a solution for this !  😄 

## Steps to Reproduce (for bugs)

Reproduction: https://codepen.io/anon/pen/xygeyM

Click the toggle button to move between data sets.

## Your Environment

* Version used: 2.9.6
* Browser Name and version: Chrome 69
* Operating System and version: Mac OS
* Link to your project or codepen: https://codepen.io/anon/pen/xygeyM

**Comment by Golodhros** [comment]
Hi @mikerhyssm, thanks for opening the issue!

You are right in your diagnosis of the problem. If you could send a PR we would really appreciate it!!

Thanks a lot!
