### ISSUE TITLE
Stacked area chart ignores xTicks() and shows months incorrectly

### ISSUE THREAD

**Issue by rickardliljeberg** [eventbrite/britecharts#688]
I have a stacked area chart that looks fine when in a normal desktop size as can be seen here.

![image](https://user-images.githubusercontent.com/3726818/47785499-3812cb00-dd09-11e8-8f03-870ed1b3c545.png)

However, when the graph is loaded with a much smaller window i correctly chooses fewer ticks as you can see there are only 4 actual ticks on the smaller version. But on the month line under it seems to write "Dec" first, then all the other months after it. In this particlar graph I do show a year so it's correct timespan, just it should not show all months.

![image](https://user-images.githubusercontent.com/3726818/47785479-2b8e7280-dd09-11e8-91dd-2d256b1c30c7.png)

And this is how it looks on my actual phone aswell which is why this is a problem.
I also tried to use xTicks() but it's ignored. But really we see there is only 4 ticks on my screenshot but all months, so the problem is not really the ticks but rather a bug.

This codepen should display the problem but due to codepen and how it scales I cannot make it happen there (but the code in a local html file should do).
https://codepen.io/anon/pen/QZXmaJ/

**Comment by Golodhros** [comment]
Hi @rickardliljeberg, thanks for the issue.

Yeah, axis are tricky. They should fit there.

In the meanwhile, you could try to set a `xAxisFormat('custom')` and a custom format with `xAxisCustomFormat` when the width is less than a given value. This will effectively remove the month axis and allow you to set whatever format you want.

**Comment by rickardliljeberg** [comment]
Actually in my case I wanted this formatting with years and months anyway and that also solved my problem due to always only showing one year :-)

![image](https://user-images.githubusercontent.com/3726818/47803414-b9328800-dd32-11e8-9edb-3c0fec0347fa.png)

**Comment by rickardliljeberg** [comment]
Well, it still has the bug that when d3 changes number of ticks it still displays all items on the lower axis.

Mine only works because 

1. I only display one year
2. I wanted months and years, not days and months

If you had other spans or wanted to show for instance months and days it would still fail.
Personally I am fine, but it's up to you if the ticket should be closed with the bug in existance!

**Comment by Golodhros** [comment]
Thanks @rickardliljeberg!!

We'll close it for now, but we should probably have a docs page for these axes alone!
