### ISSUE TITLE
Truncation on bar charts can replace entire labels with ellipses

### ISSUE THREAD

**Issue by mikerhyssmith** [eventbrite/britecharts#691]
If the first word within a label is larger than the available space the entire label is replaced with ellipses.

![screenshot 2018-11-11 at 21 07 05](https://user-images.githubusercontent.com/7879587/48318273-d2bab600-e5f5-11e8-9bcd-a8a8a15539a4.png)

## Expected Behavior

To be able to identify the label of the data on the x or y axis.

## Current Behavior
Within the `wrapTextWithEllipses` function if the first word in a label is larger than the available space, that entire word is replaced with ellipses.

If you have many labels with long names this can lead to an entire axis consisting of ellipses.

## Possible Solution
Potentially if the first word is larger than the available space, cut it down to as many characters that can fit and add ellipses ?
Another potential option could be to allow truncation to be disabled within the bar chart so a CSS approach can be used ( which we have used on other charts)

Would be happy to submit a PR if either of these would be an appropriate fix :-) 

## Steps to Reproduce (for bugs)
Example: https://codepen.io/anon/pen/oQzPeG

## Context

Sometimes with labels with large words in or with currencies with a large number of 0s all the labels, particularly when the chart is horizontal, can be replaced making it impossible to identify what the chart is showing.

## Your Environment

* Version used: 2.9.8
* Browser Name and version: Chrome
* Operating System and version: MacOS
* Link to your project or codepen:https://codepen.io/anon/pen/oQzPeG

**Comment by Golodhros** [comment]
Hi @mikerhyssmith, thanks for opening this issue!

I think this is expected, you need to add a lot more left margin in order to give space for the labels.

**Comment by Golodhros** [comment]
Is this still an issue then?

**Comment by mikerhyssmith** [comment]
Hi @Golodhros sorry for the delay in getting back to you, work took over !

I suppose the reason I raised this as an issue is because this is the only chart that uses the internal wrapTextWithEllipses methods and there is no way for it to be disabled.

To get the behaviour we wanted with other charts we've been able to grab the label text, and replace it with a label with the css applied to truncate it. But on the bar chart, the text is truncated before it's rendered we can't do that ourselves.

If thats intended then Im more than happy for this to be closed, and thanks again for your quick replies 🙂

**Comment by Golodhros** [comment]
I see. How is the truncation you are doing with CSS different? 
I am not sure what would be the best way to go here...

**Comment by mikerhyssmith** [comment]
In the case where we use CSS it just trims it down to whatever will fit but will always includes the first word so for example reallyLongWord would become reall... rather than ...

I suppose ideally a config option for being able to switch it off, but I understand that's probably not that easy here.

We can adjust the margin depending on the size of the input for now so it's not a big deal 🙂 Thanks for taking a look !
