### ISSUE TITLE
Add hasLastHoverSliceHighlighted to donut chart

### ISSUE THREAD

**Issue by bootleq** [eventbrite/britecharts#692]
Hi, the donut's `hasFixedHighlightedSlice()` seems always highlight the slice set by `highlightSliceById()` initially, just good like the document says.

However, if we change the `highlightedSliceId` (for example, by using `highlightSliceById(4)` in a `customMouseOver` event), I would expect the fixed slice also change to it, while current behavior is keeping highlight the original slice.

This would be useful when we want to keep highlighting the last selected slice (after mouse out).

Version used: 2.9.8

**Comment by Golodhros** [comment]
Hi @bootleq, thanks for opening an issue!

Oh, I am curious, how are you doing to update the highlighted slice within a customMouseOver? Could you post a Codepen reproducing this behavior?

You could use this one as a jumpstart: https://codepen.io/Britecharts/pen/WZRMEp

**Comment by bootleq** [comment]
Thank you very much kindly provide a jumpstart!

What I tried is to call `highlightSliceById()` in customMouseOver, like codepen [bootleq/pen/wRGrPR](https://codepen.io/bootleq/pen/wRGrPR).
Trying to keep some slice highlighted, with respect the user's latest hover one.

**Comment by Golodhros** [comment]
Hi @bootleq, 
I see the confusion. In Britecharts, after changing the settings of a chart, we need to call it again on the same container. In your case, it means doing this:

```
  donutChart
    .isAnimated(false)
    .highlightSliceById(1)
    .width(containerWidth)
    .height(containerWidth)
    .externalRadius(containerWidth/2.5)
    .internalRadius(containerWidth/5)
    .hasFixedHighlightedSlice(true)
    .on('customMouseOut', function(slice) { 
      console.log("Trying set fixed slice", slice.data.id);
      donutChart.highlightSliceById(slice.data.id);
      donutContainer.call(donutChart);
    });
```

Note how I had to remove the initial animation, as we are re-rendering the whole chart after each mouseOut. This isn't ideal.

I think what you are looking for is a new option that could be named 'hasLastHoverSliceHighlighted' or similar.

**Comment by bootleq** [comment]
Thanks for explanation, now I understand the design.

I'm okay to close this issue, and besides, I found my original intention is to "keep last slice highlighted", similar to #365 with little difference, would be great if new option can be added.

**Comment by DalerAsrorov** [comment]
This can be closed.
