### ISSUE TITLE
Fixed height horizontal bars

### ISSUE THREAD

**Issue by gabitoju** [eventbrite/britecharts#693]
Hi, is there in which we can set a fixed height for a horizontal bar?
I took a look at the code and I can see that the height is set using the bandwith function: https://github.com/eventbrite/britecharts/blob/master/src/charts/bar.js#L452

Is there a way in which I can force that function to return a fixed size or I have to change the code to get this behavior?

Regards

**Comment by Golodhros** [comment]
Hi @gabitoju, thanks for opening this issue!

I don't think there is any way of fixing that height. What you could do is to play around with the height of the chart until you get something you are happy with and use it.

Sorry!
