### ISSUE TITLE
Line Chart allowing categorical data on the X axis

### ISSUE THREAD

**Issue by supazixi** [eventbrite/britecharts#699]
How do I draw a proper X-to-Y line chart with this? NOT every single dataset in this world is date-tagged.

**Comment by Golodhros** [comment]
Hi @supazixi, thanks for the issue and sorry for the delay on the response!

I am afraid that our line chart works only for time series. 

We could consider making it work with categorical data too, depending on how many people would like to see it happening.

I will transform this into a feature proposal and see.

Thanks a lot!

**Comment by Golodhros** [comment]
Oh, this seems to be duplicated with https://github.com/eventbrite/britecharts/issues/394

Closing this one.
