### ISSUE TITLE
Brush chart custom rounding

### ISSUE THREAD

**Issue by danielbater247** [eventbrite/britecharts#701]
I would like to be able to customise the rounding of dateExtentRounded in the brush charts handleBrushEnd event. Rounding to the nearest day as only option does not fulfil many use cases for us. 

## Expected Behavior
I would like to be able to set interval from brush chart config.
https://github.com/d3/d3-time#Intervals

## Current Behavior
Current is timeDay
https://github.com/eventbrite/britecharts/blob/master/src/charts/brush.js#L384

## Possible Solution
I would like to be able to set interval from brush chart config.
https://github.com/d3/d3-time#Intervals

## Context
I have graphs with lots of sample values within a day so only being able to select a day makes this of little worth.

## Your Environment
master branch.

**Comment by Golodhros** [comment]
Hi @danielbater247, thanks for the issue!

That sounds good! Let's do it.

We would need to store that rounding function in a variable at the top, maybe name it 'roundingTimeInterval'. Then we would need to create an accessor for it and add a test.

Would you be able to send a PR with this?

**Comment by danielbater247** [comment]
@Golodhros hows this?
https://github.com/eventbrite/britecharts/pull/702

**Comment by Golodhros** [comment]
Added and bumped!

**Comment by Golodhros** [comment]
Thanks a lot @danielbater247 !!
