### ISSUE TITLE
Disable hover effect on donut chart

### ISSUE THREAD

**Issue by carlkenne** [eventbrite/britecharts#703]
Is it possible to disable the hover effect on the donut chart? I still want the initial selected slice to be highlighted but just disable the mouse.

**Comment by Golodhros** [comment]
Hi @carlkenne, thanks for the issue!

To clarify, you mean you don't want to see the donut slice grow when you hover over it? I assume the central legend will still show the value, right?

**Comment by carlkenne** [comment]
Exactly, I want to get the mouseover event and text changes. But I would like to be able to turn off the grow part. I have a dashboard of many donut charts and it gets a bit much, visually, when you move the mouse over the page and all of them starts to move.
Although, I like the feature where an important slice is highlighted (grown) initially

**Comment by Golodhros** [comment]
I see. This is not possible at the moment but I think is a legit request.

We should add an option called 'hasHoverAnimation' that would be true by default. We would check that condition before growing the slice in https://github.com/Golodhros/britecharts/blob/master/src/charts/donut.js#L415
	
Would you be able to implement this and send us a PR?
