### ISSUE TITLE
lineChartDataByDate

### ISSUE THREAD

**Issue by Codemann12** [eventbrite/britecharts#738]
Hey,
when i pass the data format `LineChartData `to my line chart everything work just fine but when i change it to `lineChartDataByDate` then i received the following error: 
`Error: Data needs to have a dataByTopic or data property`. I am using the version 2.11.0 so this shouldn't produce any error right? However i added the  dataByTopic  property and now  there is this error: `TypeError: Cannot read property 'forEach' of undefined`.
What i am getting wrong?

**Comment by Golodhros** [comment]
Hi @Codemann12, thanks for opening this issue!

We have recently changed the way the line chart accepts data, although the old way also works. Right now, you should pass a data shape like this one(http://eventbrite.github.io/britecharts/global.html#LineChartData__anchor).

The response you get when passing `lineChartDataByDate` makes sense, it was never meant to accept the data ordered by date, that is something that the chart will calculate by itself. The error message is confusing though.

If you pass `dataByTopic`, then it needs to have a specific shape (http://eventbrite.github.io/britecharts/global.html#lineChartDataByTopic__anchor), probably yours doesn't have an array on 'dates'?

Anyways, I recommend you to use the regular `lineChartData` as it is the one we want to use going forward.

Hope this is useful!

**Comment by Codemann12** [comment]
Hi @Golodhros  thank you for the quick reply.
The problem is that i wanted to have an array of string on the `xAxis `and i don't really know how to do it with the `lineChartData `format. And if i change the `topicName `i would have many Independent lines and that not the purpose. 
My data:
`xAxis `:```[String_1, string_2,..., string_n]
yAxis: [number_1, number_2, ..., number_n]
```

**Comment by Golodhros** [comment]
Oh, I see. I'm sorry but our line chart doesn't support categorical data on
the X axis. This is something that other users have asked for, so we would
like to get to it as soon as possible.

Thanks again for using Britecharts!

**Comment by Codemann12** [comment]
That would be great.
Thank you for the support and i really enjoy Britecharts.
