### ISSUE TITLE
Line chart round up input value greater than 100

### ISSUE THREAD

**Issue by Tsatia** [eventbrite/britecharts#748]
I am using line chart and every time my input `value` (float) is greater than 100 the value is round up to "some" integer value.
For  `[357.14020388074823, 357.25020392220705, 357.14971965367164]` the tooltip shows
`[360,360,360]`.

## Input
`[357.14020388074823, 357.25020392220705, 357.14971965367164]`
## Expected Behavior
`[357.14020388074823, 357.25020392220705, 357.14971965367164]`

## Current Behavior
`[360,360,360]`
## Codepen
https://codepen.io/tsatia/pen/RXRvjJ?editors=1010

Moreover is it possible for me to have strings like "monday", "tuesday"... on the xAxis while using  line chart?

**Comment by Golodhros** [comment]
Hi @Tsatia, thanks for the issue!

You can customize the tooltip value format using the numberFormat accessor (http://eventbrite.github.io/britecharts/module-Tooltip.html#.numberFormat__anchor). You can also play with different number formats here: http://bl.ocks.org/zanarmstrong/05c1e95bf7aa16c4768e

Similarly, for the date formats you can use http://eventbrite.github.io/britecharts/module-Tooltip.html#.dateCustomFormat__anchor

Let me know if you need something else!

**Comment by Tsatia** [comment]
Hey @Golodhros, thanks for the quick reply.

Ok this is working just fine but it would be great if the tooltip can display the same data that are parse to the line chart without any need of customization. 
I was a little bit  frustrated by this behavior 🤒

**Comment by Golodhros** [comment]
Thanks for the feedback @Tsatia!

I think we chose a smaller format due to space constraints in the tooltip, but is good to know it was frustrating for you!
