### ISSUE TITLE
Chart data distribution

### ISSUE THREAD

**Issue by gabitoju** [eventbrite/britecharts#762]
Hi everyone. I'm looking for a way to chart something like a normal distribution or any distribution actually using britecharts.

The chart would be something like this:
![normal](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_HypothesisTest-Means-Proportions/Standard%20Normal%20Distribution%20upper%20tail.png)

I've been looking into the line chart and the sparkline chart but they work with dates not with numerical data.

Is there a way to create this charts using britecharts?

**Comment by Golodhros** [comment]
Hi @gabitoju, thanks for creating this issue!

At the moment we don't support line charts with non-timeseries data. It has been a request from many people, so it should become part of the library soon. 

In the meanwhile, the only way I see this working would be using a bar chart.

Thanks!

**Comment by gabitoju** [comment]
Thanks for the answer @Golodhros.

Right now that's what we are doing, using the bar chart to represent a distribution and also as a sort of historgram (that would also be a nice chart to have).

I'm closing the issue.

Regards!
