### ISSUE TITLE
Heatmap for hourly categorical data

### ISSUE THREAD

**Issue by Tsatia** [eventbrite/britecharts#763]
Hi,
for now the heatmap allow us only to have data of type number. The  `yAxis `takes only `days `of type `number `and `xAxis `hours of type `number`. What if i want to have `string `there?  I mean something like this: 

![Bildschirmfoto_von_2019-10-25_10-39-54](https://user-images.githubusercontent.com/27213628/68942319-9e4d7d00-07a8-11ea-8ea6-539b103b20b4.png)

**Comment by Golodhros** [comment]
Hi @Tsatia, thanks for the feature proposal!

That's a totally legit use case and I agree it would be useful for this component to support this use case!
