### ISSUE TITLE
Breaking changes in Version 2.13.0 with ES6 refactor

### ISSUE THREAD

**Issue by brendanmckeown** [eventbrite/britecharts#771]
Version 2.13.0 introduced breaking changes in the form of a refactor to ES6 modules. Existing projects that import code using the `require` statement will no longer work – these must be changed to `import` statements.

## Expected Behavior
- Updating this library to the latest **minor** version should not break an existing implementation.

## Current Behavior
- If an implementation uses `require` statements to import code from this package, it will break when version 2.13.0 is installed.

## Possible Solution
- A major refactor like this one should have been a **major** version bump because it can break existing implementations. 

## Context
My project that depends on britecharts was set in `package.json` to use the latest minor version (`^2.4.9`) before version 3. The Javascript is bundled with Webpack, and uses `require` statements to import code from the `britecharts` package.

For example:
```
const donut = require('britecharts/src/charts/donut');
let chart = donut();
```
However, a recent build process for my project downloaded version 2.13.0, which caused an error and led to the charts not rendering. In order to fix this error, I had to change my implementation code to use an `import` statement instead.
```
import donut from 'britecharts/src/charts/donut';
let chart = donut();
```

## Your Environment
* Britecharts version used: 2.13.0
* Webpack 4
* Babel 7

**Comment by Golodhros** [comment]
Wow! Yeah, this wasn't expected and we need to fix.
I will probably revert the changes.

Thanks for the heads up @brendanmckeown !!

**Comment by Golodhros** [comment]
Hi @brendanmckeown,

I have just published 13.1 without the ES modules thing. Let me know if everything went back to normal!

This issue surfaced the need for us to have a test project to make sure the installation instructions are working, the same way we have for Britecharts-React (https://github.com/Golodhros/britecharts-react-test-project).

Thanks for your patience and sorry again for the inconvenience!

**Comment by brendanmckeown** [comment]
@Golodhros - thanks for addressing this issue so quickly!

**Comment by Golodhros** [comment]
Sure! Sorry for the inconvenience!
