### ISSUE TITLE
Bullet chart not working

### ISSUE THREAD

**Issue by topinvestor** [eventbrite/britecharts#774]
I need to implement a bulletchart.

Created the following Codepen:
https://codepen.io/topinvestor/pen/yLyNqZN

Here is the code:

var dataset = [
  {
            "title": "CPU 1",
            "subtitle": "GHz",
            "ranges": [1500, 2100, 3500],
            "measures": [1800, 2200],
            "markers": [2600]
        }

];

function createBulletChart() {
let bulletChart = new britecharts.bullet();
const bulletContainer = d3.select('.js-bullet-chart-container');

  bulletChart
    .height(300)
    .height(600);
  
  bulletContainer
    .datum(dataset)
    .call(bulletChart);
  

}

createBulletChart();

I cannot see the bullet chart working.

**Comment by Golodhros** [comment]
Hi @topinvestor, thanks a lot for opening this issue!

Yes, there was a problem with the chart import for the britecharts bundle. I will open a PR and let you know when it is fixed.

**Comment by Golodhros** [comment]
Version 2.13.2 of Britecharts should have this fixed.
Please check your codePen in some minutes

**Comment by topinvestor** [comment]
Do I have to update the import statements in codepen? Because I don't see a change.

**Comment by Golodhros** [comment]
You will need to open the browser console to see what's not working on the CodePen.

In this case, your dataset is an array, when it should be only the object. If you remove the "[]" it works as expected.

**Comment by topinvestor** [comment]
I changed it to:

var dataset = {
            "title": "CPU 1",
            "subtitle": "GHz",
            "ranges": [1500, 2100, 3500],
            "measures": [1800, 2200],
            "markers": [2600]
        };
But there is no difference.

It would be nice if you get my example and fork it to get it working.

**Comment by Golodhros** [comment]
Here is my fork: https://codepen.io/Britecharts/pen/rNaOoMM?editors=1010#0

**Comment by topinvestor** [comment]
Thank you.

But here is what I see - there is no chart. It is blank:

<img width="977" alt="BulletChart" src="https://user-images.githubusercontent.com/28638245/70393874-d1e48700-19a3-11ea-9665-aa81680c74fd.png">

**Comment by Golodhros** [comment]
Try doing a hard refresh Ctrl+shift+R
