### ISSUE TITLE
Error: <rect> attribute height: A negative value is not valid. ("-348")

### ISSUE THREAD

**Issue by amahterian-github** [eventbrite/britecharts#784]
## Expected Behavior
A height and width are being set on my chart container. I expect no issues in the console.

## Current Behavior
I'm seeing the following error in the console, even though the boundingClientRect has an assigned width and height. Please see screenshot.

## Possible Solution
I've tried reordering my data ( ordering by both ascending date and ascending stack order ), removing higher-valued data points that might edge out smaller ones ( possibly generating the rendering error ), filling in stack gaps with zeroed data to make everything homogenous, updating Britecharts to 2.13 from 2.12, and forcing height and width with CSS and chart configuration. I cannot get the errors to disappear.

## Steps to Reproduce
Providing the following data set to a stackedBarChart creates the error seen in the screenshot.

`[{name: "Test1", date: "12/01", value: 9378, stack: 1},
{name: "Test2", date: "12/01", value: 135357, stack: 2},
{name: "Test3", date: "12/01", value: 14230057827, stack: 3},
{name: "Test4", date: "12/01", value: 7246940111, stack: 4},
{name: "Test5", date: "12/01", value: 44731804, stack: 5},
{name: "Test6", date: "12/01", value: 142205244, stack: 6},
{name: "Test1", date: "12/02", value: 19335, stack: 1},
{name: "Test2", date: "12/02", value: 174201, stack: 2},
{name: "Test3", date: "12/02", value: 17226732277, stack: 3},
{name: "Test4", date: "12/02", value: 10211900786, stack: 4},
{name: "Test5", date: "12/02", value: 55913698, stack: 5},
{name: "Test6", date: "12/02", value: 148038887, stack: 6},
{name: "Test7", date: "12/02", value: 8374, stack: 7},
{name: "Test1", date: "12/03", value: 23630, stack: 1},
{name: "Test2", date: "12/03", value: 204863, stack: 2},
{name: "Test3", date: "12/03", value: 17791562411, stack: 3},
{name: "Test4", date: "12/03", value: 9326094636, stack: 4},
{name: "Test5", date: "12/03", value: 49869637, stack: 5},
{name: "Test6", date: "12/03", value: 142239144, stack: 6},
{name: "Test7", date: "12/03", value: 4210, stack: 7}]`

## Screenshots
<img width="751" alt="Screen Shot 2019-12-23 at 2 23 46 PM" src="https://user-images.githubusercontent.com/8904305/71376602-035a7680-2590-11ea-8f78-1f1022ee961b.png">

## Your Environment
* Britecharts version used: 2.12.0
* Browser Name and version: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
* Operating System and version: MacOS 10.14.6 (18G103) Mojave

**Comment by Golodhros** [comment]
Hi @amahterian-github, thanks for opening this issue!

Could you try to reproduce your issue in a Codepen? You could use [this one](https://codepen.io/Britecharts/pen/bogLrB) as a starting point.

Thanks!

**Comment by amahterian-github** [comment]
Here's my codepen, but I'm using Britecharts in a Vue context. I'm not sure how to represent that in CodePen.
https://codepen.io/amahterian/pen/dyPRpMe?editors=1112

**Comment by Golodhros** [comment]
Hi @amahterian-github,

the first issue I see is that there is a value missing in your data. If I add

           {name: "Test7", date: "12/01", value: 8374, stack: 7},
it stops failing.

It is weird that it doesn't fail on Firefox.

**Comment by amahterian-github** [comment]
Stranger still that I tried this before, as I mentioned above, ie " filling in stack gaps with zeroed data to make everything homogenous". I added the line you mentioned and the errors did stop. I'll try this with actual live data and verify that it's fixed. Thank you!
