### ISSUE TITLE
Add images to chart

### ISSUE THREAD

**Issue by cooltaiwanesesam** [eventbrite/britecharts#798]
I'm working on a horizontal bar chart with long text label on y-axis, and #135 helps to increase the margin from configuration, but it would be good if I can use icon images to replace the text label as an alternative.

I found a solution for the pure D3 chart on [Stack-overflow](https://stackoverflow.com/a/40508510/10303614), but I struggle to replicate it in Britecharts

Hope to get some tips on how to insert images to Britecharts

**Comment by Golodhros** [comment]
Hi @cooltaiwanesesam, thanks for opening a ticket!

Interesting, I think you can still do it by first rendering the chart, with hidden y labels and then insert your images there.

I would try to do something like:
```
.y-axis-group .tick text {display: none;}

// then, with JavaScript, do:
$('.y-axis-group .tick').forEach((item, index) => {
    let image = document.createElement('img');
    image.src = //whatever depending on the index
    item.appendElement(image);
});
```

Or something similar.

If you could try to put together a demo on a codepen using this example (https://codepen.io/Britecharts/pen/yzgvoP) I could give you more hints.

**Comment by cooltaiwanesesam** [comment]
Hi @Golodhros, thanks for your response.

I'm using Vuejs, and I'd like to avoid adding jQuery as another dependency.

This is what I have got so far (https://codepen.io/cooltaiwanesesam/pen/jObENQz), and I feel I'm missing something, but I couldn't figure out what is missing.

**Comment by Golodhros** [comment]
Hi @cooltaiwanesesam,

I see. You were trying to operate on the chart before rendering it. Remember that we don't draw anything until we call the chart with the .call function.

Here is a codepen with this working (more or less, you probably would want to create a hash with the data by name).
https://codepen.io/Britecharts/pen/mdeypxv?editors=0010

Hope this helps!

**Comment by cooltaiwanesesam** [comment]
Brilliant, thanks so much for your help @Golodhros

**Comment by Golodhros** [comment]
Glad to help!
