### ISSUE TITLE
Support for arbitrary x-axis formats

### ISSUE THREAD

**Issue by ajdani** [eventbrite/britecharts#800]
Hello!

Currently the x-axis values rely heavily on the fact that dates are passed as x-axis value and arbitrary other values would not work.

So, e.g. it is currently not possible to plot the line-chart of a simple linear function:
$f(x) = kx + d$ where $x \in \mathbb{N}$ but not a date

## Expected Behavior
Instead of a format which depends on dates we can pass arbitrary numerical values as x-values to the specific chart and don't treat them as timestamp but as the numbers given instead.

## Difference from Current Behavior
Currently only strings are allowed as x-values and they are treated as dates. The main difference would be to allow numbers as well and treat them differently.

## Possible Implementation
Currently no ideas, I guess there will be many changes necessary and touching files in many points of the library will be necessary (e.g. tooltips and all other features which rely heavily on the fact that dates are processed)

## Context
Why this idea? I would like to plot different kind of data, not only date-bound.

**Comment by Golodhros** [comment]
Hi @ajdani, thanks for opening this issue!

Yes, this has been requested before, you can see more details or add comments on this issue: https://github.com/eventbrite/britecharts/issues/394

I will close this ticket as a duplicate for now.
Thanks!
